import {geometryTopics,geometryFormulas} from './geometry-content';
import {matrixTopics,matrixFormulas} from './matrix-content';
import {modernMathTopics,modernMathFormulas} from './modern-math-content';
import {trigonometryTopics,trigonometryFormulas} from './trigonometry-content';
import {unicodeFormulas} from './unicode-math';
export type Topic={id:string;name:string;description:string;symbol:string;color:string;level:string};
export const topics:Topic[]=[
{id:'algebra',name:'Đại số cơ bản',description:'Hằng đẳng thức, đa thức và phương trình',symbol:'(a + b)²',color:'blue',level:'THCS'},
{id:'powers',name:'Lũy thừa & căn thức',description:'Quy tắc lũy thừa, căn và biến đổi',symbol:'ⁿ√x',color:'purple',level:'THCS'},
{id:'inequalities',name:'Bất đẳng thức',description:'Từ AM–GM đến tư duy Olympic',symbol:'a + b ≥ 2√ab',color:'orange',level:'THPT'},
...trigonometryTopics,
{id:'sequences',name:'Cấp số',description:'Quy luật, số hạng và tổng',symbol:'1, 2, 4, 8…',color:'green',level:'THPT'},
{id:'logarithms',name:'Logarit',description:'Cơ số, phép biến đổi và hàm ngược',symbol:'logₐ b',color:'blue',level:'THPT'},
{id:'complex',name:'Số phức & Euler',description:'Từ mặt phẳng phức đến đường tròn',symbol:'eⁱᶿ = cos θ + i sin θ',color:'purple',level:'THPT'},
{id:'calculus',name:'Giải tích',description:'Giới hạn, đạo hàm và tích phân',symbol:'∫ f(x) dx',color:'green',level:'Đại học cơ bản'},
...matrixTopics,
...modernMathTopics,
...geometryTopics];
export type Formula={id:string;topic:string;name:string;latex:string;unicodeMath?:string;diagram?:string;condition:string;theory:string;proof:string;example:string;exampleSolution?:string;tip:string;mistake:string;question:string;answer:number;solution:string;equality?:string;advanced?:string};
let serial=0;
function f(topic:string,name:string,latex:string,condition:string,theory:string,proof:string,example:string,exampleSolution:string,mistake:string,question:string,answer:number,solution:string,extra:Partial<Formula>={}):Formula{return {id:`f${++serial}`,topic,name,latex,condition,theory,proof,example,exampleSolution,mistake,question,answer,solution,tip:'Xác định điều kiện trước, nhận dạng công thức, rồi thay số và kiểm tra lại.',...extra}}
const r=String.raw;
export const formulas:Formula[]=[
f('algebra','Bình phương của một tổng',r`(a+b)^2=a^2+2ab+b^2`,'a, b là số thực.','Bình phương một tổng gồm hai bình phương và hai lần tích.','Nhân (a+b)(a+b), phân phối và nhóm hai số hạng ab.','Tính nhanh 103² bằng cách áp dụng hằng đẳng thức bình phương của một tổng.','• Tách số thành tổng tròn chục: 103 = 100 + 3.\n• Áp dụng công thức (a + b)² = a² + 2ab + b² với a = 100, b = 3:\n• Khai triển: 103² = (100 + 3)² = 100² + 2 × 100 × 3 + 3²\n• Thực hiện tính toán: = 10 000 + 600 + 9 = 10 609.\n• Kết luận: 103² = 10 609.','Không được bỏ 2ab.','Tính (10+3)².',169,'100 + 60 + 9 = 169.'),
f('algebra','Bình phương của một hiệu',r`(a-b)^2=a^2-2ab+b^2`,'a, b ∈ ℝ.','Khai triển bình phương của hiệu.','Thay b bằng −b trong bình phương của tổng.','Tính nhanh 98² bằng cách áp dụng hằng đẳng thức bình phương của một hiệu.','• Tách số thành hiệu tròn trăm: 98 = 100 − 2.\n• Áp dụng công thức (a − b)² = a² − 2ab + b² với a = 100, b = 2:\n• Khai triển: 98² = (100 − 2)² = 100² − 2 × 100 × 2 + 2²\n• Thực hiện tính toán: = 10 000 − 400 + 4 = 9 604.\n• Kết luận: 98² = 9 604.','Số hạng cuối là +b².','Tính (10−2)².',64,'100−40+4 = 64.'),
f('algebra','Hiệu hai bình phương',r`a^2-b^2=(a-b)(a+b)`,'a, b ∈ ℝ.','Chuyển hiệu thành tích để rút gọn hoặc nhẩm nhanh.','Khai triển vế phải, −ab và +ab triệt tiêu.','Tính nhanh giá trị của biểu thức 51² − 49².','• Nhận dạng dạng toán: Biểu thức có dạng a² − b² với a = 51 và b = 49.\n• Áp dụng hằng đẳng thức: a² − b² = (a − b)(a + b)\n• Thay số: 51² − 49² = (51 − 49)(51 + 49)\n• Tính nhẩm: = 2 × 100 = 200.\n• Kết luận: 51² − 49² = 200.','a²+b² không bằng (a+b)(a−b).','Tính 21²−19².',80,'(21−19)(21+19)=2×40=80.'),
f('algebra','Lập phương của tổng và hiệu',r`(a\pm b)^3=a^3\pm3a^2b+3ab^2\pm b^3`,'a, b ∈ ℝ.','Hệ số khai triển là 1, 3, 3, 1.','Nhân (a±b)² với (a±b) rồi thu gọn.','Khai triển biểu thức đại số (x + 2)³.','• Áp dụng công thức (a + b)³ = a³ + 3a²b + 3ab² + b³ với a = x, b = 2:\n• Khai triển từng số hạng:\n  - a³ = x³\n  - 3a²b = 3 × x² × 2 = 6x²\n  - 3ab² = 3 × x × 2² = 12x\n  - b³ = 2³ = 8\n• Thu gọn biểu thức: (x + 2)³ = x³ + 6x² + 12x + 8.','Với hiệu, số hạng 3ab² vẫn dương.','Tính (2+3)³.',125,'5³ = 125.'),
f('algebra','Tổng và hiệu hai lập phương',r`a^3\pm b^3=(a\pm b)(a^2\mp ab+b^2)`,'a, b ∈ ℝ.','Phân tích tổng hoặc hiệu lập phương thành nhân tử.','Nhân hai thừa số; các số hạng hỗn hợp triệt tiêu.','Phân tích đa thức 8x³ − 1 thành nhân tử.','• Đưa về dạng hiệu hai lập phương: 8x³ − 1 = (2x)³ − 1³.\n• Áp dụng công thức a³ − b³ = (a − b)(a² + ab + b²) với a = 2x, b = 1:\n• Thay vào biểu thức: = (2x − 1)[(2x)² + (2x)(1) + 1²]\n• Thu gọn: = (2x − 1)(4x² + 2x + 1).\n• Kết luận: 8x³ − 1 = (2x − 1)(4x² + 2x + 1).','Dấu của ab ở thừa số thứ hai ngược dấu bên ngoài.','Tính 4³−3³.',37,'64−27=37.'),
f('algebra','Phân thức đại số',r`\frac{A}{B}+\frac{C}{D}=\frac{AD+BC}{BD}`,'B ≠ 0, D ≠ 0; giữ mọi điều kiện ban đầu sau khi rút gọn.','Phân thức là thương của hai đa thức, mẫu khác 0.','Quy đồng hai mẫu thành BD.','Rút gọn phân thức đại số (x² − 1) / (x − 1) và tìm điều kiện xác định.','• Bước 1: Tìm điều kiện xác định (mẫu số khác 0): x − 1 ≠ 0 ⇒ x ≠ 1.\n• Bước 2: Phân tích tử số thành nhân tử: x² − 1 = (x − 1)(x + 1).\n• Bước 3: Triệt tiêu nhân tử chung (x − 1):\n  (x² − 1) / (x − 1) = (x − 1)(x + 1) / (x − 1) = x + 1 (với x ≠ 1).\n• Kết luận: Phân thức rút gọn bằng x + 1 kèm điều kiện x ≠ 1.','Không cộng trực tiếp hai mẫu số.','Tính 1/2 + 3/2.',2,'Cùng mẫu: (1+3)/2=2.'),
f('algebra','Đa thức và định lý phần dư',r`P(x)=(x-a)Q(x)+P(a)`,'P là đa thức; chia cho đa thức bậc nhất x−a.','Phần dư khi chia P(x) cho x−a bằng P(a).','Theo phép chia đa thức, dư là hằng r; thay x=a suy ra r=P(a).','Tìm phần dư khi chia đa thức P(x) = x² + 2x + 3 cho nhị thức x − 1 mà không cần thực hiện phép chia.','• Áp dụng định lý phần dư (định lý Bézout): Khi chia đa thức P(x) cho x − a thì số dư là r = P(a).\n• Ở đây, số chia là x − 1 nên a = 1.\n• Tính P(1): r = P(1) = 1² + 2(1) + 3 = 1 + 2 + 3 = 6.\n• Kết luận: Phần dư của phép chia bằng 6.','Không nhầm chia x+a với thế x=a.','Dư của x²+1 khi chia cho x−2?',5,'P(2)=4+1=5.'),
f('algebra','Đồng nhất thức đa thức',r`\begin{aligned}P(x)\equiv Q(x)\quad\Longleftrightarrow\quad&a_0=b_0,\ a_1=b_1,\\&\ldots,\ a_n=b_n\end{aligned}`,'Đẳng thức đúng với mọi x thực.','Hai đa thức bằng nhau đồng nhất khi mọi hệ số tương ứng bằng nhau.','Hiệu hai vế có vô số nghiệm nên là đa thức 0.','Tìm các hệ số A và B nếu biết đẳng thức Ax + B ≡ 2x + 3 đúng với mọi giá trị x.','• Theo định lý đồng nhất thức: Hai đa thức bằng nhau với mọi x khi và chỉ khi mọi hệ số tương ứng cùng bậc bằng nhau.\n• Cân bằng hệ số của biến x ở hai vế: A = 2.\n• Cân bằng hệ số tự do ở hai vế: B = 3.\n• Kết luận: A = 2 và B = 3.','Đúng ở một giá trị x chưa đủ là đồng nhất thức.','Nếu Ax+4 ≡ 3x+4 thì A bằng bao nhiêu?',3,'So sánh hệ số x: A=3.'),
f('algebra','Phương trình bậc nhất',r`ax+b=0\Rightarrow x=-\frac ba`,'a ≠ 0; nếu a=0 xét b=0 hoặc b≠0 riêng.','Tìm giá trị của biến làm đẳng thức đúng.','Trừ b rồi chia cả hai vế cho a.','Giải phương trình bậc nhất một ẩn: 3x − 12 = 0.','• Bước 1: Chuyển hằng số sang vế phải và đổi dấu: 3x = 12.\n• Bước 2: Chia cả hai vế cho hệ số của x là a = 3 (do 3 ≠ 0):\n  x = 12 / 3 = 4.\n• Bước 3: Kết luận: Phương trình có nghiệm duy nhất x = 4.','Chia cho a mà chưa xét a=0.','Giải 2x−10=0.',5,'2x=10 ⇒ x=5.'),
f('algebra','Phương trình bậc hai',r`\begin{aligned}\Delta&=b^2-4ac\\[4pt]x&=\frac{-b\pm\sqrt\Delta}{2a}\end{aligned}`,'a ≠ 0; nghiệm thực khi Δ ≥ 0.','Δ>0: hai nghiệm; Δ=0: nghiệm kép; Δ<0: không có nghiệm thực.','Hoàn thành bình phương: (2ax+b)² = Δ.','Giải phương trình bậc hai: x² − 5x + 6 = 0.','• Bước 1: Xác định các hệ số: a = 1, b = −5, c = 6.\n• Bước 2: Tính biệt thức Δ:\n  Δ = b² − 4ac = (−5)² − 4(1)(6) = 25 − 24 = 1.\n• Bước 3: Vì Δ > 0 nên phương trình có hai nghiệm phân biệt:\n  x₁ = (−b − √Δ) / (2a) = (5 − √1) / 2 = 4 / 2 = 2\n  x₂ = (−b + √Δ) / (2a) = (5 + √1) / 2 = 6 / 2 = 3.\n• Kết luận: Phương trình có hai nghiệm là x = 2 và x = 3.','Mẫu là toàn bộ 2a.','Nghiệm lớn hơn của x²−5x+6=0?',3,'Δ=1; x=(5±1)/2; nghiệm lớn là 3.'),
f('algebra','Hệ phương trình tuyến tính',r`D=a_1b_2-a_2b_1,\quad x=\frac{c_1b_2-c_2b_1}{D}`,'Hệ a₁x+b₁y=c₁, a₂x+b₂y=c₂; công thức khi D≠0.','D≠0 cho nghiệm duy nhất; D=0 phải xét tương thích.','Nhân phương trình đầu với b₂, phương trình sau với b₁ rồi trừ để khử y.','Giải hệ phương trình bậc nhất hai ẩn: x + y = 5 và x − y = 1.','• Bước 1: Dùng phương pháp cộng đại số, cộng hai phương trình vế theo vế:\n  (x + y) + (x − y) = 5 + 1 ⇒ 2x = 6 ⇒ x = 3.\n• Bước 2: Thay x = 3 vào phương trình x + y = 5:\n  3 + y = 5 ⇒ y = 2.\n• Kết luận: Hệ phương trình có nghiệm duy nhất là (x, y) = (3, 2).','D=0 không tự động có nghĩa vô nghiệm.','Với x+y=7, x−y=1, tìm x.',4,'Cộng hai phương trình: 2x=8 ⇒ x=4.'),
f('algebra','Giá trị tuyệt đối',r`|x|=\begin{cases}x&x\ge0\\-x&x<0\end{cases}`,'x ∈ ℝ.','Khoảng cách từ điểm x đến 0 trên trục số.','Khoảng cách luôn không âm; xét hai phía của 0.','Tính giá trị của |−7| và tìm các nghiệm của phương trình |x| = 3.','• Tính |−7|: Vì −7 < 0 nên |−7| = −(−7) = 7.\n• Giải phương trình |x| = 3: Giá trị tuyệt đối biểu thị khoảng cách đến 0 bằng 3, do đó có hai điểm đối xứng:\n  x = 3 hoặc x = −3.\n• Kết luận: |−7| = 7; phương trình có hai nghiệm x = ±3.','|x|=a với a<0 vô nghiệm.','Tính |−8|.',8,'−8<0 nên |−8|=−(−8)=8.'),
f('algebra','Hàm số bậc nhất',r`f(x)=ax+b`,'x ∈ ℝ; a≠0 nếu gọi là hàm số bậc nhất.','Mỗi x có đúng một giá trị y; a là hệ số góc.','f(x+h)−f(x)=ah, nên tỉ lệ thay đổi bằng a.','Cho hàm số bậc nhất f(x) = 2x + 1. Tính giá trị của hàm số tại x = 3.','• Nhận dạng hàm số: Hệ số góc a = 2, tung độ gốc b = 1.\n• Thay giá trị x = 3 vào hàm số:\n  f(3) = 2 × (3) + 1.\n• Tính toán: f(3) = 6 + 1 = 7.\n• Kết luận: Giá trị của hàm số tại x = 3 là f(3) = 7.','Phân biệt f(x) với f·x.','Với f(x)=3x−2, tính f(4).',10,'3×4−2=10.'),
f('powers','Quy tắc lũy thừa',r`a^ma^n=a^{m+n},\quad (a^m)^n=a^{mn}`,'Trong bài này a>0, m,n∈ℝ; có thể mở rộng riêng cho số mũ nguyên.','Lũy thừa nguyên dương là phép nhân lặp; mở rộng bằng tính liên tục.','Với số mũ nguyên, đếm số thừa số a; với số mũ thực, dùng aᵗ=exp(t ln a).','Tính giá trị của biểu thức lũy thừa: 2³ × 2⁴.','• Áp dụng quy tắc nhân hai lũy thừa cùng cơ số: aᵐ × aⁿ = aᵐ⁺ⁿ.\n• Giữ nguyên cơ số 2 và cộng hai số mũ: 2³ × 2⁴ = 2³⁺⁴ = 2⁷.\n• Tính giá trị số: 2⁷ = 128.\n• Kết luận: 2³ × 2⁴ = 128.','Không áp dụng aᵐ+aⁿ=aᵐ⁺ⁿ.','Tính 2³ × 2².',32,'2⁵=32.'),
f('powers','Căn bậc hai',r`\sqrt{a^2}=|a|,\quad\sqrt{ab}=\sqrt a\sqrt b`,'a,b≥0 ở quy tắc tích; √(a²)=|a| với mọi a thực.','√a là số không âm có bình phương bằng a.','Hai vế quy tắc tích không âm và bình phương đều bằng ab.','Tính giá trị của √((-3)²) và căn của tích √(4 × 9).','• Với biểu thức √((-3)²): Áp dụng hằng đẳng thức căn bậc hai √(a²) = |a|:\n  √((-3)²) = |−3| = 3 (lưu ý: kết quả luôn không âm, không phải −3).\n• Với √(4 × 9): Áp dụng quy tắc khai phương một tích √(ab) = √a × √b:\n  √(4 × 9) = √4 × √9 = 2 × 3 = 6.\n• Kết luận: √((-3)²) = 3 và √(4 × 9) = 6.','√(a+b) không bằng √a+√b.','Tính √81.',9,'9≥0 và 9²=81.'),
f('powers','Căn bậc ba',r`\sqrt[3]{a^3}=a`,'a ∈ ℝ.','Căn bậc lẻ giữ dấu của số dưới căn.','Hàm x³ đồng biến trên ℝ, nên có hàm ngược duy nhất.','Tính giá trị của căn bậc ba: ∛(−125).','• Phân tích số dưới căn thành lập phương: (−5)³ = (−5) × (−5) × (−5) = −125.\n• Áp dụng quy tắc căn bậc lẻ: ∛(a³) = a với mọi số thực a (căn bậc lẻ giữ nguyên dấu của số dưới căn).\n• Suy ra: ∛(−125) = ∛((−5)³) = −5.\n• Kết luận: ∛(−125) = −5.','Không thêm giá trị tuyệt đối cho căn bậc lẻ.','Tính ∛(−27).',-3,'(−3)³=−27.'),
f('powers','Căn bậc n',r`\sqrt[n]{a}=a^{1/n}`,'n nguyên ≥2; ở công thức lũy thừa thực dùng a≥0. Với n lẻ, căn còn xác định cho a<0.','Căn bậc chẵn lấy nghiệm không âm; căn bậc lẻ có thể âm.','Định nghĩa nghiệm x của xⁿ=a với quy ước dấu tương ứng.','Tìm giá trị số học của căn bậc bốn: ⁴√16.','• Nhận xét: 2⁴ = 16 và (−2)⁴ = 16.\n• Theo định nghĩa căn bậc chẵn số học: ⁴√a là số không âm duy nhất x sao cho x⁴ = a.\n• Do đó ta chọn giá trị dương: ⁴√16 = 2.\n• Kết luận: ⁴√16 = 2.','⁴√16 không bằng ±2; phương trình x⁴=16 mới có hai nghiệm thực.','Tính ⁴√81.',3,'3⁴=81, lấy giá trị không âm.'),
f('powers','Biến đổi căn thức',r`\frac1{\sqrt a+\sqrt b}=\frac{\sqrt a-\sqrt b}{a-b}`,'a,b≥0, a≠b trong công thức này.','Nhân với biểu thức liên hợp để khử căn ở mẫu.','(√a+√b)(√a−√b)=a−b.','Trục căn thức ở mẫu của phân số: 1 / (√3 + √2).','• Nhân cả tử và mẫu với lượng liên hợp của mẫu là (√3 − √2):\n  1 / (√3 + √2) = (√3 − √2) / [(√3 + √2)(√3 − √2)]\n• Khai triển hằng đẳng thức hiệu hai bình phương ở mẫu:\n  (√3)² − (√2)² = 3 − 2 = 1.\n• Thu gọn kết quả:\n  (√3 − √2) / 1 = √3 − √2.\n• Kết luận: Biểu thức rút gọn là √3 − √2.','Khi a=b công thức bên phải không xác định.','Tính √12 × √3.',6,'√36=6.'),
f('inequalities','AM–GM',r`\frac{a_1+\cdots+a_n}{n}\ge\sqrt[n]{a_1\cdots a_n}`,'aᵢ≥0, n nguyên dương.','Trung bình cộng không nhỏ hơn trung bình nhân.','Với hai số: (√a−√b)²≥0 ⇒ a+b≥2√ab. Bản n số suy ra bằng quy nạp hoặc tính lõm của ln (và giới hạn khi có số 0).','Áp dụng bất đẳng thức AM–GM cho hai số dương a = 1 và b = 9.','• Kiểm tra điều kiện: a = 1 > 0 và b = 9 > 0 (thỏa mãn).\n• Bất đẳng thức AM–GM: (a + b) / 2 ≥ √(ab) ⇔ a + b ≥ 2√(ab).\n• Tính vế trái (tổng): a + b = 1 + 9 = 10.\n• Tính vế phải: 2√(1 × 9) = 2√9 = 2 × 3 = 6.\n• So sánh: 10 ≥ 6 (luôn đúng). Dấu bằng chỉ xảy ra khi a = b.','Không áp dụng AM–GM cho các số âm.','Giá trị nhỏ nhất của x+4/x với x>0?',4,'AM–GM cho x+4/x≥2√4=4; bằng khi x=2.',{equality:'Tất cả các aᵢ bằng nhau.',advanced:'Dạng Olympic: với x,y,z>0 và xyz=1, x+y+z≥3. Áp dụng AM–GM ba số; bằng tại x=y=z=1.'}),
f('inequalities','Cauchy–Schwarz',r`\left(\sum a_ib_i\right)^2\le\left(\sum a_i^2\right)\left(\sum b_i^2\right)`,'Hai dãy hữu hạn số thực cùng độ dài.','Độ lớn tích vô hướng không vượt tích độ dài.','Dùng ∑(taᵢ−bᵢ)²≥0 với mọi t; biệt thức của tam thức theo t không dương, xét riêng dãy a=0.','Kiểm tra bất đẳng thức Cauchy–Schwarz với hai bộ số a = (1, 2) và b = (3, 4).','• Tính vế trái (bình phương tổng tích): (1×3 + 2×4)² = (3 + 8)² = 11² = 121.\n• Tính vế phải (tích hai tổng bình phương): (1² + 2²)(3² + 4²) = (1 + 4)(9 + 16) = 5 × 25 = 125.\n• So sánh: 121 ≤ 125 (đúng theo Cauchy–Schwarz).\n• Dấu bằng không xảy ra vì 1/3 ≠ 2/4.','Bình phương toàn bộ tổng tích, không chỉ từng số hạng.','Cận trên của (a+b)² nếu a²+b²=10?',20,'(a+b)²≤(1²+1²)(a²+b²)=20.',{equality:'Hai vector phụ thuộc tuyến tính, bao gồm trường hợp vector 0.',advanced:'Dạng Olympic: a,b,c>0 và a+b+c=1 ⇒ 1/a+1/b+1/c≥9. Áp dụng Cauchy cho (√a,√b,√c) và (1/√a,1/√b,1/√c).'}),
f('inequalities','Jensen',r`f\left(\sum w_ix_i\right)\le\sum w_if(x_i)`,'f lồi trên khoảng chứa mọi xᵢ; wᵢ≥0; ∑wᵢ=1.','Giá trị hàm tại trung bình không vượt trung bình giá trị hàm lồi.','Trường hợp hai điểm là định nghĩa lồi; quy nạp theo số trọng số dương.','Áp dụng bất đẳng thức Jensen cho hàm lồi f(x) = x² với x₁ = 1, x₂ = 3 và w₁ = w₂ = 1/2.','• Kiểm tra tính lồi: f′′(x) = 2 > 0 nên f(x) = x² là hàm lồi trên ℝ.\n• Vế trái (hàm của trung bình): f((1 + 3) / 2) = f(2) = 2² = 4.\n• Vế phải (trung bình của hàm): (f(1) + f(3)) / 2 = (1² + 3²) / 2 = (1 + 9) / 2 = 10 / 2 = 5.\n• So sánh: 4 ≤ 5 (đúng theo Jensen).','Với hàm lõm, đảo chiều bất đẳng thức.','Với x+y=6, min của x²+y²?',18,'Jensen cho x²: (x²+y²)/2≥3² ⇒ tổng≥18.',{equality:'Nếu f lồi nghiêm ngặt và các trọng số dương, mọi xᵢ bằng nhau. Với f lồi thường, dấu bằng còn có thể trên đoạn tuyến tính.',advanced:'Dạng Olympic: a,b,c>0, a+b+c=3 ⇒ a³+b³+c³≥3. Hàm t³ lồi trên (0,∞); áp dụng Jensen ba trọng số bằng nhau.'}),
f('inequalities','Hölder',r`\sum|a_ib_i|\le\left(\sum|a_i|^p\right)^{1/p}\left(\sum|b_i|^q\right)^{1/q}`,'p,q>1; 1/p+1/q=1; dãy hữu hạn.','Khái quát Cauchy–Schwarz cho hai số mũ liên hợp.','Chuẩn hóa hai dãy có chuẩn 1 rồi cộng Young uv≤uᵖ/p+vᑫ/q. Dãy 0 được xét riêng.','Xét trường hợp đặc biệt p = q = 2 của bất đẳng thức Hölder và mối liên hệ với Cauchy–Schwarz.','• Kiểm tra điều kiện số mũ liên hợp: 1/p + 1/q = 1/2 + 1/2 = 1 (thỏa mãn).\n• Khi p = 2 và q = 2, vế phải trở thành:\n  (∑|aᵢ|²)^(1/2) × (∑|bᵢ|²)^(1/2)\n• Bình phương hai vế cho ta: (∑|aᵢbᵢ|)² ≤ (∑|aᵢ|²)(∑|bᵢ|²).\n• Kết luận: Với p = q = 2, Hölder chính là bất đẳng thức Cauchy–Schwarz cho giá trị tuyệt đối.','p và q không tùy ý độc lập.','Khi p=3, q=3/2. Tính 2q.',3,'1/q=1−1/3=2/3 ⇒ q=3/2 ⇒ 2q=3.',{equality:'Một dãy bằng 0, hoặc tồn tại λ>0 sao cho |aᵢ|ᵖ=λ|bᵢ|ᑫ với mọi i.',advanced:'Dạng Olympic: a,b,c≥0 ⇒ (a+b+c)³≤9(a³+b³+c³). Dùng p=3 và q=3/2 với dãy thứ hai (1,1,1).'}),
f('inequalities','Minkowski',r`\left(\sum|a_i+b_i|^p\right)^{1/p}\le\left(\sum|a_i|^p\right)^{1/p}+\left(\sum|b_i|^p\right)^{1/p}`,'Dãy hữu hạn số thực, p≥1.','Bất đẳng thức tam giác của chuẩn p.','Với p>1, chặn ∑|a+b|ᵖ bằng ∑|a||a+b|ᵖ⁻¹+∑|b||a+b|ᵖ⁻¹ rồi áp dụng Hölder. Với p=1 cộng bất đẳng thức tam giác.','Kiểm tra bất đẳng thức Minkowski (bất đẳng thức tam giác) với hai vector u = (3, 0) và v = (0, 4) khi p = 2.','• Tính tổng hai vector: u + v = (3, 4).\n• Chuẩn của vector tổng (vế trái): ‖u + v‖₂ = √(3² + 4²) = √25 = 5.\n• Tổng các chuẩn từng vector (vế phải): ‖u‖₂ + ‖v‖₂ = √(3² + 0²) + √(0² + 4²) = 3 + 4 = 7.\n• So sánh: 5 ≤ 7 (đúng theo bất đẳng thức tam giác trong hình học).\n• Kết luận: Độ dài cạnh huyền tam giác luôn nhỏ hơn tổng độ dài hai cạnh góc vuông.','Không áp dụng chiều này cho 0<p<1.','Độ dài vector (3,4) bằng bao nhiêu?',5,'√(3²+4²)=5.',{equality:'Với p>1: hai vector cùng hướng (hoặc một vector 0). Với p=1: aᵢbᵢ≥0 với mọi i.',advanced:'Dạng Olympic: √(x²+1)+√(y²+1)≥√((x+y)²+4). Áp dụng Minkowski p=2 cho (x,1) và (y,1).'}),
f('inequalities','Chebyshev',r`\frac1n\sum a_ib_i\ge\left(\frac1n\sum a_i\right)\left(\frac1n\sum b_i\right)`,'Hai dãy số thực cùng được sắp không giảm hoặc cùng không tăng.','Hai dãy cùng chiều tạo trung bình tích lớn hơn tích trung bình.','n∑aᵢbᵢ−(∑aᵢ)(∑bᵢ)=∑ᵢ<ⱼ(aᵢ−aⱼ)(bᵢ−bⱼ)≥0.','Kiểm tra bất đẳng thức Chebyshev với hai dãy tăng: a = (1, 2) và b = (3, 4).','• Hai dãy cùng chiều tăng: a₁ ≤ a₂ (1 ≤ 2) và b₁ ≤ b₂ (3 ≤ 4).\n• Trung bình của các tích: (1×3 + 2×4) / 2 = (3 + 8) / 2 = 11 / 2 = 5.5.\n• Tích của hai trung bình: [(1 + 2) / 2] × [(3 + 4) / 2] = 1.5 × 3.5 = 5.25.\n• So sánh: 5.5 ≥ 5.25 (đúng theo bất đẳng thức Chebyshev).','Hai dãy ngược chiều thì chiều bất đẳng thức đảo lại.','Tính 1×3+2×4.',11,'3+8=11.',{equality:'Mọi tích (aᵢ−aⱼ)(bᵢ−bⱼ)=0; với dãy cùng thứ tự, một trong hai dãy hằng là đủ và cần.',advanced:'Dạng Olympic: a,b,c≥0 ⇒ 3(a³+b³+c³)≥(a+b+c)(a²+b²+c²). Sắp a,b,c tăng thì bình phương cũng tăng, rồi áp dụng Chebyshev.'}),
f('inequalities','Schur bậc ba',r`a^3+b^3+c^3+3abc\ge ab(a+b)+bc(b+c)+ca(c+a)`,'a,b,c≥0.','Liên hệ các biểu thức đối xứng bậc ba.','Giả sử a≥b≥c. Tổng ∑a(a−b)(a−c) bằng (a−b)²(a+b−c)+c(c−a)(c−b)≥0.','Kiểm tra bất đẳng thức Schur bậc ba khi ba biến bằng nhau: a = b = c = 1.','• Tính vế trái: a³ + b³ + c³ + 3abc = 1³ + 1³ + 1³ + 3(1)(1)(1) = 1 + 1 + 1 + 3 = 6.\n• Tính vế phải: ab(a + b) + bc(b + c) + ca(c + a) = 1(2) + 1(2) + 1(2) = 2 + 2 + 2 = 6.\n• So sánh: 6 ≥ 6 (đạt dấu bằng).\n• Kết luận: Khi a = b = c, bất đẳng thức Schur đạt dấu đẳng thức.','Không bỏ điều kiện không âm.','Với a=b=c=2, tính a³+b³+c³+3abc.',48,'3×8+3×8=48.',{equality:'a=b=c, hoặc một số bằng 0 và hai số còn lại bằng nhau.',advanced:'Dạng Olympic: đặt p=a+b+c, q=ab+bc+ca, r=abc. Schur tương đương p³+9r≥4pq; khai triển p³ để kiểm tra.'}),
f('inequalities','Bernoulli',r`(1+x)^n\ge1+nx`,'x≥−1; n nguyên dương.','Chặn một lũy thừa bằng biểu thức tuyến tính.','Quy nạp: nhân giả thiết với 1+x≥0, xuất hiện nx²≥0.','Kiểm tra bất đẳng thức Bernoulli với x = 0.1 và số mũ n = 3.','• Điều kiện: x = 0.1 ≥ −1 (thỏa mãn).\n• Tính vế trái: (1 + x)ⁿ = (1 + 0.1)³ = 1.1³ = 1.331.\n• Tính vế phải: 1 + nx = 1 + 3 × (0.1) = 1 + 0.3 = 1.3.\n• So sánh: 1.331 ≥ 1.3 (đúng theo Bernoulli).\n• Nhận xét: Hiệu số 1.331 − 1.3 = 0.031 chính là phần bậc cao bị bỏ qua khi xấp xỉ tuyến tính.','Không giữ cùng phát biểu cho số mũ bất kỳ.','Cận dưới 1+nx khi n=5 và x=1?',6,'1+5×1=6.',{equality:'n=1 hoặc x=0 (với n≥2 chỉ x=0).',advanced:'Dạng Olympic: n≥2 ⇒ (1+1/n)ⁿ≥2, thực tế >2 vì x≠0. Thế x=1/n vào Bernoulli.'}),
f('inequalities','Nesbitt',r`\frac a{b+c}+\frac b{c+a}+\frac c{a+b}\ge\frac32`,'a,b,c>0.','Một bất đẳng thức phân thức đối xứng cơ bản.','Dạng Engel của Cauchy: ∑a/(s−a)=∑a²/[a(s−a)]≥s²/[2(ab+bc+ca)]≥3/2, vì a²+b²+c²≥ab+bc+ca.','Kiểm tra bất đẳng thức Nesbitt khi a = b = c = 1.','• Thay a = b = c = 1 vào biểu thức vế trái:\n  a/(b + c) + b/(c + a) + c/(a + b) = 1/(1 + 1) + 1/(1 + 1) + 1/(1 + 1)\n  = 1/2 + 1/2 + 1/2 = 3/2.\n• So sánh với vế phải: 3/2 ≥ 3/2 (đạt dấu bằng).\n• Kết luận: Bất đẳng thức Nesbitt đạt giá trị nhỏ nhất bằng 3/2 khi và chỉ khi a = b = c.','Mẫu là tổng hai biến còn lại.','Hai lần cận dưới Nesbitt bằng bao nhiêu?',3,'2×(3/2)=3.',{equality:'a=b=c.',advanced:'Dạng Olympic: x,y,z>0 và x+y+z=1 ⇒ x/(1−x)+y/(1−y)+z/(1−z)≥3/2. Thay 1−x=y+z.'}),
f('sequences','Cấp số cộng: số hạng và tổng',r`u_n=u_1+(n-1)d,\quad S_n=\frac n2[2u_1+(n-1)d]`,'n nguyên ≥1; d là công sai cố định.','Mỗi số hạng tăng thêm d so với số trước.','Cộng truy hồi để có uₙ; ghép số đầu và cuối trong tổng để suy ra 2Sₙ=n(u₁+uₙ).','Cho cấp số cộng có số hạng đầu u₁ = 2 và công sai d = 3. Tính số hạng thứ năm u₅ và tổng của 5 số hạng đầu S₅.','• Bước 1: Tính số hạng u₅ theo công thức tổng quát uₙ = u₁ + (n − 1)d:\n  u₅ = 2 + (5 − 1) × 3 = 2 + 12 = 14.\n• Bước 2: Tính tổng S₅ theo công thức Sₙ = n(u₁ + uₙ) / 2:\n  S₅ = 5 × (2 + 14) / 2 = 5 × 16 / 2 = 40.\n• Kết luận: Số hạng u₅ = 14 và tổng 5 số hạng đầu là S₅ = 40.','uₙ dùng (n−1)d, không phải nd.','Tổng 1+2+…+10?',55,'S₁₀=10(1+10)/2=55.'),
f('sequences','Cấp số nhân: số hạng và tổng',r`u_n=u_1q^{n-1},\quad S_n=u_1\frac{1-q^n}{1-q}`,'n nguyên ≥1; công thức tổng khi q≠1. Với q=1, Sₙ=nu₁.','Mỗi số hạng bằng số trước nhân với q.','Lấy Sₙ−qSₙ, các số hạng giữa triệt tiêu, còn u₁−u₁qⁿ.','Cho cấp số nhân có số hạng đầu u₁ = 3 và công bội q = 2. Tính số hạng u₄ và tổng 4 số hạng đầu S₄.','• Bước 1: Tính số hạng u₄ theo công thức uₙ = u₁ × qⁿ⁻¹:\n  u₄ = 3 × 2⁴⁻¹ = 3 × 2³ = 3 × 8 = 24.\n• Bước 2: Tính tổng 4 số hạng đầu S₄ theo công thức khi q ≠ 1:\n  S₄ = u₁ × (1 − q⁴) / (1 − q) = 3 × (1 − 2⁴) / (1 − 2) = 3 × (−15) / (−1) = 45.\n• Kiểm tra lại: 3 + 6 + 12 + 24 = 45.\n• Kết luận: u₄ = 24 và S₄ = 45.','Không dùng mẫu 1−q khi q=1.','Tổng 1+2+4+8?',15,'S₄=(1−2⁴)/(1−2)=15.'),
f('sequences','Tổng cấp số nhân vô hạn',r`S_\infty=\frac{u_1}{1-q}`,'|q|<1. Nếu u₁=0 thì tổng 0 với mọi q.','Khi |q|<1, các số hạng nhỏ dần và tổng hội tụ.','Cho n→∞ trong tổng hữu hạn; qⁿ→0.','Tính tổng của chuỗi cấp số nhân lùi vô hạn: S = 1 + 1/2 + 1/4 + 1/8 + …','• Xác định số hạng đầu: u₁ = 1.\n• Xác định công bội: q = (1/2) / 1 = 1/2.\n• Kiểm tra điều kiện hội tụ: |q| = 1/2 < 1 (chuỗi hội tụ).\n• Áp dụng công thức tổng vô hạn: S_∞ = u₁ / (1 − q):\n  S_∞ = 1 / (1 − 1/2) = 1 / (1/2) = 2.\n• Kết luận: Tổng cấp số nhân lùi vô hạn bằng 2.','q<1 chưa đủ: q=−2 không hội tụ nếu u₁≠0.','Tổng 3+1.5+0.75+…?',6,'3/(1−0.5)=6.'),
f('logarithms','Định nghĩa logarit',r`\log_a b=c\iff a^c=b`,'a>0, a≠1, b>0.','Logarit trả lời: phải nâng cơ số lên mũ mấy để được b?','Hàm aˣ liên tục và đơn điệu từ ℝ lên (0,∞), nên có hàm ngược.','Tính giá trị của log₂ 8 theo định nghĩa logarit.','• Gọi giá trị cần tìm là c: log₂ 8 = c.\n• Theo định nghĩa logarit: 2ᶜ = 8.\n• Phân tích 8 thành lũy thừa cơ số 2: 8 = 2³.\n• Suy ra: 2ᶜ = 2³ ⇒ c = 3.\n• Kết luận: log₂ 8 = 3 (vì 2³ = 8).','Không lấy log của số không dương trong ℝ.','Tính log₂32.',5,'2⁵=32.'),
f('logarithms','Quy tắc và đổi cơ số',r`\log_a(xy)=\log_ax+\log_ay,\quad\log_ab=\frac{\ln b}{\ln a}`,'a>0,a≠1; x,y,b>0.','Phép nhân biến thành phép cộng, đổi cơ số giúp tính toán.','Đặt x=aᵘ,y=aᵛ thì xy=aᵘ⁺ᵛ; lấy ln(aᶜ)=ln b để đổi cơ số.','Tính giá trị biểu thức log₂ (8 × 4) bằng quy tắc logarit của một tích.','• Áp dụng quy tắc cộng logarit: log_a (xy) = log_a x + log_a y.\n• Tách biểu thức: log₂ (8 × 4) = log₂ 8 + log₂ 4.\n• Tính từng phần: log₂ 8 = 3 và log₂ 4 = 2.\n• Cộng hai kết quả: 3 + 2 = 5 (tương đương log₂ 32 = 5).\n• Kết luận: log₂ (8 × 4) = 5.','log(x+y) không bằng log x+log y.','Tính log₂8 + log₂4.',5,'3+2=5.'),
f('logarithms','Log thập phân và log tự nhiên',r`\lg x=\log_{10}x,\quad\ln x=\log_e x`,'x>0; e≈2.71828.','lg dùng cơ số 10; ln dùng cơ số e.','Đây là hai trường hợp đặc biệt của định nghĩa logarit.','Tính giá trị của logarit thập phân lg 1000 và logarit tự nhiên ln(e²).','• Với lg 1000: lg là logarit cơ số 10. Ta có 1000 = 10³ ⇒ lg 1000 = log₁₀(10³) = 3.\n• Với ln(e²): ln là logarit tự nhiên cơ số e. Ta có ln(e²) = log_e(e²) = 2.\n• Kết luận: lg 1000 = 3 và ln(e²) = 2.','Phím log và ln trên máy tính khác cơ số.','Tính lg10000.',4,'10⁴=10000.'),
f('complex','Số phức dạng đại số',r`z=a+bi,\quad i^2=-1`,'a,b∈ℝ.','a là phần thực, b là phần ảo; biểu diễn bằng điểm (a,b).','Phép nhân tuân quy tắc phân phối và thay i² bằng −1.','Thực hiện phép cộng hai số phức z₁ = 1 + 2i và z₂ = 3 − i.','• Quy tắc cộng: Cộng phần thực với phần thực, phần ảo với phần ảo:\n  z₁ + z₂ = (1 + 3) + (2 − 1)i\n• Thực hiện tính toán: = 4 + 1i = 4 + i.\n• Kết luận: Tổng của hai số phức là 4 + i (phần thực là 4, phần ảo là 1).','Phần ảo của 3+2i là 2, không phải 2i.','Phần thực của (1+2i)+(3−i)?',4,'1+3=4.'),
f('complex','Mô đun và liên hợp',r`|z|=\sqrt{a^2+b^2},\quad\overline z=a-bi,\quad z\overline z=|z|^2`,'z=a+bi; mô đun luôn không âm.','Mô đun là khoảng cách đến gốc; liên hợp đối xứng qua trục thực.','(a+bi)(a−bi)=a²+b²; dùng Pythagoras cho khoảng cách.','Cho số phức z = 3 + 4i. Tìm số phức liên hợp z̄ và tính mô đun |z|.','• Tìm số phức liên hợp: Đổi dấu phần ảo trước i: z̄ = 3 − 4i.\n• Tính mô đun |z| theo công thức: |z| = √(a² + b²)\n  |z| = √(3² + 4²) = √(9 + 16) = √25 = 5.\n• Kiểm tra hệ thức: z × z̄ = (3 + 4i)(3 − 4i) = 3² + 4² = 25 = |z|².\n• Kết luận: z̄ = 3 − 4i và |z| = 5.','|a+bi| không bằng |a|+|b|.','Tính |6+8i|.',10,'√(36+64)=10.'),
f('complex','Argument và dạng lượng giác',r`z=r(\cos\theta+i\sin\theta),\quad r=|z|`,'z≠0; θ=arg z xác định sai khác 2kπ.','θ là góc định hướng từ trục thực dương đến vector z.','a=r cosθ và b=r sinθ theo tọa độ cực.','Tìm mô đun r và argument chính θ của số phức z = 1 + i, từ đó viết dạng lượng giác.','• Bước 1: Tính mô đun r = |z| = √(1² + 1²) = √2.\n• Bước 2: Tìm argument θ từ hệ tọa độ cực:\n  cos θ = a / r = 1 / √2\n  sin θ = b / r = 1 / √2\n  Vì điểm (1, 1) nằm ở góc phần tư thứ I nên θ = π/4 (hoặc 45°).\n• Bước 3: Viết dạng lượng giác: z = √2 (cos(π/4) + i sin(π/4)).','Không dùng arctan(b/a) mà bỏ góc phần tư; z=0 không có argument.','Argument chính của i, tính bằng độ?',90,'i nằm trên trục ảo dương, góc 90°.'),
f('complex','De Moivre',r`[r(\cos\theta+i\sin\theta)]^n=r^n(\cos n\theta+i\sin n\theta)`,'n∈ℤ; khi n<0 cần r>0.','Nhân số phức tương ứng nhân mô đun và cộng góc.','Nhân hai dạng lượng giác bằng công thức cộng góc, rồi quy nạp.','Tính lũy thừa bậc ba của số phức dạng lượng giác: (cos 30° + i sin 30°)³.','• Áp dụng công thức De Moivre: [cos θ + i sin θ]ⁿ = cos(nθ) + i sin(nθ).\n• Với θ = 30° và n = 3:\n  (cos 30° + i sin 30°)³ = cos(3 × 30°) + i sin(3 × 30°) = cos 90° + i sin 90°.\n• Thay giá trị lượng giác: cos 90° = 0 và sin 90° = 1:\n  = 0 + 1i = i.\n• Kết luận: Kết quả của phép nâng lũy thừa là i.','Không nhân mô đun với n; phải nâng lên rⁿ.','Phần thực của (1+i)²?',0,'(1+i)²=1+2i−1=2i.'),
f('complex','Công thức Euler',r`e^{i\theta}=\cos\theta+i\sin\theta`,'θ∈ℝ, dùng radian trong giải tích.','Hàm mũ phức mô tả điểm chuyển động trên đường tròn đơn vị.','Tách chuỗi Taylor eⁱᶿ thành phần chẵn và lẻ, nhận được chuỗi cosθ và i sinθ.','Tính giá trị của e^(iπ) bằng công thức Euler.','• Áp dụng công thức Euler với góc θ = π (rad):\n  e^(iπ) = cos π + i sin π.\n• Thay giá trị lượng giác: cos π = −1 và sin π = 0:\n  e^(iπ) = −1 + 0i = −1.\n• Chuyển vế sang trái ta được đồng nhất thức nổi tiếng: e^(iπ) + 1 = 0.\n• Kết luận: e^(iπ) = −1.','Phân biệt độ và radian.','Phần thực của e^(iπ)?',-1,'cosπ=−1.'),
f('calculus','Giới hạn cơ bản',r`\lim_{x\to0}\frac{\sin x}{x}=1`,'x tính bằng radian; x≠0 trong biểu thức.','Giới hạn mô tả giá trị tiến gần, không nhất thiết là giá trị tại điểm.','Với 0<x<π/2: cos x≤sin x/x≤1; dùng định lý kẹp và tính chẵn của thương.','Tính giới hạn cơ bản: lim(x→0) [sin(3x) / x].','• Nhận dạng: Khi x → 0, biểu thức có dạng vô định 0/0.\n• Biến đổi mẫu số để khớp với góc 3x: nhân cả tử và mẫu với 3:\n  sin(3x) / x = 3 × [sin(3x) / (3x)].\n• Khi x → 0 thì u = 3x → 0. Theo giới hạn cơ bản lim(u→0) [sin u / u] = 1:\n  lim(x→0) 3 × [sin(3x) / (3x)] = 3 × 1 = 3.\n• Kết luận: Giới hạn cần tính bằng 3.','Không thay x=0 rồi kết luận 0/0 là 0.','Giá trị limₓ→₀ sin(2x)/x?',2,'2 × lim sin(2x)/(2x)=2.'),
f('calculus','Định nghĩa và quy tắc đạo hàm',r`f'(x)=\lim_{h\to0}\frac{f(x+h)-f(x)}h,\quad(x^n)'=nx^{n-1}`,'Giới hạn hữu hạn phải tồn tại. Quy tắc lũy thừa ở đây n nguyên ≥1.','Đạo hàm là tốc độ thay đổi tức thời và hệ số góc tiếp tuyến.','Khai triển (x+h)ⁿ; sau khi chia h, mọi số hạng còn h tiến về 0.','Tính đạo hàm của hàm số f(x) = x³ và tính giá trị đạo hàm tại x = 2.','• Áp dụng quy tắc đạo hàm của hàm lũy thừa (xⁿ)′ = n × xⁿ⁻¹:\n  f′(x) = (x³)′ = 3 × x³⁻¹ = 3x².\n• Tính giá trị đạo hàm tại điểm x = 2:\n  f′(2) = 3 × (2)² = 3 × 4 = 12.\n• Kết luận: Đạo hàm là f′(x) = 3x² và tốc độ thay đổi tại x = 2 là 12.','Đạo hàm hằng số bằng 0.','Đạo hàm x² tại x=3?',6,'f′(x)=2x ⇒ f′(3)=6.'),
f('calculus','Đạo hàm tích, thương, hàm hợp',r`(uv)'=u'v+uv',\quad (f\circ g)'=(f'\circ g)g'`,'Các hàm khả vi tại điểm xét. Với thương cần v≠0: (u/v)′=(u′v−uv′)/v².','Tách cấu trúc biểu thức để chọn quy tắc phù hợp.','Quy tắc tích từ định nghĩa: thêm bớt u(x+h)v(x), chia h và lấy giới hạn.','Tính đạo hàm của hàm số hợp y = sin(x²).','• Bước 1: Nhận dạng cấu trúc hàm hợp y = f(u) với u = g(x) = x² và f(u) = sin u.\n• Bước 2: Tính đạo hàm của từng thành phần:\n  (sin u)′ = cos u\n  u′ = (x²)′ = 2x.\n• Bước 3: Áp dụng quy tắc chuỗi y′ = f′(u) × u′:\n  y′ = cos(x²) × 2x = 2x cos(x²).\n• Kết luận: Đạo hàm của sin(x²) là 2x cos(x²).','Không bỏ đạo hàm bên trong ở hàm hợp.','Đạo hàm (2x+1)² tại x=0?',4,'2(2x+1)×2; tại 0 là 4.'),
f('calculus','Nguyên hàm',r`\int x^n\,dx=\frac{x^{n+1}}{n+1}+C`,'n≠−1; với n thực, xét x>0. Riêng ∫1/x dx=ln|x|+C trên khoảng không chứa 0.','Nguyên hàm F của f thỏa F′=f; các nguyên hàm sai khác hằng số trên một khoảng.','Lấy đạo hàm xⁿ⁺¹/(n+1)+C thu được xⁿ.','Tìm nguyên hàm của hàm số f(x) = 2x.','• Áp dụng công thức nguyên hàm cơ bản: ∫ xⁿ dx = (xⁿ⁺¹) / (n + 1) + C:\n  ∫ 2x dx = 2 × ∫ x dx = 2 × (x² / 2) + C = x² + C.\n• Kiểm tra lại bằng đạo hàm: (x² + C)′ = 2x + 0 = 2x (chính xác bằng f(x)).\n• Kết luận: Họ các nguyên hàm của 2x là F(x) = x² + C (với C là hằng số tùy ý).','Phải thêm hằng số C cho tích phân bất định.','Với F(x)=x² và F′=2x, tính F(3).',9,'F(3)=3²=9.'),
f('calculus','Tích phân xác định',r`\int_a^b f(x)\,dx=F(b)-F(a)`,'f liên tục trên [a,b] và F′=f.','Tích phân là diện tích có dấu, liên hệ với nguyên hàm bởi định lý cơ bản.','Hàm G(x)=∫ₐˣf(t)dt có G′=f, nên F−G hằng; thế hai đầu mút.','Tính tích phân xác định: I = ∫₀² x dx.','• Bước 1: Tìm một nguyên hàm của hàm dưới dấu tích phân f(x) = x:\n  F(x) = x² / 2.\n• Bước 2: Áp dụng định lý cơ bản của giải tích (công thức Newton–Leibniz):\n  I = [x² / 2]₀² = F(2) − F(0)\n• Bước 3: Thay hai cận:\n  I = (2² / 2) − (0² / 2) = (4 / 2) − 0 = 2.\n• Kết luận: Giá trị của tích phân là 2.','Diện tích hình học cần tách dấu hoặc tích phân |f|.','Tính ∫₀² 3x² dx.',8,'[x³]₀²=8.'),
];
for(const formula of formulas) formula.unicodeMath=unicodeFormulas[formula.id];
formulas.push(...trigonometryFormulas, ...matrixFormulas, ...modernMathFormulas, ...geometryFormulas);
export const normalize=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').toLowerCase();
export function findFormulas(q:string,topic='all'){const tokens=normalize(q).replace(/công thức|cong thuc/g,'').split(/\s+/).filter(Boolean);return formulas.filter(f=>(topic==='all'||f.topic===topic)&&tokens.every(t=>normalize(f.name+' '+f.theory+' '+f.latex+' '+topics.find(x=>x.id===f.topic)?.name).includes(t)))}
