import type {Formula,Topic} from './content';
import {geometryLatex} from './geometry-latex';

export const geometryTopics:Topic[] = [
  {id:'geometry-middle',name:'Hình học THCS',description:'Công thức tính chi tiết từng hình: tam giác, tứ giác, đường tròn và hình khối',symbol:'a² + b² = c²',color:'blue',level:'THCS'},
  {id:'geometry-high',name:'Hình học THPT',description:'Lượng giác, tọa độ, vector và hình học không gian',symbol:'u · v = |u||v| cos θ',color:'purple',level:'THPT'},
  {id:'geometry-university',name:'Hình học đại học',description:'Hình học giải tích, phép biến đổi và nhập môn đường cong, mặt',symbol:'κ = |r′ × r″| / |r′|³',color:'green',level:'Đại học cơ bản'},
];

function g(
  id: string,
  level: 'middle' | 'high' | 'university',
  name: string,
  unicodeMath: string,
  condition: string,
  theory: string,
  proof: string,
  example: string,
  exampleSolution: string,
  mistake: string,
  question: string,
  answer: number,
  solution: string,
  diagram?: Formula['diagram']
): Formula {
  return {
    id: 'geo-' + id,
    topic: 'geometry-' + level,
    name,
    unicodeMath,
    latex: geometryLatex[id] || '',
    condition,
    theory,
    proof,
    example,
    exampleSolution,
    mistake,
    question,
    answer,
    solution,
    diagram,
    tip: 'Vẽ hình, xác định rõ các đại lượng đã cho và đơn vị trước khi ráp vào công thức.',
  };
}

export const geometryFormulas: Formula[] = [
  // ==================== THCS: TAM GIÁC & HỆ THỨC ====================
  g(
    'angles',
    'middle',
    'Góc và tổng ba góc trong tam giác',
    'A + B + C = 180°',
    'A, B, C là ba góc trong một tam giác phẳng.',
    'Tổng số đo ba góc trong một tam giác luôn luôn bằng 180°. Góc ngoài tại một đỉnh bằng tổng hai góc trong không kề với nó.',
    'Qua đỉnh A kẻ đường thẳng d song song với cạnh BC. Dùng tính chất hai góc so le trong và góc bẹt để suy ra A + B + C = 180°.',
    'Cho tam giác ABC có góc A = 50° và góc B = 65°. Tính số đo góc C.',
    '• Áp dụng định lý tổng ba góc trong tam giác: A + B + C = 180°.\n• Suy ra: C = 180° − (A + B) = 180° − (50° + 65°).\n• Tính toán: C = 180° − 115° = 65°.\n• Nhận xét: Tam giác ABC có góc B = góc C = 65° nên đây là tam giác cân tại A.\n• Kết luận: Góc C có số đo bằng 65°.',
    'Không cộng thêm góc ngoài vào tổng ba góc trong tam giác.',
    'Tam giác có hai góc 40° và 65°. Góc còn lại bằng bao nhiêu độ?',
    75,
    'Góc còn lại = 180° − 40° − 65° = 75°.'
  ),

  g(
    'pythagoras',
    'middle',
    'Định lý Pythagoras (Pytago)',
    'a² + b² = c²  ⇔  c = √(a² + b²)',
    'Áp dụng cho tam giác vuông; a, b là độ dài 2 cạnh góc vuông, c là độ dài cạnh huyền.',
    'Trong tam giác vuông, bình phương cạnh huyền bằng tổng bình phương hai cạnh góc vuông. Định lý đảo: nếu ba cạnh thỏa a² + b² = c² thì tam giác vuông tại đỉnh đối diện c.',
    'Ghép 4 tam giác vuông bằng nhau quanh một hình vuông cạnh c tạo thành hình vuông lớn cạnh (a+b). Ta có: (a+b)² = 4(ab/2) + c² ⇒ a² + 2ab + b² = 2ab + c² ⇒ a² + b² = c².',
    'Cho tam giác ABC vuông tại A có hai cạnh góc vuông AB = 3 cm và AC = 4 cm. Tính độ dài cạnh huyền BC.',
    '• Áp dụng định lý Pythagoras trong tam giác ABC vuông tại A:\n  BC² = AB² + AC²\n• Thay số: BC² = 3² + 4² = 9 + 16 = 25.\n• Vì độ dài cạnh BC > 0 nên:\n  BC = √25 = 5 cm.\n• Kết luận: Cạnh huyền BC có độ dài là 5 cm.',
    'Nhầm lẫn giữa cạnh huyền và cạnh góc vuông. Cạnh huyền luôn là cạnh đối diện góc 90° và dài nhất.',
    'Tam giác vuông có hai cạnh góc vuông là 6 và 8. Tính cạnh huyền.',
    10,
    'c = √(6² + 8²) = √(36 + 64) = √100 = 10.',
    'right-triangle'
  ),

  g(
    'triangle-area',
    'middle',
    'Diện tích tam giác thường',
    'S = (a · h) / 2',
    'a là độ dài một cạnh đáy; h là chiều cao hạ vuông góc từ đỉnh đối diện xuống đáy (hoặc đường thẳng chứa đáy).',
    'Diện tích tam giác bằng nửa tích của độ dài đáy với chiều cao tương ứng.',
    'Ghép hai tam giác bằng nhau lại ta được một hình bình hành có đáy a và chiều cao h, có diện tích là a · h. Do đó mỗi tam giác có diện tích là ah/2.',
    'Cho tam giác ABC có độ dài cạnh đáy BC = 8 cm và chiều cao AH hạ từ đỉnh A xuống BC là 5 cm. Tính diện tích tam giác ABC.',
    '• Áp dụng công thức diện tích tam giác: S = (a × h) / 2\n• Với đáy a = BC = 8 cm, chiều cao h = AH = 5 cm:\n  S = (8 × 5) / 2 = 40 / 2 = 20 cm².\n• Kết luận: Diện tích tam giác ABC bằng 20 cm².',
    'Lấy nhầm cạnh bên thay cho chiều cao vuông góc.',
    'Tam giác có đáy 12 cm và chiều cao 7 cm. Tính diện tích tam giác.',
    42,
    'S = (12 × 7) / 2 = 84 / 2 = 42 cm²',
    'triangle-height'
  ),

  g(
    'triangle-right-area',
    'middle',
    'Diện tích tam giác vuông',
    'S = (a · b) / 2',
    'a và b là độ dài của hai cạnh góc vuông.',
    'Trong tam giác vuông, mỗi cạnh góc vuông chính là đường cao tương ứng với cạnh góc vuông còn lại. Do đó diện tích bằng nửa tích hai cạnh góc vuông.',
    'Tam giác vuông chính là một nửa hình chữ nhật có hai kích thước a và b.',
    'Cho tam giác vuông có hai cạnh góc vuông lần lượt là a = 6 cm và b = 8 cm. Tính diện tích tam giác vuông.',
    '• Áp dụng công thức tính diện tích tam giác vuông: S = (a × b) / 2\n• Thay a = 6 cm và b = 8 cm:\n  S = (6 × 8) / 2 = 48 / 2 = 24 cm².\n• Kết luận: Diện tích tam giác vuông bằng 24 cm².',
    'Không cần tìm cạnh huyền hay kẻ thêm đường cao khi đã biết độ dài 2 cạnh góc vuông.',
    'Tam giác vuông có hai cạnh góc vuông là 5 cm và 12 cm. Diện tích bằng bao nhiêu cm²?',
    30,
    'S = (5 × 12) / 2 = 60 / 2 = 30 cm².',
    'right-triangle'
  ),

  g(
    'triangle-equilateral-area',
    'middle',
    'Chiều cao và diện tích tam giác đều',
    'h = (a√3) / 2,   S = (a²√3) / 4',
    'a là độ dài cạnh của tam giác đều (ba cạnh bằng nhau và ba góc bằng 60°).',
    'Trong tam giác đều cạnh a, đường cao đồng thời là đường trung tuyến. Chiều cao tính nhanh bằng a√3/2 và diện tích là a²√3/4.',
    'Kẻ đường cao h chia tam giác đều thành 2 tam giác vuông có cạnh huyền a và 1 cạnh đáy a/2. Theo Pythagoras: h² = a² − (a/2)² = 3a²/4 ⇒ h = a√3/2. Khi đó S = (1/2)ah = a²√3/4.',
    'Cho một tam giác đều có cạnh a = 6 cm. Tính chiều cao h và diện tích S của tam giác đều này.',
    '• Bước 1: Tính chiều cao h của tam giác đều:\n  h = (a√3) / 2 = (6√3) / 2 = 3√3 cm (xấp xỉ 5.2 cm).\n• Bước 2: Tính diện tích S của tam giác đều:\n  S = (a²√3) / 4 = (6²√3) / 4 = (36√3) / 4 = 9√3 cm² (xấp xỉ 15.59 cm²).\n• Kết luận: Chiều cao h = 3√3 cm và diện tích S = 9√3 cm².',
    'Quên căn 3 hoặc nhầm hệ số mẫu thành 2 thay vì 4 trong công thức diện tích.',
    'Tam giác đều có cạnh a = 4. Tính diện tích của tam giác theo k√3, tìm k.',
    4,
    'S = (4²√3)/4 = 4√3 ⇒ k = 4.',
    'triangle-height'
  ),

  g(
    'right-triangle-relations',
    'middle',
    'Hệ thức lượng trong tam giác vuông (Lớp 9)',
    'h² = b′c′,   b² = ab′,   c² = ac′,   ah = bc',
    'Tam giác vuông với cạnh huyền a, hai cạnh góc vuông b, c; h là đường cao hạ xuống cạnh huyền; b′, c′ là hình chiếu của b, c trên cạnh huyền.',
    'Các cặp tam giác vuông đồng dạng sinh ra 4 hệ thức lượng kinh điển: bình phương đường cao bằng tích hai hình chiếu; bình phương cạnh góc vuông bằng cạnh huyền nhân hình chiếu tương ứng.',
    'Chứng minh bằng các tam giác vuông đồng dạng: ΔABH ∼ ΔCBA và ΔCAH ∼ ΔCBA và ΔABH ∼ ΔCAH.',
    'Cho tam giác ABC vuông tại A có đường cao AH. Biết hai hình chiếu trên cạnh huyền là b′ = CH = 2 cm và c′ = BH = 8 cm. Tính độ dài đường cao AH và cạnh góc vuông AB.',
    '• Bước 1: Tính độ dài đường cao AH qua hệ thức h² = b′c′:\n  AH² = BH × CH = 8 × 2 = 16 ⇒ AH = √16 = 4 cm.\n• Bước 2: Tính cạnh huyền BC = BH + CH = 8 + 2 = 10 cm.\n• Bước 3: Tính cạnh góc vuông AB qua hệ thức c² = ac′:\n  AB² = BC × BH = 10 × 8 = 80 ⇒ AB = √80 = 4√5 cm.\n• Kết luận: AH = 4 cm và AB = 4√5 cm.',
    'Nhầm lẫn hình chiếu b′ của cạnh b với hình chiếu c′ của cạnh c.',
    'Tam giác vuông có hai hình chiếu trên cạnh huyền là 4 và 9. Độ dài đường cao bằng bao nhiêu?',
    6,
    'h² = 4 × 9 = 36 ⇒ h = 6.',
    'right-triangle'
  ),

  g(
    'right-trig',
    'middle',
    'Tỉ số lượng giác góc nhọn (sin, cos, tan, cot)',
    'sin α = Đối/Huyền,  cos α = Kề/Huyền,  tan α = Đối/Kề,  cot α = Kề/Đối',
    'Áp dụng cho góc nhọn α (0° < α < 90°) trong tam giác vuông.',
    'Câu khẩu quyết ghi nhớ: "Sao Đi Học (sin = Đ/H), Cứ Khóc Hoài (cos = K/H), Thôi Đừng Khóc (tan = Đ/K), Có Kẹo Đây (cot = K/Đ)".',
    'Dựa vào tính chất hai tam giác vuông có cùng góc nhọn thì đồng dạng với nhau, tỉ số giữa các cạnh tương ứng không đổi.',
    'Cho tam giác ABC vuông tại A có AB = 3 cm, AC = 4 cm, BC = 5 cm. Tính sin, cos, tan của góc B.',
    '• Xét góc nhọn B: Cạnh đối là AC = 4 cm, cạnh kề là AB = 3 cm, cạnh huyền là BC = 5 cm.\n• sin B = Đối / Huyền = AC / BC = 4 / 5 = 0.8.\n• cos B = Kề / Huyền = AB / BC = 3 / 5 = 0.6.\n• tan B = Đối / Kề = AC / AB = 4 / 3 ≈ 1.33.\n• cot B = Kề / Đối = AB / AC = 3 / 4 = 0.75.\n• Kết luận: sin B = 4/5, cos B = 3/5, tan B = 4/3.',
    'Nhầm cạnh kề với cạnh huyền. Cạnh huyền là cạnh lớn nhất đối diện góc vuông.',
    'Cạnh đối bằng 6, cạnh huyền bằng 10. Giá trị sin α bằng bao nhiêu?',
    0.6,
    'sin α = 6/10 = 0.6.'
  ),

  g(
    'similarity',
    'middle',
    'Tam giác đồng dạng và tỉ số diện tích',
    'a′/a = b′/b = c′/c = k  ⇒  S′/S = k²',
    'Hai tam giác đồng dạng theo tỉ số k (k > 0).',
    'Nếu hai tam giác đồng dạng với tỉ số cạnh là k thì tỉ số chu vi bằng k, còn tỉ số diện tích bằng bình phương tỉ số đồng dạng (k²).',
    'Đáy nhân k và chiều cao cũng nhân k, do đó diện tích S′ = (ka)(kh)/2 = k²(ah/2) = k²S.',
    'Hai tam giác ABC và A′B′C′ đồng dạng với tỉ số k = 3. Biết diện tích tam giác ABC là S = 10 cm². Tính diện tích tam giác A′B′C′.',
    '• Áp dụng định lý tỉ số diện tích của hai tam giác đồng dạng: S′ / S = k²\n• Thay k = 3 và S = 10 cm²:\n  S′ / 10 = 3² = 9\n• Suy ra: S′ = 10 × 9 = 90 cm².\n• Kết luận: Diện tích tam giác phóng to A′B′C′ bằng 90 cm² (gấp 9 lần tam giác ban đầu).',
    'Sai lầm phổ biến: Cho rằng diện tích cũng gấp k lần (nghĩ là gấp 3 lần thay vì 9 lần).',
    'Một tam giác được phóng to với tỉ số cạnh k = 4. Diện tích tăng gấp bao nhiêu lần?',
    16,
    'Tỉ số diện tích = k² = 4² = 16 lần.'
  ),

  g(
    'thales',
    'middle',
    'Định lý Thales và hệ quả (Talet)',
    'AD/AB = AE/AC = DE/BC   (khi DE ∥ BC)',
    'Đoạn thẳng DE cắt hai cạnh AB, AC của tam giác ABC và song song với cạnh thứ ba BC.',
    'Một đường thẳng song song với một cạnh của tam giác và cắt hai cạnh còn lại thì định ra trên hai cạnh đó những đoạn thẳng tương ứng tỉ lệ.',
    'Dựng đường cao và so sánh tỉ số diện tích các tam giác có chung đáy hoặc chung chiều cao.',
    'Cho tam giác ABC có AB = 9 cm, AC = 12 cm. Trên AB lấy điểm D sao cho AD = 3 cm. Kẻ đường thẳng qua D song song với BC, cắt AC tại E. Biết BC = 15 cm, tính độ dài đoạn thẳng DE và AE.',
    '• Vì DE ∥ BC nên theo hệ quả định lý Thales ta có:\n  AD / AB = AE / AC = DE / BC\n• Tỉ số: AD / AB = 3 / 9 = 1/3.\n• Tính DE: DE / 15 = 1/3 ⇒ DE = 15 × (1/3) = 5 cm.\n• Tính AE: AE / 12 = 1/3 ⇒ AE = 12 × (1/3) = 4 cm.\n• Kết luận: DE = 5 cm và AE = 4 cm.',
    'Áp dụng Thales khi chưa có giả thiết hai đường thẳng song song.',
    'Cho DE ∥ BC, AD/AB = 2/5 và BC = 20 cm. Độ dài DE bằng bao nhiêu cm?',
    8,
    'DE = 20 × (2/5) = 8 cm.'
  ),

  // ==================== THCS: TỨ GIÁC PHẲNG (TÁCH RIÊNG TỪNG HÌNH) ====================
  g(
    'square',
    'middle',
    'Chu vi và diện tích hình vuông',
    'P = 4a,   S = a²',
    'a là độ dài cạnh của hình vuông (a > 0).',
    'Hình vuông có 4 cạnh bằng nhau và 4 góc vuông. Chu vi bằng 4 lần độ dài cạnh, diện tích bằng bình phương độ dài cạnh.',
    'Chia hình vuông thành lưới các ô vuông đơn vị: có a hàng, mỗi hàng a ô, tổng số ô là a × a = a².',
    'Cho hình vuông ABCD có độ dài cạnh a = 5 cm. Tính chu vi P và diện tích S của hình vuông.',
    '• Bước 1: Tính chu vi hình vuông:\n  P = 4 × a = 4 × 5 = 20 cm.\n• Bước 2: Tính diện tích hình vuông:\n  S = a² = 5² = 25 cm².\n• Kết luận: Chu vi hình vuông là 20 cm và diện tích là 25 cm².',
    'Nhầm lẫn giữa chu vi (đơn vị cm) và diện tích (đơn vị cm²), hoặc nhầm a² với 2a.',
    'Một mảnh đất hình vuông có cạnh 7 m. Tính diện tích mảnh đất (m²).',
    49,
    'S = 7² = 49 m².'
  ),

  g(
    'rectangle',
    'middle',
    'Chu vi và diện tích hình chữ nhật',
    'P = 2(a + b),   S = a · b',
    'a là chiều dài, b là chiều rộng (cùng đơn vị đo, a > 0, b > 0).',
    'Hình chữ nhật có các góc vuông và hai cặp cạnh đối song song, bằng nhau. Chu vi bằng 2 lần tổng chiều dài và chiều rộng, diện tích bằng tích chiều dài nhân chiều rộng.',
    'Lưới ô vuông gồm a cột và b hàng, tổng diện tích phủ kín bằng a × b ô vuông đơn vị.',
    'Một căn phòng hình chữ nhật có chiều dài a = 8 m và chiều rộng b = 5 m. Tính chu vi và diện tích căn phòng.',
    '• Bước 1: Tính chu vi hình chữ nhật:\n  P = 2 × (a + b) = 2 × (8 + 5) = 2 × 13 = 26 m.\n• Bước 2: Tính diện tích hình chữ nhật:\n  S = a × b = 8 × 5 = 40 m².\n• Kết luận: Chu vi căn phòng là 26 m và diện tích là 40 m².',
    'Quên nhân đôi khi tính chu vi (chỉ lấy a + b), hoặc hai kích thước chưa cùng đơn vị đo (ví dụ mét và xăng-ti-mét).',
    'Hình chữ nhật có chiều dài 12 cm và chiều rộng 6 cm. Tính diện tích (cm²).',
    72,
    'S = 12 × 6 = 72 cm².'
  ),

  g(
    'parallelogram',
    'middle',
    'Chu vi và diện tích hình bình hành',
    'P = 2(a + b),   S = a · h',
    'a là cạnh đáy, b là cạnh bên; h là chiều cao hạ vuông góc xuống cạnh đáy a.',
    'Hình bình hành có các cạnh đối song song và bằng nhau. Chu vi bằng 2(a+b). Diện tích bằng độ dài đáy nhân với chiều cao tương ứng.',
    'Cắt tam giác vuông ở một đầu hình bình hành và ghép vào đầu đối diện, ta nhận được một hình chữ nhật có cùng đáy a và chiều cao h, do đó S = a · h.',
    'Cho hình bình hành ABCD có độ dài cạnh đáy a = 10 cm, cạnh bên b = 6 cm và chiều cao hạ xuống đáy là h = 4 cm. Tính chu vi và diện tích hình bình hành.',
    '• Bước 1: Tính chu vi hình bình hành:\n  P = 2 × (a + b) = 2 × (10 + 6) = 2 × 16 = 32 cm.\n• Bước 2: Tính diện tích hình bình hành:\n  S = a × h = 10 × 4 = 40 cm².\n• Kết luận: Chu vi hình bình hành là 32 cm và diện tích là 40 cm².',
    'Lấy cạnh bên nhân với đáy (a × b) thay vì lấy đáy nhân chiều cao vuông góc (a × h).',
    'Hình bình hành có đáy 15 cm và chiều cao tương ứng 6 cm. Diện tích bằng bao nhiêu cm²?',
    90,
    'S = 15 × 6 = 90 cm².'
  ),

  g(
    'rhombus',
    'middle',
    'Chu vi và diện tích hình thoi',
    'P = 4a,   S = (d₁ · d₂) / 2',
    'a là độ dài cạnh của hình thoi; d₁ và d₂ là độ dài của hai đường chéo vuông góc với nhau.',
    'Hình thoi có bốn cạnh bằng nhau và hai đường chéo vuông góc tại trung điểm mỗi đường. Chu vi bằng 4a, diện tích bằng nửa tích hai đường chéo.',
    'Hai đường chéo chia hình thoi thành 4 tam giác vuông bằng nhau có các cạnh góc vuông d₁/2 và d₂/2. Diện tích S = 4 × [(d₁/2)(d₂/2)/2] = (d₁d₂)/2.',
    'Cho hình thoi ABCD có cạnh a = 5 cm và độ dài hai đường chéo lần lượt là d₁ = 8 cm, d₂ = 6 cm. Tính chu vi và diện tích hình thoi.',
    '• Bước 1: Tính chu vi hình thoi:\n  P = 4 × a = 4 × 5 = 20 cm.\n• Bước 2: Tính diện tích hình thoi:\n  S = (d₁ × d₂) / 2 = (8 × 6) / 2 = 48 / 2 = 24 cm².\n• Kết luận: Chu vi hình thoi là 20 cm và diện tích là 24 cm².',
    'Quên chia cho 2 khi nhân hai đường chéo, hoặc nhầm lẫn giữa độ dài cạnh và độ dài đường chéo.',
    'Hình thoi có hai đường chéo dài 10 cm và 14 cm. Diện tích hình thoi bằng bao nhiêu cm²?',
    70,
    'S = (10 × 14) / 2 = 70 cm².'
  ),

  g(
    'trapezoid',
    'middle',
    'Diện tích hình thang',
    'S = ((a + b) · h) / 2',
    'a, b là độ dài hai đáy (đáy bé và đáy lớn song song với nhau); h là chiều cao (khoảng cách vuông góc giữa hai đáy).',
    'Câu vè quen thuộc: "Muốn tính diện tích hình thang, Đáy lớn đáy nhỏ ta mang cộng vào, Thế rồi nhân với chiều cao, Chia đôi lấy nửa thế nào cũng ra".',
    'Ghép hai hình thang bằng nhau ngược chiều lại, ta được một hình bình hành có đáy là (a+b) và chiều cao h. Diện tích hình bình hành là (a+b)h, nên diện tích mỗi hình thang là ((a+b)h)/2.',
    'Cho hình thang ABCD có đáy bé a = 6 cm, đáy lớn b = 10 cm và chiều cao h = 4 cm. Tính diện tích hình thang.',
    '• Áp dụng công thức tính diện tích hình thang: S = ((a + b) × h) / 2\n• Thay số:\n  S = ((6 + 10) × 4) / 2\n  S = (16 × 4) / 2 = 64 / 2 = 32 cm².\n• Kết luận: Diện tích hình thang bằng 32 cm².',
    'Không cộng hai đáy trước mà nhân chiều cao với một đáy rồi mới cộng; hoặc hai đáy chưa song song.',
    'Hình thang có hai đáy là 8 cm và 14 cm, chiều cao 5 cm. Tính diện tích (cm²).',
    55,
    'S = ((8 + 14) × 5) / 2 = (22 × 5) / 2 = 55 cm².'
  ),

  // ==================== THCS: ĐƯỜNG TRÒN & HÌNH TRÒN ====================
  g(
    'circle-perimeter',
    'middle',
    'Chu vi đường tròn',
    'C = 2πr = πd',
    'r là bán kính, d là đường kính đường tròn (d = 2r, r > 0). Hằng số π ≈ 3.14159.',
    'Chu vi là chiều dài của đường biên bao quanh hình tròn. Độ dài này luôn gấp π lần đường kính d của nó.',
    'Định nghĩa hằng số số học π = Chu vi / Đường kính = C / d ⇒ C = πd = 2πr.',
    'Cho một bánh xe hình tròn có bán kính r = 35 cm. Tính chu vi bánh xe (lấy π ≈ 3.14).',
    '• Áp dụng công thức chu vi đường tròn: C = 2πr\n• Thay số: C = 2 × 3.14 × 35 = 70 × 3.14 = 219.8 cm.\n• Nếu để dạng số chính xác theo π: C = 70π cm.\n• Kết luận: Chu vi của bánh xe xấp xỉ 219.8 cm.',
    'Dùng nhầm đường kính d vào vị trí của r trong công thức 2πr (thành 2πd sẽ bị gấp đôi kết quả).',
    'Đường kính đường tròn d = 10 cm. Tính chu vi theo kπ, tìm k.',
    10,
    'C = πd = 10π ⇒ k = 10.',
    'circle'
  ),

  g(
    'circle-area',
    'middle',
    'Diện tích hình tròn',
    'S = πr²',
    'r là bán kính của hình tròn (r > 0).',
    'Diện tích hình tròn tỉ lệ thuận với bình phương bán kính. Khi bán kính tăng gấp đôi thì diện tích tăng gấp 4 lần.',
    'Chia hình tròn thành hàng nghìn quạt nhỏ rồi ghép xen kẽ tạo thành một hình gần chữ nhật có chiều rộng là r và chiều dài là πr. Diện tích bằng r × πr = πr².',
    'Cho một hình tròn có bán kính r = 6 cm. Tính diện tích hình tròn (lấy π ≈ 3.14).',
    '• Áp dụng công thức diện tích hình tròn: S = πr²\n• Thay số: S = π × 6² = 36π cm².\n• Tính giá trị xấp xỉ với π ≈ 3.14:\n  S ≈ 36 × 3.14 = 113.04 cm².\n• Kết luận: Diện tích hình tròn là 36π cm² (xấp xỉ 113.04 cm²).',
    'Nhầm diện tích πr² với 2πr (chu vi) hoặc quên không bình phương bán kính.',
    'Hình tròn có bán kính r = 5 cm. Diện tích bằng kπ cm², tìm k.',
    25,
    'S = π × 5² = 25π ⇒ k = 25.',
    'circle'
  ),

  g(
    'circle-arc-sector',
    'middle',
    'Độ dài cung tròn và diện tích hình quạt tròn',
    'l = (π · r · n) / 180,   S_quat = (π · r² · n) / 360',
    'r là bán kính đường tròn; n là số đo độ của cung tròn (0° < n ≤ 360°).',
    'Cung tròn chiếm tỉ lệ n/360 so với toàn bộ chu vi đường tròn; quạt tròn chiếm tỉ lệ n/360 so với toàn bộ diện tích hình tròn.',
    'Toàn bộ đường tròn là 360°. Do đó cung 1° có độ dài 2πr/360 = πr/180; cung n° có độ dài l = (πrn)/180.',
    'Cho đường tròn bán kính r = 6 cm. Tính độ dài cung tròn l và diện tích hình quạt tròn có số đo cung n = 60°.',
    '• Bước 1: Tính độ dài cung tròn 60°:\n  l = (π × r × n) / 180 = (π × 6 × 60) / 180 = (360π) / 180 = 2π cm (xấp xỉ 6.28 cm).\n• Bước 2: Tính diện tích hình quạt tròn 60°:\n  S_quat = (π × r² × n) / 360 = (π × 6² × 60) / 360 = (2160π) / 360 = 6π cm² (xấp xỉ 18.85 cm²).\n• Kết luận: Độ dài cung tròn là 2π cm và diện tích hình quạt là 6π cm².',
    'Nhầm lẫn giữa mẫu số 180 (cho độ dài cung) và mẫu số 360 (cho diện tích quạt).',
    'Đường tròn bán kính r = 9 cm. Độ dài cung 40° bằng kπ cm, tìm k.',
    2,
    'l = (π × 9 × 40)/180 = 2π ⇒ k = 2.',
    'circle'
  ),

  g(
    'inscribed-angle',
    'middle',
    'Góc nội tiếp và góc ở tâm trong đường tròn',
    '∠APB = (sđ cung AB) / 2',
    'A, B, P thuộc đường tròn; P là đỉnh nằm trên đường tròn (góc nội tiếp chắn cung AB không chứa P).',
    'Trong một đường tròn, số đo của góc nội tiếp bằng nửa số đo của cung bị chắn. Đặc biệt: Góc nội tiếp chắn nửa đường tròn luôn là góc vuông (90°).',
    'Nối tâm O với các đỉnh, các tam giác cân OPA và OPB tạo nên các góc ngoài tại tâm gấp đôi góc nội tiếp.',
    'Cho đường tròn (O), góc nội tiếp ∠APB chắn cung AB có số đo cung là 80°. Tính số đo của góc ∠APB và góc ở tâm ∠AOB.',
    '• Bước 1: Tính góc nội tiếp ∠APB:\n  Theo định lý góc nội tiếp: ∠APB = (số đo cung AB) / 2 = 80° / 2 = 40°.\n• Bước 2: Tính góc ở tâm ∠AOB:\n  Số đo góc ở tâm bằng số đo cung bị chắn: ∠AOB = số đo cung AB = 80°.\n• Nhận xét: Góc ở tâm gấp đôi góc nội tiếp cùng chắn một cung: ∠AOB = 2 × ∠APB.\n• Kết luận: ∠APB = 40° và ∠AOB = 80°.',
    'Không phân biệt giữa góc nội tiếp (đỉnh nằm TRÊN đường tròn) và góc ở tâm (đỉnh tại TÂM đường tròn).',
    'Góc nội tiếp chắn nửa đường tròn bằng bao nhiêu độ?',
    90,
    'Nửa đường tròn có số đo 180°. Góc nội tiếp = 180° / 2 = 90°.'
  ),

  // ==================== THCS: HÌNH KHỐI KHÔNG GIAN (TÁCH RIÊNG TỪNG HÌNH) ====================
  g(
    'solid-cuboid',
    'middle',
    'Thể tích và diện tích hình hộp chữ nhật',
    'V = a · b · c,   S_tp = 2(ab + bc + ca)',
    'a, b, c là ba kích thước: chiều dài, chiều rộng, chiều cao của hình hộp chữ nhật (cùng đơn vị đo).',
    'Hình hộp chữ nhật có 6 mặt đều là hình chữ nhật. Thể tích bằng tích ba kích thước; diện tích toàn phần bằng tổng diện tích của 6 mặt.',
    'Đếm số khối lập phương đơn vị được xếp đầy trong hộp: gồm c lớp, mỗi lớp có a × b khối.',
    'Một bể nước hình hộp chữ nhật có chiều dài a = 3 m, chiều rộng b = 2 m và chiều cao c = 1.5 m. Tính diện tích toàn phần và thể tích chứa nước của bể.',
    '• Bước 1: Tính diện tích toàn phần:\n  S_tp = 2(ab + bc + ca) = 2(3×2 + 2×1.5 + 1.5×3)\n  S_tp = 2(6 + 3 + 4.5) = 2 × 13.5 = 27 m².\n• Bước 2: Tính thể tích bể nước:\n  V = a × b × c = 3 × 2 × 1.5 = 9 m³.\n• Kết luận: Diện tích toàn phần là 27 m² và thể tích bể chứa là 9 m³ (tương đương 9000 lít nước).',
    'Nhầm lẫn giữa diện tích xung quanh (chỉ có 4 mặt bên: 2(a+b)c) và diện tích toàn phần (cộng thêm 2 mặt đáy 2ab).',
    'Hình hộp chữ nhật có kích thước 2 cm, 3 cm, 5 cm. Thể tích bằng bao nhiêu cm³?',
    30,
    'V = 2 × 3 × 5 = 30 cm³.',
    'solid'
  ),

  g(
    'solid-cube',
    'middle',
    'Thể tích và diện tích hình lập phương',
    'V = a³,   S_tp = 6a²',
    'a là độ dài cạnh của hình lập phương (a > 0).',
    'Hình lập phương là trường hợp đặc biệt của hình hộp chữ nhật khi cả 3 kích thước đều bằng nhau. Có 6 mặt là các hình vuông bằng nhau.',
    'Thay a = b = c vào công thức hình hộp chữ nhật: V = a × a × a = a³ và S_tp = 2(a² + a² + a²) = 6a².',
    'Một khối rubik hình lập phương có độ dài mỗi cạnh a = 5 cm. Tính diện tích toàn phần và thể tích của khối rubik.',
    '• Bước 1: Tính diện tích toàn phần:\n  S_tp = 6 × a² = 6 × 5² = 6 × 25 = 150 cm².\n• Bước 2: Tính thể tích khối lập phương:\n  V = a³ = 5³ = 5 × 5 × 5 = 125 cm³.\n• Kết luận: Diện tích toàn phần là 150 cm² và thể tích là 125 cm³.',
    'Nhầm lẫn a³ với 3a khi tính thể tích, hoặc 6a² với (6a)². ',
    'Khối lập phương có cạnh bằng 4 cm. Thể tích bằng bao nhiêu cm³?',
    64,
    'V = 4³ = 64 cm³.',
    'solid'
  ),

  g(
    'solid-cylinder',
    'middle',
    'Hình trụ: Diện tích xung quanh và thể tích',
    'S_xq = 2πrh,   V = πr²h',
    'r là bán kính đáy, h là chiều cao hình trụ (khoảng cách giữa hai mặt đáy tròn).',
    'Hình trụ được tạo ra khi quay một hình chữ nhật quanh một cạnh. Diện tích xung quanh mở ra thành một hình chữ nhật có kích thước 2πr và h.',
    'Trải mặt xung quanh lên mặt phẳng: chiều dài là chu vi đáy 2πr, chiều rộng là chiều cao h. Diện tích xung quanh = 2πr · h. Thể tích = Diện tích đáy × chiều cao = (πr²)h.',
    'Một lon sữa đặc hình trụ có bán kính đáy r = 3 cm và chiều cao h = 10 cm. Tính diện tích xung quanh và thể tích của lon sữa (theo π).',
    '• Bước 1: Tính diện tích xung quanh hình trụ:\n  S_xq = 2πrh = 2π × 3 × 10 = 60π cm² (xấp xỉ 188.5 cm²).\n• Bước 2: Tính thể tích của lon sữa:\n  V = πr²h = π × 3² × 10 = π × 9 × 10 = 90π cm³ (xấp xỉ 282.7 cm³).\n• Kết luận: Diện tích xung quanh là 60π cm² và thể tích là 90π cm³.',
    'Quên nhân 2 trong diện tích xung quanh (nhầm thành πrh), hoặc quên bình phương r khi tính thể tích.',
    'Hình trụ có bán kính r = 2 cm và cao h = 5 cm. Thể tích bằng kπ cm³, tìm k.',
    20,
    'V = π × 2² × 5 = 20π ⇒ k = 20.',
    'solid'
  ),

  g(
    'solid-cone',
    'middle',
    'Hình nón: Diện tích xung quanh và thể tích',
    'S_xq = πrl,   V = (πr²h) / 3   (với l = √(r² + h²))',
    'r là bán kính đường tròn đáy, h là chiều cao từ đỉnh nón đến tâm đáy, l là độ dài đường sinh từ đỉnh nón đến đường tròn đáy.',
    'Hình nón được tạo ra khi quay một tam giác vuông quanh một cạnh góc vuông. Thể tích hình nón bằng đúng 1/3 thể tích hình trụ có cùng đáy và chiều cao.',
    'Theo định lý Pythagoras trong tam giác vuông tạo bởi chiều cao h, bán kính đáy r và đường sinh l: l² = r² + h². Mặt xung quanh mở ra là một hình quạt tròn bán kính l.',
    'Một chiếc nón lá có bán kính đáy r = 30 cm và chiều cao h = 40 cm. Tính độ dài đường sinh l, diện tích xung quanh và thể tích chiếc nón (lấy π ≈ 3.14).',
    '• Bước 1: Tính độ dài đường sinh l:\n  l = √(r² + h²) = √(30² + 40²) = √(900 + 1600) = √2500 = 50 cm.\n• Bước 2: Tính diện tích xung quanh (phần lá lợp):\n  S_xq = πrl = π × 30 × 50 = 1500π cm² ≈ 4710 cm².\n• Bước 3: Tính thể tích chiếc nón:\n  V = (1/3)πr²h = (1/3)π × 30² × 40 = (1/3)π × 900 × 40 = 12000π cm³ ≈ 37680 cm³.\n• Kết luận: Đường sinh l = 50 cm, S_xq = 1500π cm² và V = 12000π cm³.',
    'Lấy nhầm chiều cao h thay vào công thức diện tích xung quanh (phải dùng đường sinh l: S_xq = πrl). Quên chia 3 khi tính thể tích.',
    'Hình nón có r = 3 cm, h = 4 cm. Đường sinh l bằng bao nhiêu cm?',
    5,
    'l = √(3² + 4²) = √25 = 5 cm.',
    'solid'
  ),

  g(
    'solid-sphere',
    'middle',
    'Hình cầu: Diện tích mặt cầu và thể tích khối cầu',
    'S = 4πr²,   V = (4πr³) / 3',
    'r là bán kính của mặt cầu và khối cầu (r > 0).',
    'Quả cầu là tập hợp tất cả các điểm trong không gian cách tâm O một khoảng không đổi r. Diện tích mặt cầu gấp 4 lần diện tích hình tròn lớn cùng bán kính.',
    'Ac-si-met (Archimedes) đã chứng minh thể tích hình cầu bằng 2/3 thể tích hình trụ ngoại tiếp nó: V = (2/3) × (πr² × 2r) = 4πr³/3.',
    'Một quả bóng đá hình cầu có bán kính r = 3 cm. Tính diện tích mặt ngoài của quả bóng và thể tích không khí bên trong nó (theo π).',
    '• Bước 1: Tính diện tích mặt ngoài (mặt cầu):\n  S = 4πr² = 4π × 3² = 4π × 9 = 36π cm² (xấp xỉ 113.1 cm²).\n• Bước 2: Tính thể tích quả bóng (khối cầu):\n  V = (4/3)πr³ = (4/3)π × 3³ = (4/3)π × 27 = 36π cm³ (xấp xỉ 113.1 cm³).\n• Kết luận: Diện tích mặt cầu là 36π cm² và thể tích khối cầu là 36π cm³.',
    'Nhầm lẫn số mũ: diện tích dùng r² (đơn vị cm²), thể tích dùng r³ (đơn vị cm³). Quên hệ số 4/3.',
    'Khối cầu có bán kính r = 3 cm. Thể tích bằng kπ cm³, tìm k.',
    36,
    'V = (4/3)π(3³) = 36π ⇒ k = 36.',
    'solid'
  ),

  g(
    'solid-prism',
    'middle',
    'Hình lăng trụ đứng',
    'V = S_day · h,   S_xq = 2p · h',
    'S_day là diện tích mặt đáy; 2p là chu vi mặt đáy; h là chiều cao lăng trụ (độ dài cạnh bên vuông góc với đáy).',
    'Hình lăng trụ đứng có các mặt bên là những hình chữ nhật vuông góc với hai đáy. Thể tích bằng diện tích một đáy nhân với chiều cao.',
    'Hình lăng trụ đứng gồm h lớp phẳng song song có cùng diện tích S_day.',
    'Cho một khối gỗ hình lăng trụ đứng có đáy là tam giác vuông với hai cạnh góc vuông là 3 cm và 4 cm, chiều cao của lăng trụ là h = 10 cm. Tính thể tích khối gỗ.',
    '• Bước 1: Tính diện tích đáy (tam giác vuông):\n  S_day = (3 × 4) / 2 = 6 cm².\n• Bước 2: Tính thể tích khối lăng trụ đứng:\n  V = S_day × h = 6 × 10 = 60 cm³.\n• Kết luận: Thể tích khối gỗ là 60 cm³.',
    'Nhầm công thức lăng trụ với hình chóp (chia cho 3). Thể tích lăng trụ KHÔNG chia cho 3.',
    'Lăng trụ đứng có diện tích đáy bằng 15 cm² và chiều cao 8 cm. Tính thể tích (cm³).',
    120,
    'V = 15 × 8 = 120 cm³.',
    'solid'
  ),

  // ==================== THPT: LƯỢNG GIÁC, TỌA ĐỘ & HÌNH KHÔNG GIAN ====================
  g(
    'cosine',
    'high',
    'Định lý cosin trong tam giác',
    'a² = b² + c² − 2bc cos A',
    'a, b, c là ba cạnh tam giác, góc A đối diện với cạnh a.',
    'Mở rộng định lý Pythagoras cho tam giác bất kỳ. Khi A = 90°, cos 90° = 0 ta thu lại định lý Pythagoras a² = b² + c².',
    'Dùng tích vô hướng của hai vector cạnh xuất phát từ đỉnh A để khai triển bình phương hiệu.',
    'Cho tam giác ABC có b = 2, c = 2 và góc xen giữa A = 60°. Tính độ dài cạnh a.',
    '• Áp dụng định lý cosin: a² = b² + c² − 2bc cos A.\n• Thay số: a² = 2² + 2² − 2(2)(2) cos 60° = 4 + 4 − 8 × (1/2) = 8 − 4 = 4.\n• Do a > 0 nên: a = √4 = 2.\n• Kết luận: Cạnh a có độ dài bằng 2 (tam giác ABC là tam giác đều).',
    'Góc giữa hai cạnh b, c phải là góc xen giữa A.',
    'Tam giác có b=3, c=4, A=90°. Tính a.',
    5,
    'a² = 9 + 16 − 0 = 25 ⇒ a = 5.'
  ),

  g(
    'sine',
    'high',
    'Định lý sin trong tam giác',
    'a / sin A = b / sin B = c / sin C = 2R',
    'Tam giác không suy biến, R là bán kính đường tròn ngoại tiếp tam giác.',
    'Tỉ số giữa độ dài một cạnh với sin của góc đối diện luôn bằng đường kính đường tròn ngoại tiếp.',
    'Dây cung a chắn góc nội tiếp A; dựng đường kính suy ra tam giác vuông có cạnh huyền 2R và cạnh góc vuông a = 2R sin A.',
    'Cho tam giác ABC có cạnh a = 6 và góc đối diện A = 30°. Tính bán kính R của đường tròn ngoại tiếp.',
    '• Áp dụng định lý sin: a / sin A = 2R ⇒ R = a / (2 sin A).\n• Thay số: R = 6 / (2 × sin 30°) = 6 / (2 × 0.5) = 6 / 1 = 6.\n• Kết luận: Bán kính đường tròn ngoại tiếp tam giác là R = 6.',
    'Không dùng góc kề cạnh; dữ kiện cạnh–cạnh–góc có thể cho hai tam giác.',
    'a = 8, A = 90°. Tính R.',
    4,
    'R = 8 / (2 × 1) = 4.'
  ),

  g(
    'heron',
    'high',
    'Công thức Heron tính diện tích tam giác',
    'p = (a+b+c)/2,   S = √(p(p−a)(p−b)(p−c))',
    'a, b, c là độ dài ba cạnh của tam giác (thỏa bất đẳng thức tam giác); p là nửa chu vi.',
    'Giúp tính nhanh diện tích tam giác khi chỉ biết độ dài 3 cạnh mà không cần kẻ đường cao hay tính góc.',
    'Từ S = (1/2)bc sin A kết hợp với định lý cosin, phân tích thành 4 thừa số chứa p.',
    'Tính diện tích tam giác có độ dài ba cạnh là a = 3, b = 4, c = 5 theo công thức Heron.',
    '• Bước 1: Tính nửa chu vi p: p = (3 + 4 + 5) / 2 = 12 / 2 = 6.\n• Bước 2: Tính các hiệu: p − a = 3, p − b = 2, p − c = 1.\n• Bước 3: Áp dụng công thức Heron: S = √(6 × 3 × 2 × 1) = √36 = 6.\n• Kết luận: Diện tích tam giác bằng 6.',
    'p là nửa chu vi (chia cho 2), không phải chu vi.',
    'Tam giác có 3 cạnh là 5, 5, 6. Diện tích bằng bao nhiêu?',
    12,
    'p = 8 ⇒ S = √(8 × 3 × 3 × 2) = √144 = 12.'
  ),

  g(
    'dot',
    'high',
    'Tích vô hướng và góc giữa hai vector',
    'u · v = u₁v₁ + u₂v₂ + u₃v₃ = ‖u‖ ‖v‖ cos θ',
    'u, v trong không gian ℝ³; công thức tính góc yêu cầu cả hai khác vector 0.',
    'Hai vector khác 0 vuông góc với nhau khi và chỉ khi tích vô hướng của chúng bằng 0.',
    'Khai triển ‖u−v‖² theo tọa độ rồi đối chiếu với định lý cosin.',
    'Cho hai vector u = (1, 2, 0) và v = (3, −1, 4). Tính tích vô hướng u · v.',
    '• Áp dụng công thức tích vô hướng: u · v = u₁v₁ + u₂v₂ + u₃v₃\n• Thay số: u · v = 1×3 + 2×(−1) + 0×4 = 3 − 2 + 0 = 1.\n• Kết luận: Tích vô hướng u · v = 1.',
    'Không chia cho độ dài vector 0.',
    'Tính (1, 2, 3) · (4, 0, −1).',
    1,
    '1×4 + 2×0 + 3×(−1) = 1.',
    'vectors'
  ),

  g(
    'coordinates',
    'high',
    'Khoảng cách hai điểm và tọa độ trung điểm',
    'AB = √((x₂−x₁)² + (y₂−y₁)²),   M = ((x₁+x₂)/2, (y₁+y₂)/2)',
    'A(x₁, y₁), B(x₂, y₂) trong hệ tọa độ Oxy.',
    'Khoảng cách suy ra trực tiếp từ định lý Pythagoras; tọa độ trung điểm là trung bình cộng tọa độ hai đầu mút.',
    'Áp dụng Pythagoras cho tam giác vuông có các cạnh song song trục tọa độ.',
    'Cho hai điểm A(1, 2) và B(4, 6). Tính độ dài đoạn thẳng AB và tọa độ trung điểm M.',
    '• Độ dài đoạn thẳng AB: AB = √((4−1)² + (6−2)²) = √(3² + 4²) = √25 = 5.\n• Tọa độ trung điểm M: x_M = (1+4)/2 = 2.5; y_M = (2+6)/2 = 4.\n• Kết luận: Độ dài AB = 5 và trung điểm là M(2.5, 4).',
    'Nhầm dấu trừ trong công thức khoảng cách với dấu cộng trong công thức trung điểm.',
    'Cho A(0, 0) và B(6, 8). Tính độ dài AB.',
    10,
    'AB = √(6² + 8²) = √100 = 10.',
    'vectors'
  ),

  g(
    'line-distance',
    'high',
    'Khoảng cách từ điểm đến đường thẳng',
    'd(M, Δ) = |ax₀ + by₀ + c| / √(a² + b²)',
    'Đường thẳng Δ: ax + by + c = 0 (với a² + b² > 0); điểm M(x₀, y₀).',
    'Đoạn vuông góc kẻ từ M đến đường thẳng là khoảng cách ngắn nhất từ M đến mọi điểm trên đường thẳng.',
    'Vector (a, b) là vector pháp tuyến; khoảng cách là độ dài hình chiếu của vector HM lên pháp tuyến đơn vị.',
    'Tính khoảng cách từ gốc tọa độ O(0, 0) đến đường thẳng Δ: 3x + 4y − 10 = 0.',
    '• Áp dụng công thức khoảng cách: d(O, Δ) = |a(0) + b(0) + c| / √(a² + b²)\n• Thay số: d(O, Δ) = |3(0) + 4(0) − 10| / √(3² + 4²) = |−10| / √25 = 10 / 5 = 2.\n• Kết luận: Khoảng cách từ gốc tọa độ O đến đường thẳng Δ bằng 2.',
    'Tử số phải có dấu giá trị tuyệt đối để khoảng cách luôn không âm.',
    'Khoảng cách từ O đến đường thẳng 3x + 4y − 15 = 0 bằng bao nhiêu?',
    3,
    'd = |−15| / √(3² + 4²) = 15 / 5 = 3.'
  ),

  g(
    'circle-equation',
    'high',
    'Phương trình đường tròn trong mặt phẳng',
    '(x − a)² + (y − b)² = R²',
    'Đường tròn tâm I(a, b) và bán kính R > 0.',
    'Tập hợp tất cả các điểm M(x, y) cách tâm I một khoảng bằng R.',
    'Bình phương hai vế hệ thức khoảng cách IM = √((x−a)² + (y−b)²) = R.',
    'Xác định tọa độ tâm I và bán kính R của đường tròn (C): (x − 2)² + (y + 1)² = 9.',
    '• Dạng chuẩn tắc: (x − a)² + (y − b)² = R².\n• Đồng nhất hệ số: x − a = x − 2 ⇒ a = 2; y − b = y + 1 = y − (−1) ⇒ b = −1.\n• Bán kính: R² = 9 ⇒ R = 3 (do R > 0).\n• Kết luận: Đường tròn có tâm I(2, −1) và bán kính R = 3.',
    'Tọa độ tâm đổi dấu so với hằng số trong ngoặc.',
    'Đường tròn x² + y² = 49 có bán kính bao nhiêu?',
    7,
    'R² = 49 ⇒ R = 7.',
    'circle'
  ),

  g(
    'conics',
    'high',
    'Phương trình chính tắc ba đường conic',
    'x²/a² + y²/b² = 1;   x²/a² − y²/b² = 1;   y² = 2px',
    'Elip: a > b > 0; Hyperbol: a, b > 0; Parabol: p > 0.',
    'Elip có c² = a² − b²; Hyperbol có c² = a² + b². Parabol có tiêu điểm (p/2, 0) và đường chuẩn x = −p/2.',
    'Xuất phát từ tổng/hiệu khoảng cách đến hai tiêu điểm.',
    'Cho elip có phương trình x²/25 + y²/9 = 1. Tìm bán tiêu cự c và tiêu cự 2c.',
    '• Ta có: a² = 25, b² = 9 ⇒ a = 5, b = 3.\n• Hệ thức liên hệ: c² = a² − b² = 25 − 9 = 16.\n• Bán tiêu cự: c = √16 = 4 ⇒ Tiêu cự: 2c = 8.\n• Kết luận: c = 4 và tiêu cự là 8.',
    'Không nhầm c² = a² − b² của elip với c² = a² + b² của hyperbol.',
    'Elip x²/25 + y²/9 = 1 có tiêu cự 2c bằng bao nhiêu?',
    8,
    'c = √(25 − 9) = 4 ⇒ 2c = 8.'
  ),

  g(
    'space-plane',
    'high',
    'Mặt phẳng trong không gian Oxyz',
    'ax + by + cz + d = 0,   d(M, P) = |ax₀+by₀+cz₀+d| / √(a²+b²+c²)',
    '(a, b, c) ≠ (0, 0, 0); M(x₀, y₀, z₀).',
    'Vector n = (a, b, c) là vector pháp tuyến vuông góc với mặt phẳng.',
    'Phương trình n · (X − X₀) = 0; khoảng cách là độ dài hình chiếu lên pháp tuyến đơn vị.',
    'Tính khoảng cách từ gốc tọa độ O(0, 0, 0) đến mặt phẳng (P): x + 2y + 2z − 9 = 0.',
    '• Vector pháp tuyến n = (1, 2, 2).\n• Áp dụng công thức khoảng cách:\n  d(O, P) = |1(0) + 2(0) + 2(0) − 9| / √(1² + 2² + 2²)\n  = |−9| / √9 = 9 / 3 = 3.\n• Kết luận: Khoảng cách từ gốc O đến mặt phẳng (P) bằng 3.',
    'Mẫu số là độ dài vector pháp tuyến, không phải tổng các tọa độ.',
    'Khoảng cách từ O đến 2x + y + 2z − 6 = 0 bằng bao nhiêu?',
    2,
    'd = 6 / √(4 + 1 + 4) = 6 / 3 = 2.',
    'solid'
  ),

  g(
    'pyramid',
    'high',
    'Thể tích khối chóp trong không gian',
    'V = (B · h) / 3',
    'B là diện tích mặt đáy, h là chiều cao hạ vuông góc từ đỉnh chóp xuống mặt phẳng đáy.',
    'Khối chóp luôn có thể tích bằng đúng 1/3 thể tích hình lăng trụ có cùng diện tích đáy và chiều cao.',
    'Cắt lớp song song với đáy: diện tích thiết diện tỉ lệ với bình phương khoảng cách đến đỉnh; tích phân cho ra hệ số 1/3.',
    'Cho một khối chóp tứ giác có diện tích đáy B = 18 cm² và chiều cao vuông góc h = 5 cm. Tính thể tích khối chóp.',
    '• Áp dụng công thức thể tích khối chóp: V = (1/3) × B × h\n• Thay số: V = (1/3) × 18 × 5 = 6 × 5 = 30 cm³.\n• Kết luận: Thể tích khối chóp là 30 cm³.',
    'Không dùng độ dài cạnh bên thay thế cho chiều cao nếu cạnh bên không vuông góc với đáy.',
    'Khối chóp có đáy B = 24 cm² và cao h = 6 cm. Thể tích bằng bao nhiêu cm³?',
    48,
    'V = (24 × 6) / 3 = 48 cm³.',
    'solid'
  ),

  // ==================== ĐẠI HỌC: GIẢI TÍCH HÌNH HỌC & VI PHÂN ====================
  g(
    'cross',
    'university',
    'Tích có hướng và diện tích tam giác trong ℝ³',
    'u × v = (u₂v₃−u₃v₂, u₃v₁−u₁v₃, u₁v₂−u₂v₁),   S = ‖u × v‖ / 2',
    'u, v là hai vector cạnh cùng gốc trong không gian ℝ³.',
    'Tích có hướng tạo ra một vector vuông góc với cả u và v; độ dài của nó bằng diện tích hình bình hành căng bởi hai vector.',
    'Dựa trên đồng nhất thức Lagrange: ‖u×v‖² = ‖u‖²‖v‖² − (u·v)²',
    'Cho hai vector u = (3, 0, 0) và v = (0, 4, 0). Tính tích có hướng u × v và diện tích tam giác tạo bởi hai vector này.',
    '• Tính tích có hướng: u × v = (0, 0, 3×4 − 0) = (0, 0, 12).\n• Tính độ dài: ‖u × v‖ = 12.\n• Diện tích tam giác: S = ‖u × v‖ / 2 = 12 / 2 = 6.\n• Kết luận: u × v = (0, 0, 12) và diện tích tam giác bằng 6.',
    'Đổi thứ tự nhân làm đổi dấu vector: v × u = −(u × v).',
    'Hai cạnh tam giác là (2, 0, 0) và (0, 5, 0). Tính diện tích.',
    5,
    'S = ‖(0, 0, 10)‖ / 2 = 5.',
    'vectors'
  ),

  g(
    'triple',
    'university',
    'Tích hỗn tạp và thể tích tứ diện',
    'V_hop = |u · (v × w)|,   V_tu_dien = |u · (v × w)| / 6',
    'u, v, w là ba vector cùng xuất phát từ một đỉnh.',
    'Tích hỗn tạp là định thức của ma trận ghép bởi 3 vector; bằng 0 khi ba vector đồng phẳng.',
    'Thể tích hình hộp bằng diện tích đáy nhân chiều cao chiếu lên pháp tuyến.',
    'Cho ba vector u = (2, 0, 0), v = (0, 3, 0), w = (0, 0, 4). Tính thể tích khối hộp và tứ diện.',
    '• v × w = (12, 0, 0).\n• Tích hỗn tạp: u · (v × w) = 2 × 12 = 24.\n• Thể tích hộp: V = 24. Thể tích tứ diện: V_td = 24 / 6 = 4.\n• Kết luận: V hộp = 24, V tứ diện = 4.',
    'Quên chia cho 6 khi tính thể tích tứ diện.',
    'Tứ diện có 3 cạnh xuất phát từ đỉnh là (3, 0, 0), (0, 4, 0), (0, 0, 2). Tính V.',
    4,
    '|3 × 4 × 2| / 6 = 4.',
    'solid'
  ),

  g(
    'projection',
    'university',
    'Phép chiếu trực giao vector',
    'proj_v u = ((u · v) / (v · v)) v',
    'u, v trong không gian Euclid, v ≠ 0.',
    'Phân rã vector u thành hai thành phần vuông góc: một thành phần cùng phương với v, một thành phần trực giao với v.',
    'Đặt hình chiếu bằng tv, giải điều kiện (u − tv) · v = 0.',
    'Tìm hình chiếu của u = (3, 4) lên v = (1, 0).',
    '• u · v = 3×1 + 4×0 = 3; v · v = 1.\n• proj_v u = (3 / 1) × (1, 0) = (3, 0).\n• Kết luận: Vector hình chiếu là (3, 0).',
    'Hình chiếu là một vector, không phải một đại lượng vô hướng.',
    'Chiếu (6, 8) lên Ox. Độ dài vector hình chiếu bằng bao nhiêu?',
    6,
    'Hình chiếu là (6, 0), độ dài bằng 6.'
  ),

  g(
    'space-line',
    'university',
    'Khoảng cách từ điểm đến đường thẳng trong ℝ³',
    'd(M, ℓ) = ‖(M − A) × v‖ / ‖v‖',
    'Đường thẳng ℓ đi qua điểm A và có vector chỉ phương v ≠ 0.',
    'Khoảng cách chính là chiều cao hình bình hành dựng trên vector chỉ phương v và vector AM.',
    'Diện tích hình bình hành bằng đáy nhân cao: ‖v‖ × d = ‖AM × v‖.',
    'Tính khoảng cách từ điểm M(3, 4, 2) đến trục Oz trong không gian Oxyz.',
    '• Trục Oz qua O(0, 0, 0) với v = (0, 0, 1).\n• OM × v = (4, −3, 0) ⇒ ‖OM × v‖ = √(4² + (−3)²) = 5.\n• ‖v‖ = 1 ⇒ d = 5 / 1 = 5.\n• Kết luận: Khoảng cách từ M đến trục Oz bằng 5.',
    'Công thức tính khoảng cách đến toàn bộ đường thẳng vô hạn, không phải đoạn thẳng hữu hạn.',
    'Điểm M(6, 8, 7) cách trục Oz một khoảng bằng bao nhiêu?',
    10,
    '√(6² + 8²) = 10.'
  ),

  g(
    'affine',
    'university',
    'Phép biến đổi affine và tỉ số diện tích',
    'x′ = Ax + b,   S′ = |det A| · S',
    'A là ma trận 2×2 khả nghịch, b là vector tịnh tiến.',
    'Phép biến đổi affine bảo toàn tính thẳng hàng và song song. Tịnh tiến không đổi diện tích; phần ma trận A thay đổi diện tích tỉ lệ theo |det A|.',
    'Hình vuông đơn vị qua ma trận A biến thành hình bình hành có diện tích bằng |det A|.',
    'Một phép biến đổi affine có ma trận A = diag(2, 3) tác động lên hình tròn diện tích S = 5. Tính diện tích hình ảnh S′.',
    '• det A = 2 × 3 − 0 = 6.\n• S′ = |det A| × S = 6 × 5 = 30.\n• Kết luận: Diện tích hình ảnh bằng 30.',
    'Phép affine nói chung làm thay đổi góc và độ dài đoạn thẳng.',
    'A có định thức det A = 4 tác động lên miền diện tích 3. Diện tích ảnh bằng bao nhiêu?',
    12,
    'S′ = 4 × 3 = 12.'
  ),

  g(
    'rotation',
    'university',
    'Phép quay phẳng quanh gốc tọa độ',
    'x′ = x cos θ − y sin θ,   y′ = x sin θ + y cos θ',
    'Góc quay θ ngược chiều kim đồng hồ quanh gốc tọa độ O.',
    'Phép quay bảo toàn khoảng cách, góc và diện tích hình học (là một phép dời hình trực giao đặc biệt).',
    'Biểu diễn điểm trong tọa độ cực và dùng công thức cộng lượng giác.',
    'Quay điểm A(1, 0) quanh gốc O một góc θ = 90° ngược chiều kim đồng hồ.',
    '• cos 90° = 0, sin 90° = 1.\n• x′ = 1×0 − 0×1 = 0; y′ = 1×1 + 0×0 = 1.\n• Kết luận: Điểm ảnh là A′(0, 1).',
    'Phân biệt góc quay ngược chiều kim đồng hồ (dương) và thuận chiều (âm).',
    'Quay (2, 0) quanh gốc O góc 90° ngược chiều kim đồng hồ. Tung độ điểm ảnh bằng bao nhiêu?',
    2,
    'Tọa độ ảnh là (0, 2), tung độ bằng 2.'
  ),

  g(
    'arc-length',
    'university',
    'Độ dài đường cong tham số',
    'L = ∫ₐᵇ ‖r′(t)‖ dt',
    'r(t) khả vi liên tục trên đoạn [a, b].',
    'Tích phân tốc độ tức thời ‖r′(t)‖ theo thời gian t cho ra tổng quãng đường đi được.',
    'Xấp xỉ đường cong bằng chuỗi các đoạn dây cung vi phân và lấy giới hạn tổng Riemann.',
    'Tính độ dài đường cong r(t) = (3t, 4t) trên đoạn 0 ≤ t ≤ 2.',
    '• r′(t) = (3, 4) ⇒ ‖r′(t)‖ = √(3² + 4²) = 5.\n• L = ∫₀² 5 dt = 5 × (2 − 0) = 10.\n• Kết luận: Độ dài đường cong bằng 10.',
    'Không lấy tích phân vector rồi mới tính độ dài (đó là độ dời, không phải độ dài quãng đường).',
    'r(t) = (3t, 4t) với 0 ≤ t ≤ 3. Độ dài đường cong bằng bao nhiêu?',
    15,
    'L = 5 × 3 = 15.',
    'curve'
  ),

  g(
    'curvature',
    'university',
    'Độ cong của đường cong tham số',
    'κ = ‖r′ × r″‖ / ‖r′‖³',
    'r(t) trong ℝ³ khả vi hai lần, r′(t) ≠ 0.',
    'Độ cong đo tốc độ đổi hướng của vector tiếp tuyến đơn vị. Đường tròn bán kính R có độ cong cố định κ = 1/R; đường thẳng có κ = 0.',
    'Xuất phát từ công thức vi phân Frenet-Serret: κ = ‖dT/ds‖.',
    'Tính độ cong của đường tròn có bán kính R = 5.',
    '• Độ cong của đường tròn bán kính R là κ = 1 / R.\n• Thay R = 5: κ = 1 / 5 = 0.2.\n• Kết luận: Độ cong của đường tròn là 0.2.',
    'Không áp dụng tại điểm dừng r′(t) = 0.',
    'Đường tròn bán kính 4 có độ cong κ. Tính 100κ.',
    25,
    'κ = 1/4 = 0.25 ⇒ 100κ = 25.',
    'curve'
  ),

  g(
    'surface-tangent',
    'university',
    'Mặt phẳng tiếp tuyến của mặt mức',
    '∇F(P) · (X − P) = 0',
    'Mặt F(x, y, z) = 0; ∇F(P) ≠ 0 tại điểm P.',
    'Vector gradient ∇F(P) là vector pháp tuyến của mặt tiếp tuyến tại điểm chính quy P.',
    'Với mọi đường cong r(t) trên mặt đi qua P, đạo hàm F(r(t)) = 0 cho ra ∇F · r′ = 0.',
    'Viết phương trình mặt phẳng tiếp xúc với mặt cầu x² + y² + z² − 9 = 0 tại điểm P(3, 0, 0).',
    '• ∇F = (2x, 2y, 2z) ⇒ Tại P(3, 0, 0): n = (6, 0, 0).\n• Phương trình: 6(x − 3) + 0(y − 0) + 0(z − 0) = 0 ⇒ x = 3.\n• Kết luận: Mặt phẳng tiếp xúc là x = 3.',
    'Khi ∇F(P) = (0, 0, 0) thì điểm P là điểm kỳ dị, không dùng công thức này.',
    'Tiếp diện mặt cầu x² + y² + z² = 16 tại (4, 0, 0) có dạng x = k. Tìm k.',
    4,
    'x = 4.'
  ),

  g(
    'surface-area',
    'university',
    'Diện tích mặt tham số',
    'S = ∬_D ‖r_u × r_v‖ du dv',
    'Mặt tham số r(u, v) chính quy trên miền D.',
    'Tích có hướng của hai vector tiếp xúc r_u và r_v cho diện tích vi phân của hình bình hành tiếp xúc nhỏ.',
    'Mỗi ô vi phân dudv trên mặt phẳng tham số biến dạng thành một mảnh tiếp xúc có diện tích ‖r_u × r_v‖ dudv.',
    'Tính diện tích mặt phẳng r(u, v) = (u, v, 0) với 0 ≤ u ≤ 2, 0 ≤ v ≤ 3.',
    '• r_u = (1, 0, 0), r_v = (0, 1, 0) ⇒ r_u × r_v = (0, 0, 1) ⇒ ‖r_u × r_v‖ = 1.\n• S = ∫₀² du ∫₀³ dv = 2 × 3 = 6.\n• Kết luận: Diện tích mặt là 6.',
    'Tham số hóa trùng lặp nhiều lần sẽ đếm thừa diện tích.',
    'Miền 0 ≤ u ≤ 4, 0 ≤ v ≤ 5 cho mặt phẳng nằm ngang. Diện tích S bằng bao nhiêu?',
    20,
    'S = 4 × 5 = 20.'
  ),
];
