import type {Formula,Topic} from './content';
export const geometryTopics:Topic[] = [
 {id:'geometry-middle',name:'Hình học THCS',description:'Góc, tam giác, đồng dạng, đường tròn và các hình khối',symbol:'a² + b² = c²',color:'blue',level:'THCS'},
 {id:'geometry-high',name:'Hình học THPT',description:'Lượng giác, tọa độ, vector và hình học không gian',symbol:'u · v = |u||v| cos θ',color:'purple',level:'THPT'},
 {id:'geometry-university',name:'Hình học đại học',description:'Hình học giải tích, phép biến đổi và nhập môn đường cong, mặt',symbol:'κ = |r′ × r″| / |r′|³',color:'green',level:'Đại học cơ bản'},
];
function g(id:string,level:'middle'|'high'|'university',name:string,unicodeMath:string,condition:string,theory:string,proof:string,example:string,mistake:string,question:string,answer:number,solution:string,diagram?:Formula['diagram']):Formula {
 return {id:'geo-'+id,topic:'geometry-'+level,name,unicodeMath,latex:'',condition,theory,proof,example,mistake,question,answer,solution,diagram,tip:'Vẽ hình, ghi giả thiết, thống nhất đơn vị rồi chọn công thức phù hợp.'};
}
export const geometryFormulas:Formula[] = [
 g('angles','middle','Góc và tổng góc tam giác','A+B+C=180°','A, B, C là ba góc trong một tam giác phẳng Euclid.','Ba góc trong tạo thành một góc bẹt. Góc ngoài bằng tổng hai góc trong không kề.','Qua một đỉnh kẻ đường thẳng song song cạnh đối diện, dùng góc so le trong.','A=50°, B=60° ⇒ C=70°.','Không cộng thêm góc ngoài vào tổng ba góc trong.','Tam giác có hai góc 40° và 65°. Góc còn lại bao nhiêu độ?',75,'180−40−65=75°.'),
 g('pythagoras','middle','Định lý Pythagoras','a²+b²=c²','Tam giác vuông; a, b là hai cạnh góc vuông, c là cạnh huyền.','Bình phương cạnh huyền bằng tổng bình phương hai cạnh góc vuông. Đảo lại, ba cạnh dương thỏa hệ thức tạo tam giác vuông.','Ghép bốn tam giác vuông vào hình vuông cạnh a+b: (a+b)²=4ab/2+c².','Hai cạnh góc vuông 3 cm, 4 cm ⇒ cạnh huyền 5 cm.','Cạnh huyền đối diện góc vuông và dài nhất.','Hai cạnh góc vuông 5 và 12. Tính cạnh huyền.',13,'c=√(25+144)=13.','right-triangle'),
 g('triangle-area','middle','Diện tích tam giác','S=ah/2','a là một cạnh; h là khoảng cách vuông góc từ đỉnh đối diện đến đường thẳng chứa cạnh đó.','Diện tích phụ thuộc đáy và chiều cao tương ứng, kể cả khi chân đường cao ở ngoài tam giác.','Ghép hai tam giác bằng nhau thành hình bình hành có diện tích ah.','a=8 cm, h=5 cm ⇒ S=20 cm².','Không lấy cạnh xiên thay cho chiều cao.','Tam giác có đáy 12, chiều cao 7. Tính diện tích.',42,'S=12×7/2=42.','triangle-height'),
 g('similarity','middle','Tam giác đồng dạng và tỉ số diện tích','a′/a=b′/b=c′/c=k,  S′/S=k²','Hai tam giác đồng dạng, các cạnh được ghép đúng tương ứng, k>0.','Độ dài tăng k lần thì diện tích tăng k² lần. Nhận biết đồng dạng bằng góc–góc, cạnh–cạnh–cạnh hoặc cạnh–góc–cạnh tương ứng.','Đáy và chiều cao cùng nhân k; thay vào S=ah/2.','Tỉ số cạnh 3 ⇒ tỉ số diện tích 9.','Tỉ số diện tích không bằng tỉ số cạnh.','Một tam giác phóng lớn các cạnh gấp 4. Diện tích gấp mấy lần?',16,'4²=16 lần.'),
 g('thales','middle','Định lý Thales','AD/AB=AE/AC=DE/BC','D∈AB, E∈AC, DE∥BC trong tam giác ABC; xét các đoạn thẳng dương.','Một đường song song với một cạnh cắt hai cạnh còn lại theo cùng tỉ số.','Tam giác ADE và ABC đồng dạng theo hai góc.','AD/AB=1/2, BC=10 ⇒ DE=5.','Phải có giả thiết song song; không trộn AD/DB với AE/AC.','DE∥BC, AD/AB=2/3 và BC=12. Tính DE.',8,'DE=(2/3)×12=8.'),
 g('quadrilaterals','middle','Diện tích tứ giác quen thuộc','S_(chữ nhật)=ab,  S_(bình hành)=ah,  S_(hình thang)=(a+b)h/2','a,b là cạnh kề ở hình chữ nhật hoặc hai đáy song song ở hình thang; h là chiều cao tương ứng.','Hình thoi còn có S=d₁d₂/2, với d₁,d₂ là hai đường chéo.','Cắt ghép hình bình hành thành chữ nhật; ghép hai hình thang bằng nhau thành hình bình hành.','Hình thang đáy 6 và 10, cao 4 ⇒ S=32.','Hai đáy hình thang phải song song; h vuông góc hai đáy.','Hình thang đáy 8 và 14, cao 5. Tính diện tích.',55,'S=(8+14)×5/2=55.'),
 g('circle','middle','Chu vi và diện tích hình tròn','C=2πr,  S=πr²','r>0 là bán kính; đường kính d=2r.','Chu vi tăng tuyến tính theo r, diện tích tăng theo r².','C/d=π theo định nghĩa π; chia hình tròn thành nhiều quạt nhỏ, ghép gần hình chữ nhật đáy πr, cao r rồi lấy giới hạn.','r=3 ⇒ C=6π, S=9π.','Không thay đường kính vào vị trí bán kính.','Hình tròn bán kính 5 có S=kπ. Tìm k.',25,'S=π×5²=25π.','circle'),
 g('inscribed-angle','middle','Góc nội tiếp và tiếp tuyến','∠APB=(số đo cung AB không chứa P)/2','A,B,P trên một đường tròn, P khác A,B.','Góc nội tiếp bằng nửa số đo cung bị chắn. Tiếp tuyến tại T vuông góc bán kính OT.','Nối tâm với các đỉnh; các tam giác cân tạo quan hệ góc tâm bằng hai lần góc nội tiếp chắn cùng cung.','Cung AB không chứa P có số đo 100° ⇒ ∠APB=50°.','Phải chọn cung không chứa đỉnh góc nội tiếp.','Góc nội tiếp chắn nửa đường tròn bằng bao nhiêu độ?',90,'Nửa đường tròn 180°; góc nội tiếp bằng 180/2=90°.'),
 g('right-trig','middle','Tỉ số lượng giác trong tam giác vuông','sin α=a/c,  cos α=b/c,  tan α=a/b','0°<α<90°; a đối diện α, b kề α, c là cạnh huyền.','Các tỉ số không đổi với những tam giác vuông có cùng góc nhọn vì chúng đồng dạng.','Dùng đồng dạng để chứng minh tỉ số chỉ phụ thuộc góc α.','Tam giác 3–4–5, cạnh đối α là 3 ⇒ sin α=3/5.','Cạnh kề ở công thức cos không phải cạnh huyền.','Cạnh đối α là 6, cạnh huyền 10. Tính 10 sin α.',6,'10×(6/10)=6.'),
 g('solids','middle','Hộp chữ nhật, trụ, nón và cầu','V_(hộp)=abc,  V_(trụ)=πr²h,  V_(nón)=πr²h/3,  V_(cầu)=4πr³/3','Kích thước dương; h là chiều cao vuông góc đáy.','Thể tích đo phần không gian bên trong. Diện tích mặt cầu là 4πr².','Hộp đếm các khối đơn vị; trụ từ diện tích đáy nhân cao; nón và cầu có thể chứng minh bằng phương pháp cắt lớp ở giải tích.','Hộp 2×3×4 có V=24; trụ r=2,h=3 có V=12π.','Không nhầm diện tích (đơn vị vuông) với thể tích (đơn vị khối).','Khối hộp có ba kích thước 3, 4, 5. Tính thể tích.',60,'V=3×4×5=60.','solid'),
 g('cosine','high','Định lý cosin','a²=b²+c²−2bc cos A','a,b,c là ba cạnh tam giác, A đối diện a.','Mở rộng Pythagoras cho tam giác bất kỳ; khi A=90°, cos A=0.','Dùng tích vô hướng của hai vector cạnh xuất phát từ đỉnh A để khai triển bình phương hiệu.','b=c=2, A=60° ⇒ a²=4.','Góc giữa hai cạnh b,c phải là A.','b=3,c=4,A=90°. Tính a.',5,'a²=9+16−0=25 ⇒ a=5.'),
 g('sine','high','Định lý sin','a/(sin A)=b/(sin B)=c/(sin C)=2R','Tam giác không suy biến, R là bán kính đường tròn ngoại tiếp.','Tỉ số cạnh với sin góc đối diện bằng đường kính đường tròn ngoại tiếp.','Dây cung a chắn góc nội tiếp A; dùng tam giác vuông dựng qua đường kính suy ra a=2R sin A.','a=6,A=30° ⇒ R=6.','Không dùng góc kề cạnh; dữ kiện cạnh–cạnh–góc có thể cho hai tam giác.','a=8, A=90°. Tính R.',4,'R=8/(2×1)=4.'),
 g('heron','high','Công thức Heron','p=(a+b+c)/2,  S=√(p(p−a)(p−b)(p−c))','a,b,c>0 và thỏa bất đẳng thức tam giác nghiêm ngặt.','Tính diện tích khi biết ba cạnh; p là nửa chu vi.','Từ S=bc sin A/2 và định lý cosin, bình phương rồi phân tích thành bốn thừa số.','Tam giác cạnh 3,4,5 có p=6, S=√(6×3×2×1)=6.','p là nửa chu vi, không phải chu vi.','Tam giác cạnh 5,5,6 có diện tích bao nhiêu?',12,'p=8 ⇒ S=√(8×3×3×2)=12.'),
 g('dot','high','Tích vô hướng và góc giữa vector','u·v=u₁v₁+u₂v₂+u₃v₃=‖u‖‖v‖cos θ','u,v∈ℝ³; công thức tính góc yêu cầu cả hai khác vector 0.','Hai vector khác 0 vuông góc khi tích vô hướng bằng 0.','Khai triển ‖u−v‖² theo tọa độ rồi so với định lý cosin.','(1,2,0)·(3,−1,4)=1.','Không chia cho độ dài vector 0.','Tính (1,2,3)·(4,0,−1).',1,'1×4+2×0+3×(−1)=1.','vectors'),
 g('coordinates','high','Khoảng cách và trung điểm','AB=√((x₂−x₁)²+(y₂−y₁)²),  M=((x₁+x₂)/2,(y₁+y₂)/2)','A(x₁,y₁), B(x₂,y₂) trong hệ tọa độ trực chuẩn.','Hiệu tọa độ tạo hai cạnh vuông; trung điểm lấy trung bình từng tọa độ.','Áp dụng Pythagoras cho độ dài; AM=MB và M nằm trên AB theo phép chia đôi vector.','A(1,2), B(4,6) ⇒ AB=5, M(2.5,4).','Không cộng tọa độ khi tính vector AB.','A(0,0), B(6,8). Tính AB.',10,'AB=√(36+64)=10.','vectors'),
 g('line-distance','high','Đường thẳng và khoảng cách điểm–đường','d(M,Δ)=|ax₀+by₀+c|/√(a²+b²)','Δ: ax+by+c=0, (a,b)≠(0,0); M(x₀,y₀).','Vector (a,b) là pháp tuyến; khoảng cách là độ dài hình chiếu lên pháp tuyến đơn vị.','Chọn H∈Δ và chiếu HM lên (a,b)/√(a²+b²).','M(0,0), Δ:3x+4y−10=0 ⇒ d=2.','Tử số phải có trị tuyệt đối.','Khoảng cách từ O đến 3x+4y−15=0?',3,'d=15/5=3.'),
 g('circle-equation','high','Phương trình đường tròn','(x−a)²+(y−b)²=R²','Tâm I(a,b), R>0; tọa độ trực chuẩn.','Tập hợp điểm cách tâm I một khoảng R.','Bình phương công thức khoảng cách IM=R.','(x−2)²+(y+1)²=9 có tâm (2,−1), bán kính 3.','Tọa độ tâm đổi dấu so với hằng số trong ngoặc.','Đường tròn x²+y²=49 có bán kính bao nhiêu?',7,'R²=49, R>0 ⇒ R=7.','circle'),
 g('conics','high','Elip, hyperbol và parabol','x²/a²+y²/b²=1;  x²/a²−y²/b²=1;  y²=2px','Elip: a>b>0; hyperbol: a,b>0; parabol theo quy ước p>0.','Elip có c²=a²−b²; hyperbol có c²=a²+b². Parabol y²=2px có tiêu điểm (p/2,0), đường chuẩn x=−p/2.','Xuất phát từ tổng hoặc hiệu khoảng cách đến hai tiêu điểm; parabol từ khoảng cách đến tiêu điểm bằng khoảng cách đến đường chuẩn.','Elip x²/25+y²/9=1 có c=4.','Không trộn quy ước y²=2px với y²=4px.','Elip x²/25+y²/9=1 có tiêu cự 2c bằng bao nhiêu?',8,'c=√(25−9)=4 ⇒ 2c=8.'),
 g('space-plane','high','Mặt phẳng trong không gian','ax+by+cz+d=0,  d(M,P)=|ax₀+by₀+cz₀+d|/√(a²+b²+c²)','(a,b,c)≠(0,0,0); M(x₀,y₀,z₀).','Vector pháp tuyến n=(a,b,c) vuông góc mọi hướng nằm trong mặt phẳng.','Viết n·(X−X₀)=0; khoảng cách là độ dài hình chiếu lên pháp tuyến đơn vị.','P:x+2y+2z−9=0 ⇒ d(O,P)=3.','Mẫu là độ dài pháp tuyến, không phải tổng tọa độ.','Tính khoảng cách từ O đến 2x+y+2z−6=0.',2,'d=6/√(4+1+4)=2.','solid'),
 g('pyramid','high','Thể tích lăng trụ và hình chóp','V_(lăng trụ)=Bh,  V_(chóp)=Bh/3','B là diện tích đáy, h là chiều cao vuông góc mặt phẳng đáy.','Lăng trụ xiên vẫn dùng chiều cao vuông góc. Chóp bằng một phần ba lăng trụ cùng đáy và chiều cao.','Cắt lớp song song đáy: diện tích tiết diện chóp tỉ lệ bình phương khoảng cách đến đỉnh; tích phân cho hệ số 1/3.','Chóp B=18,h=5 ⇒ V=30.','Không dùng độ dài cạnh bên thay h nếu cạnh bên không vuông góc đáy.','Chóp có B=24 và h=6. Tính thể tích.',48,'V=24×6/3=48.','solid'),
 g('cross','university','Tích có hướng và diện tích','u×v=(u₂v₃−u₃v₂,u₃v₁−u₁v₃,u₁v₂−u₂v₁),  S=‖u×v‖/2','u,v là hai vector cạnh cùng gốc của một tam giác trong ℝ³, hệ trực chuẩn thuận.','Tích có hướng vuông góc hai vector; độ dài bằng diện tích hình bình hành do chúng sinh ra.','‖u×v‖²=‖u‖²‖v‖²−(u·v)² ⇒ ‖u×v‖=‖u‖‖v‖sin θ.','u=(3,0,0),v=(0,4,0) ⇒ u×v=(0,0,12), S=6.','Đổi thứ tự làm đổi dấu: v×u=−u×v.','Hai cạnh tam giác là (2,0,0) và (0,5,0). Tính diện tích.',5,'S=‖(0,0,10)‖/2=5.','vectors'),
 g('triple','university','Tích hỗn tạp và thể tích','V_(hộp)=|u·(v×w)|,  V_(tứ diện)=|u·(v×w)|/6','u,v,w cùng gốc trong ℝ³; tứ diện có ba cạnh này tại một đỉnh.','Tích hỗn tạp là thể tích có dấu; bằng 0 khi ba vector đồng phẳng.','Diện tích đáy ‖v×w‖ nhân chiều cao |u·n̂| cho hình hộp; tứ diện chiếm 1/6.','u=(2,0,0),v=(0,3,0),w=(0,0,4) ⇒ thể tích hộp 24, tứ diện 4.','Thể tích hình học luôn không âm; nhớ hệ số 1/6 cho tứ diện.','Tứ diện có ba cạnh tại một đỉnh (3,0,0),(0,4,0),(0,0,2). Tính V.',4,'|3×4×2|/6=4.','solid'),
 g('projection','university','Phép chiếu trực giao','proj_v u=((u·v)/(v·v))v','u,v trong không gian Euclid, v≠0.','Tách u thành một thành phần song song v và một thành phần vuông góc v.','Đặt hình chiếu bằng tv; điều kiện (u−tv)·v=0 cho t=(u·v)/(v·v).','Chiếu (3,4) lên (1,0) được (3,0).','Hệ số chiếu có thể âm; hình chiếu là vector.','Chiếu (6,8) lên trục Ox. Độ dài hình chiếu bằng bao nhiêu?',6,'Hình chiếu (6,0), độ dài 6.'),
 g('space-line','university','Khoảng cách đến đường thẳng trong ℝ³','d(M,ℓ)=‖(M−A)×v‖/‖v‖','ℓ:A+tv, t∈ℝ, v≠0.','Khoảng cách là chiều cao hình bình hành dựng trên vector chỉ phương và vector nối tới điểm.','Diện tích hình bình hành bằng ‖v‖d và cũng bằng ‖(M−A)×v‖.','Trục Oz: A=O,v=(0,0,1); M(3,4,2) cách trục 5.','Công thức cho khoảng cách đến cả đường thẳng, không phải đoạn thẳng hữu hạn.','M(6,8,7) cách trục Oz bao nhiêu?',10,'Khoảng cách √(6²+8²)=10.'),
 g('affine','university','Phép biến đổi affine và định thức','x′=Ax+b,  S′=|det A|S','A là ma trận 2×2 khả nghịch cho phép affine phẳng; b là vector tịnh tiến.','Affine bảo toàn thẳng hàng và song song. Tịnh tiến không đổi diện tích; phần tuyến tính nhân diện tích với |det A|.','Ảnh của hình vuông đơn vị là hình bình hành có diện tích |det A|; mở rộng bằng chia nhỏ và cộng diện tích.','A=diag(2,3) ⇒ mọi diện tích tăng 6 lần.','Phép affine nói chung không bảo toàn góc hay độ dài.','A=diag(3,4), hình ban đầu diện tích 2. Tính diện tích ảnh.',24,'|det A|=12 ⇒ S′=12×2=24.'),
 g('rotation','university','Phép quay phẳng và ma trận trực giao','x′=x cos θ−y sin θ,  y′=x sin θ+y cos θ','Quay chủ động ngược chiều kim đồng hồ quanh gốc O trong hệ trục thuận.','Ma trận quay thỏa AᵀA=I và det A=1 nên bảo toàn độ dài, góc và định hướng.','Viết điểm theo tọa độ cực rồi dùng công thức cộng góc.','Quay (1,0) góc 90° được (0,1).','Phân biệt quay vector với quay hệ tọa độ, hai phép dùng dấu góc ngược nhau.','Quay (2,0) góc 90° ngược chiều kim đồng hồ. Tung độ ảnh?',2,'Ảnh là (0,2).'),
 g('arc-length','university','Độ dài đường cong tham số','L=∫_a^b▒‖r′(t)‖ dt','r:[a,b]→ℝ² hoặc ℝ³ khả vi liên tục; tính chiều dài theo tham số, có tính số lần đi qua.','Tốc độ ‖r′(t)‖ tích lũy thành độ dài.','Xấp xỉ đường cong bằng các đoạn dây cung, dùng r(t+Δt)−r(t)≈r′(t)Δt rồi lấy giới hạn tổng Riemann.','r(t)=(3t,4t), 0≤t≤2 ⇒ L=∫₀²5dt=10.','Không tích phân vector r′ rồi lấy chuẩn: đó chỉ là độ dời.','r(t)=(3t,4t), 0≤t≤3. Tính L.',15,'‖r′‖=5 ⇒ L=5×3=15.','curve'),
 g('curvature','university','Độ cong của đường cong','κ=‖r′×r″‖/‖r′‖³','r(t)∈ℝ³ khả vi hai lần, r′(t)≠0; đường phẳng xem như có z=0.','Độ cong đo tốc độ đổi hướng của tiếp tuyến đơn vị theo độ dài cung. Đường tròn bán kính R có κ=1/R.','Từ T=r′/‖r′‖ và κ=‖dT/ds‖, dùng ds/dt=‖r′‖ để suy ra công thức.','Đường thẳng κ=0; đường tròn R=5 có κ=0.2.','Không áp dụng tại điểm tham số có r′=0 nếu chưa đổi tham số hoặc xét giới hạn.','Đường tròn bán kính 4 có độ cong κ. Tính 100κ.',25,'κ=1/4 ⇒ 100κ=25.','curve'),
 g('surface-tangent','university','Mặt mức và mặt phẳng tiếp tuyến','∇F(P)·(X−P)=0','Mặt F(x,y,z)=0; F khả vi liên tục gần P, F(P)=0 và ∇F(P)≠0.','Gradient là pháp tuyến của mặt mức tại điểm chính quy.','Với đường cong r(t) nằm trên mặt, F(r(t))=0 ⇒ ∇F·r′=0 theo quy tắc dây chuyền.','Mặt cầu x²+y²+z²=9 tại P(3,0,0) có tiếp diện x=3.','Gradient bằng 0 không xác định được mặt phẳng tiếp tuyến bằng công thức này.','Tiếp diện mặt cầu x²+y²+z²=16 tại (4,0,0) là x=k. Tìm k.',4,'∇F=(8,0,0) ⇒ 8(x−4)=0 ⇒ x=4.'),
 g('surface-area','university','Diện tích mặt tham số','S=∬_D▒‖r_u×r_v‖ du dv','r(u,v) khả vi liên tục, chính quy (r_u×r_v≠0); tham số hóa một lần, trừ các biên hoặc tập diện tích 0.','Tích có hướng hai vector tiếp xúc cho hệ số đổi diện tích từ miền tham số lên mặt.','Một ô ΔuΔv biến thành hình bình hành xấp xỉ có diện tích ‖r_u×r_v‖ΔuΔv; lấy giới hạn.','r(u,v)=(u,v,0), D=[0,2]×[0,3] ⇒ S=6.','Tham số hóa chồng nhiều lần sẽ đếm diện tích nhiều lần.','r(u,v)=(u,v,0), 0≤u≤4, 0≤v≤5. Tính S.',20,'‖r_u×r_v‖=1 ⇒ S=4×5=20.'),
];
