const r=String.raw;
// Display form; the UnicodeMath text remains available for Word and export.
export const geometryLatex:Record<string,string>={
 angles:r`A+B+C=180^\circ`,
 pythagoras:r`a^2+b^2=c^2`,
 'triangle-area':r`S=\frac{ah}{2}`,
 similarity:r`\begin{aligned}\frac{a'}a=\frac{b'}b=\frac{c'}c&=k\\[4pt]\frac{S'}S&=k^2\end{aligned}`,
 thales:r`\frac{AD}{AB}=\frac{AE}{AC}=\frac{DE}{BC}`,
 quadrilaterals:r`\begin{aligned}S_{\mathrm{HCN}}&=ab\\S_{\mathrm{HBH}}&=ah\\S_{\mathrm{HT}}&=\frac{(a+b)h}{2}\end{aligned}`,
 circle:r`C=2\pi r,\qquad S=\pi r^2`,
 'inscribed-angle':r`\angle APB=\frac{1}{2}\,m(\widehat{AB})`,
 'right-trig':r`\begin{aligned}\sin\alpha&=\frac ac\\[4pt]\cos\alpha&=\frac bc\\[4pt]\tan\alpha&=\frac ab\end{aligned}`,
 solids:r`\begin{aligned}V_{\mathrm{hop}}&=abc\\V_{\mathrm{tru}}&=\pi r^2h\\V_{\mathrm{non}}&=\frac{\pi r^2h}{3}\\[4pt]V_{\mathrm{cau}}&=\frac{4\pi r^3}{3}\end{aligned}`,
 cosine:r`a^2=b^2+c^2-2bc\cos A`,
 sine:r`\frac{a}{\sin A}=\frac{b}{\sin B}=\frac{c}{\sin C}=2R`,
 heron:r`\begin{aligned}p&=\frac{a+b+c}{2}\\[4pt]S&=\sqrt{p(p-a)(p-b)(p-c)}\end{aligned}`,
 dot:r`\begin{aligned}\mathbf u\cdot\mathbf v&=u_1v_1+u_2v_2+u_3v_3\\&=\lVert\mathbf u\rVert\lVert\mathbf v\rVert\cos\theta\end{aligned}`,
 coordinates:r`\begin{aligned}AB&=\sqrt{(x_2-x_1)^2+(y_2-y_1)^2}\\[5pt]M&=\left(\frac{x_1+x_2}{2},\frac{y_1+y_2}{2}\right)\end{aligned}`,
 'line-distance':r`d(M,\Delta)=\frac{|ax_0+by_0+c|}{\sqrt{a^2+b^2}}`,
 'circle-equation':r`(x-a)^2+(y-b)^2=R^2`,
 conics:r`\begin{aligned}\text{Elip: }&\frac{x^2}{a^2}+\frac{y^2}{b^2}=1\\[5pt]\text{Hyperbol: }&\frac{x^2}{a^2}-\frac{y^2}{b^2}=1\\[5pt]\text{Parabol: }&y^2=2px\end{aligned}`,
 'space-plane':r`\begin{gathered}ax+by+cz+d=0\\[5pt]d(M,P)=\frac{|ax_0+by_0+cz_0+d|}{\sqrt{a^2+b^2+c^2}}\end{gathered}`,
 pyramid:r`\begin{aligned}V_{\mathrm{LT}}&=Bh\\V_{\mathrm{C}}&=\frac{Bh}{3}\end{aligned}`,
 cross:r`\begin{gathered}\mathbf u\times\mathbf v=\begin{pmatrix}u_2v_3-u_3v_2\\u_3v_1-u_1v_3\\u_1v_2-u_2v_1\end{pmatrix}\\[6pt]S=\frac{\lVert\mathbf u\times\mathbf v\rVert}{2}\end{gathered}`,
 triple:r`\begin{aligned}V_{\mathrm{hop}}&=|\mathbf u\cdot(\mathbf v\times\mathbf w)|\\[5pt]V_{\mathrm{TD}}&=\frac{|\mathbf u\cdot(\mathbf v\times\mathbf w)|}{6}\end{aligned}`,
 projection:r`\operatorname{proj}_{\mathbf v}\mathbf u=\frac{\mathbf u\cdot\mathbf v}{\mathbf v\cdot\mathbf v}\,\mathbf v`,
 'space-line':r`d(M,\ell)=\frac{\lVert(M-A)\times\mathbf v\rVert}{\lVert\mathbf v\rVert}`,
 affine:r`\begin{aligned}\mathbf x'&=A\mathbf x+\mathbf b\\S'&=|\det A|\,S\end{aligned}`,
 rotation:r`\begin{aligned}x'&=x\cos\theta-y\sin\theta\\y'&=x\sin\theta+y\cos\theta\end{aligned}`,
 'arc-length':r`L=\int_a^b\lVert\mathbf r'(t)\rVert\,dt`,
 curvature:r`\kappa=\frac{\lVert\mathbf r'\times\mathbf r''\rVert}{\lVert\mathbf r'\rVert^3}`,
 'surface-tangent':r`\nabla F(P)\cdot(X-P)=0`,
 'surface-area':r`S=\iint_D\lVert\mathbf r_u\times\mathbf r_v\rVert\,du\,dv`,
};
