import type {Topic,Formula} from './content';

export const matrixTopics: Topic[] = [
  {
    id: 'matrices',
    name: 'Ma trận & Đại số tuyến tính',
    description: 'Phép toán ma trận, định thức, nghịch đảo, hệ phương trình và giá trị riêng',
    symbol: '[A] · det(A)',
    color: 'blue',
    level: 'Đại học & THPT Chuyên',
  },
];

const r = String.raw;

export const matrixFormulas: Formula[] = [
  {
    id: 'mat-definition',
    topic: 'matrices',
    name: 'Khái niệm ma trận & các dạng đặc biệt',
    latex: r`A = [a_{ij}]_{m\times n} = \begin{pmatrix} a_{11} & a_{12} & \cdots & a_{1n} \\ a_{21} & a_{22} & \cdots & a_{2n} \\ \vdots & \vdots & \ddots & \vdots \\ a_{m1} & a_{m2} & \cdots & a_{mn} \end{pmatrix},\quad I_n = \begin{pmatrix} 1 & 0 & \cdots & 0 \\ 0 & 1 & \cdots & 0 \\ \vdots & \vdots & \ddots & \vdots \\ 0 & 0 & \cdots & 1 \end{pmatrix}`,
    condition: 'm, n là các số nguyên dương chỉ số hàng và số cột. Ma trận đơn vị Iₙ có số hàng bằng số cột (m = n).',
    theory: 'Ma trận cấp m × n là một bảng chữ nhật gồm m hàng và n cột các số thực (hoặc phức). Một số ma trận đặc biệt: Ma trận vuông (m = n), ma trận không O (mọi phần tử bằng 0), ma trận đơn vị I (đường chéo chính toàn 1, còn lại bằng 0), ma trận đường chéo (chỉ có phần tử trên đường chéo chính), ma trận tam giác trên/dưới.',
    proof: 'Ma trận đơn vị Iₙ đóng vai trò như số 1 trong đại số thông thường: Với mọi ma trận vuông A cấp n, luôn có A · Iₙ = Iₙ · A = A. Điều này được kiểm tra trực tiếp qua định nghĩa phép nhân ma trận.',
    example: 'Cho ma trận $A = \\begin{pmatrix} 1 & 2 & 3 \\\\ 4 & 5 & 6 \\end{pmatrix}$. Xác định cấp của ma trận $A$ và tìm giá trị phần tử $a_{23}$.',
    exampleSolution: '• Bước 1: Đếm số hàng và số cột của ma trận $A$:\n  - Ma trận $A$ có 2 hàng và 3 cột.\n• Bước 2: Kết luận cấp của ma trận $A$ là $2 \\times 3$.\n• Bước 3: Tìm phần tử $a_{23}$ (nằm ở hàng 2, cột 3):\n  - Phần tử ở vị trí hàng 2 cột 3 là $a_{23} = 6$.\n• Kết luận: Ma trận $A$ có cấp $2 \\times 3$ và $a_{23} = 6$.',
    tip: 'Chỉ số thứ nhất luôn chỉ số HÀNG, chỉ số thứ hai luôn chỉ số CỘT: a_{hàng, cột}. Ghi nhớ: "Hàng trước, Cột sau".',
    mistake: 'Nhầm lẫn giữa thứ tự hàng và cột (viết a_{cột, hàng}).',
    question: 'Cho ma trận vuông đơn vị I₃ cấp 3. Tổng tất cả các phần tử trên đường chéo chính của I₃ bằng bao nhiêu?',
    answer: 3,
    solution: 'I₃ có 3 phần tử trên đường chéo chính, mỗi phần tử đều bằng 1. Tổng = 1 + 1 + 1 = 3.',
  },
  {
    id: 'mat-addition-scalar',
    topic: 'matrices',
    name: 'Phép cộng ma trận & nhân với vô hướng',
    latex: r`C = A + B \implies c_{ij} = a_{ij} + b_{ij},\qquad kA = [k \cdot a_{ij}]`,
    condition: 'Hai ma trận A và B phải CÙNG CẤP (cùng số hàng và cùng số cột) mới cộng hoặc trừ được cho nhau. k là một số vô hướng thực hoặc phức.',
    theory: 'Phép cộng hai ma trận cùng cấp được thực hiện bằng cách cộng từng cặp phần tử ở vị trí tương ứng. Nhân ma trận với số k là nhân TẤT CẢ các phần tử của ma trận với k. Phép cộng có tính giao hoán: A + B = B + A, kết hợp: (A + B) + C = A + (B + C), và phân phối: k(A + B) = kA + kB.',
    proof: 'Suy ra trực tiếp từ tính chất giao hoán và phân phối của phép cộng và nhân các số thực trên từng vị trí thành phần.',
    example: 'Cho hai ma trận $A = \\begin{pmatrix} 1 & 3 \\\\ 2 & 4 \\end{pmatrix}$ và $B = \\begin{pmatrix} 5 & -1 \\\\ 0 & 2 \\end{pmatrix}$. Tính ma trận $2A + B$.',
    exampleSolution: '• Bước 1: Tính ma trận $2A$ bằng cách nhân mỗi phần tử của $A$ với 2:\n  $$2A = 2 \\begin{pmatrix} 1 & 3 \\\\ 2 & 4 \\end{pmatrix} = \\begin{pmatrix} 2 & 6 \\\\ 4 & 8 \\end{pmatrix}$$\n• Bước 2: Thực hiện phép cộng $2A + B$ từng phần tử tương ứng:\n  $$2A + B = \\begin{pmatrix} 2+5 & 6+(-1) \\\\ 4+0 & 8+2 \\end{pmatrix} = \\begin{pmatrix} 7 & 5 \\\\ 4 & 10 \\end{pmatrix}$$\n• Kết quả: $2A + B = \\begin{pmatrix} 7 & 5 \\\\ 4 & 10 \\end{pmatrix}$.',
    tip: 'Phép trừ A − B tương đương với A + (−1)B. Nhớ đổi dấu tất cả phần tử của ma trận bị trừ.',
    mistake: 'Cộng hai ma trận khác cấp (ví dụ lấy ma trận 2×3 cộng với ma trận 3×2). Điều này không xác định!',
    question: 'Cho A = [[2, -1], [3, 5]]. Tính phần tử ở hàng 1 cột 1 của ma trận 3A.',
    answer: 6,
    solution: 'Phần tử ở hàng 1 cột 1 của 3A bằng 3 × 2 = 6.',
  },
  {
    id: 'mat-multiplication',
    topic: 'matrices',
    name: 'Phép nhân hai ma trận',
    latex: r`C_{m\times p} = A_{m\times n} \cdot B_{n\times p},\qquad c_{ij} = \sum_{k=1}^n a_{ik} b_{kj} = a_{i1}b_{1j} + a_{i2}b_{2j} + \cdots + a_{in}b_{nj}`,
    condition: 'Số CỘT của ma trận đứng trước (A) phải BẰNG số HÀNG của ma trận đứng sau (B). Nếu A cấp m × n và B cấp n × p thì tích AB có cấp m × p.',
    theory: 'Phần tử c_{ij} ở hàng i, cột j của ma trận tích được tính bằng tích vô hướng giữa hàng i của ma trận A và cột j của ma trận B ("Hàng nhân Cột"). Phép nhân ma trận có tính kết hợp (AB)C = A(BC) và phân phối A(B + C) = AB + AC, nhưng KHÔNG CÓ TÍNH GIAO HOÁN: nhìn chung AB ≠ BA.',
    proof: 'Xuất phát từ phép hợp thành của hai ánh xạ tuyến tính T_A: ℝⁿ → ℝᵐ và T_B: ℝᵖ → ℝⁿ: ma trận của ánh xạ hợp T_A ∘ T_B chính là tích ma trận AB.',
    example: 'Cho $A = \\begin{pmatrix} 1 & 2 \\\\ 3 & 4 \\end{pmatrix}$ và $B = \\begin{pmatrix} 2 & 0 \\\\ 1 & 3 \\end{pmatrix}$. Tính ma trận tích $C = A \\cdot B$.',
    exampleSolution: '• Bước 1: Kiểm tra cấp: $A$ cấp $2\\times 2$, $B$ cấp $2\\times 2$ $\\implies$ tích $C$ có cấp $2\\times 2$.\n• Bước 2: Tính từng phần tử của $C$ bằng quy tắc "Hàng nhân Cột":\n  - $c_{11} = 1 \\times 2 + 2 \\times 1 = 2 + 2 = 4$\n  - $c_{12} = 1 \\times 0 + 2 \\times 3 = 0 + 6 = 6$\n  - $c_{21} = 3 \\times 2 + 4 \\times 1 = 6 + 4 = 10$\n  - $c_{22} = 3 \\times 0 + 4 \\times 3 = 0 + 12 = 12$\n• Bước 3: Thu được ma trận tích:\n  $$C = A \\cdot B = \\begin{pmatrix} 4 & 6 \\\\ 10 & 12 \\end{pmatrix}$$\n• Kết luận: $A \\cdot B = \\begin{pmatrix} 4 & 6 \\\\ 10 & 12 \\end{pmatrix}$.',
    tip: 'Để tính c_{ij}, hãy đặt ngón tay trái di chuyển dọc theo Hàng i của A, ngón tay phải di chuyển dọc theo Cột j của B, nhân từng cặp rồi cộng dồn lại.',
    mistake: 'Tự ý nhân từng phần tử tương ứng như phép cộng: a_{ij} × b_{ij}. Đây là phép nhân Hadamard, không phải phép nhân ma trận thông thường!',
    question: 'Cho A = [[1, 2]], B = [[3], [4]]. Tính giá trị phần tử duy nhất của ma trận tích A · B.',
    answer: 11,
    solution: 'A có cấp 1×2, B có cấp 2×1. Tích AB có cấp 1×1: 1×3 + 2×4 = 3 + 8 = 11.',
  },
  {
    id: 'mat-transpose',
    topic: 'matrices',
    name: 'Ma trận chuyển vị & ma trận đối xứng',
    latex: r`A^T = [a_{ji}]_{n\times m},\qquad (A + B)^T = A^T + B^T,\quad (AB)^T = B^T A^T`,
    condition: 'A là ma trận cấp m × n bất kỳ. Chuyển vị Aᵀ có cấp n × m. Ma trận đối xứng yêu cầu A là ma trận vuông thỏa Aᵀ = A.',
    theory: 'Ma trận chuyển vị Aᵀ nhận được bằng cách đổi các HÀNG của A thành các CỘT tương ứng (hàng i trở thành cột i). Tính chất quan trọng nhất: Chuyển vị của một tích ĐẢO NGƯỢC THỨ TỰ: (AB)ᵀ = Bᵀ Aᵀ. Ma trận vuông A được gọi là đối xứng nếu Aᵀ = A.',
    proof: 'Xét phần tử ở vị trí (i, j) của (AB)ᵀ: chính là phần tử (j, i) của AB, tức là ∑ₖ a_{jk}b_{ki} = ∑ₖ b_{ki}a_{jk} = ∑ₖ (Bᵀ)_{ik}(Aᵀ)_{kj}, chính là tích Bᵀ Aᵀ.',
    example: 'Tìm ma trận chuyển vị của $A = \\begin{pmatrix} 1 & 2 & 3 \\\\ 4 & 5 & 6 \\end{pmatrix}$.',
    exampleSolution: '• Bước 1: Xác định cấp của $A$: gồm 2 hàng và 3 cột ($2 \\times 3$).\n• Bước 2: Đổi từng hàng thành cột tương ứng:\n  - Hàng 1 $(1, 2, 3)$ biến thành Cột 1.\n  - Hàng 2 $(4, 5, 6)$ biến thành Cột 2.\n• Bước 3: Ghép lại thành ma trận $A^T$ cấp $3 \\times 2$:\n  $$A^T = \\begin{pmatrix} 1 & 4 \\\\ 2 & 5 \\\\ 3 & 6 \\end{pmatrix}$$\n• Kết luận: $A^T = \\begin{pmatrix} 1 & 4 \\\\ 2 & 5 \\\\ 3 & 6 \\end{pmatrix}$.',
    tip: 'Đường chéo chính của ma trận vuông giữ nguyên vị trí khi chuyển vị.',
    mistake: 'Quên đảo thứ tự khi chuyển vị tích: viết (AB)ᵀ = Aᵀ Bᵀ (sai!). Phải là Bᵀ Aᵀ.',
    question: 'Cho A = [[2, 5], [3, 7]]. Phần tử ở hàng 1 cột 2 của Aᵀ bằng bao nhiêu?',
    answer: 3,
    solution: 'Phần tử hàng 1 cột 2 của Aᵀ chính là phần tử hàng 2 cột 1 của A, tức là 3.',
  },
  {
    id: 'mat-determinant',
    topic: 'matrices',
    name: 'Định thức ma trận (Determinant)',
    latex: r`\det\begin{pmatrix} a & b \\ c & d \end{pmatrix} = ad - bc,\qquad \det(A_{3\times 3}) = a_{11}C_{11} + a_{12}C_{12} + a_{13}C_{13}`,
    condition: 'Chỉ ma trận VUÔNG (n × n) mới có định thức. Ký hiệu là det(A) hoặc |A|.',
    theory: 'Định thức là một giá trị vô hướng đặc trưng cho ma trận vuông. Ý nghĩa hình học: |det(A)| là hệ số co giãn thể tích/diện tích qua phép biến đổi tuyến tính A. Nếu det(A) ≠ 0 thì ma trận khả nghịch (không suy biến). Một số tính chất quan trọng: det(AB) = det(A) · det(B), det(Aᵀ) = det(A), det(kA) = kⁿ det(A) với ma trận cấp n.',
    proof: 'Với ma trận 2×2, diện tích hình bình hành sinh bởi hai vector (a,c) và (b,d) bằng |ad − bc|. Với cấp 3, quy tắc Sarrus hoặc khai triển Laplace theo hàng/cột bất kỳ đều cho cùng một kết quả duy nhất.',
    example: 'Tính định thức của $A = \\begin{pmatrix} 3 & 2 \\\\ 1 & 4 \\end{pmatrix}$ và ma trận tam giác $B = \\begin{pmatrix} 1 & 2 & 3 \\\\ 0 & 4 & 5 \\\\ 0 & 0 & 6 \\end{pmatrix}$.',
    exampleSolution: '• Tính $\\det(A)$ cấp 2: Áp dụng công thức $ad - bc$:\n  $$\\det(A) = \\begin{vmatrix} 3 & 2 \\\\ 1 & 4 \\end{vmatrix} = 3 \\times 4 - 2 \\times 1 = 12 - 2 = 10$$\n• Tính $\\det(B)$ cấp 3: $B$ là ma trận tam giác trên nên định thức bằng tích các phần tử đường chéo chính:\n  $$\\det(B) = 1 \\times 4 \\times 6 = 24$$\n• Kết luận: $\\det(A) = 10$ và $\\det(B) = 24$.',
    tip: 'Khi tính định thức cấp 3 trở lên, hãy chọn hàng hoặc cột chứa nhiều số 0 nhất để khai triển Laplace, phép tính sẽ đơn giản đi rất nhiều!',
    mistake: 'Nhầm công thức det(kA) = k det(A). Đúng phải là kⁿ det(A) với n là cấp của ma trận (mỗi hàng được nhân với k).',
    question: 'Tính định thức của ma trận A = [[5, 2], [3, 4]].',
    answer: 14,
    solution: 'det(A) = 5×4 − 2×3 = 20 − 6 = 14.',
  },
  {
    id: 'mat-inverse',
    topic: 'matrices',
    name: 'Ma trận nghịch đảo (Inverse Matrix)',
    latex: r`A^{-1} = \frac{1}{\det(A)} \operatorname{adj}(A),\qquad \begin{pmatrix} a & b \\ c & d \end{pmatrix}^{-1} = \frac{1}{ad-bc} \begin{pmatrix} d & -b \\ -c & a \end{pmatrix}`,
    condition: 'A là ma trận vuông và BẮT BUỘC det(A) ≠ 0 (ma trận không suy biến hay khả nghịch). Khi đó A · A⁻¹ = A⁻¹ · A = I.',
    theory: 'Ma trận nghịch đảo A⁻¹ đóng vai trò như nghịch đảo 1/a của số thực. Công thức ma trận 2×2: Đổi chỗ hai phần tử trên đường chéo chính (a và d), đổi dấu hai phần tử đường chéo phụ (b và c), rồi chia toàn bộ cho det(A) = ad − bc. Với cấp n, adj(A) = Cᵀ là ma trận chuyển vị của các phần bù đại số.',
    proof: 'Nhân trực tiếp [[a, b], [c, d]] với [[d, −b], [−c, a]]: ta thu được đường chéo chính là ad − bc và đường chéo phụ là 0. Chia cho ad − bc ra ma trận đơn vị I₂.',
    example: 'Tìm ma trận nghịch đảo của $A = \\begin{pmatrix} 2 & 1 \\\\ 5 & 3 \\end{pmatrix}$.',
    exampleSolution: '• Bước 1: Tính định thức $\\det(A)$:\n  $$\\det(A) = \\begin{vmatrix} 2 & 1 \\\\ 5 & 3 \\end{vmatrix} = 2 \\times 3 - 1 \\times 5 = 1 \\neq 0 \\implies \\text{A khả nghịch}$$\n• Bước 2: Lập ma trận phụ hợp $\\operatorname{adj}(A)$ (đổi chỗ chéo chính, đổi dấu chéo phụ):\n  $$\\operatorname{adj}(A) = \\begin{pmatrix} 3 & -1 \\\\ -5 & 2 \\end{pmatrix}$$\n• Bước 3: Nhân với $\\frac{1}{\\det(A)}$:\n  $$A^{-1} = \\frac{1}{1} \\begin{pmatrix} 3 & -1 \\\\ -5 & 2 \\end{pmatrix} = \\begin{pmatrix} 3 & -1 \\\\ -5 & 2 \\end{pmatrix}$$\n• Kiểm tra lại: $A \\cdot A^{-1} = \\begin{pmatrix} 1 & 0 \\\\ 0 & 1 \\end{pmatrix} = I_2$.\n• Kết luận: $A^{-1} = \\begin{pmatrix} 3 & -1 \\\\ -5 & 2 \\end{pmatrix}$.',
    tip: 'Nhớ đảo thứ tự khi nghịch đảo tích hai ma trận: (AB)⁻¹ = B⁻¹ A⁻¹.',
    mistake: 'Tìm nghịch đảo của ma trận có det(A) = 0. Khi det(A) = 0, ma trận không có nghịch đảo!',
    question: 'Cho A = [[4, 1], [3, 1]]. Tính phần tử ở hàng 1 cột 1 của ma trận nghịch đảo A⁻¹.',
    answer: 1,
    solution: 'det(A) = 4×1 − 1×3 = 1. Theo công thức, phần tử hàng 1 cột 1 của A⁻¹ là d/det(A) = 1/1 = 1.',
  },
  {
    id: 'mat-rank-gauss',
    topic: 'matrices',
    name: 'Hạng ma trận & phép khử Gauss',
    latex: r`\operatorname{rank}(A) = r \iff \text{Số hàng khác 0 của ma trận bậc thang sau phép khử Gauss}`,
    condition: 'Áp dụng cho mọi ma trận A cấp m × n. Phép biến đổi sơ cấp trên hàng: (1) Đổi chỗ 2 hàng; (2) Nhân một hàng với số k ≠ 0; (3) Cộng vào một hàng bội số của hàng khác.',
    theory: 'Hạng của ma trận rank(A) là số lượng vector hàng (hoặc vector cột) độc lập tuyến tính tối đa của A. Ba phép biến đổi sơ cấp trên dòng KHÔNG làm thay đổi hạng của ma trận. Bằng phương pháp khử Gauss, ta đưa ma trận về dạng bậc thang; khi đó hạng chính bằng số hàng khác 0. Luôn có rank(A) ≤ min(m, n).',
    proof: 'Các phép biến đổi sơ cấp tương ứng với việc nhân bên trái ma trận A với các ma trận sơ cấp khả nghịch E, bảo toàn không gian sinh bởi các hàng và hạng.',
    example: 'Tìm hạng của ma trận $A = \\begin{pmatrix} 1 & 2 & 3 \\\\ 2 & 4 & 6 \\\\ 0 & 1 & 1 \\end{pmatrix}$.',
    exampleSolution: '• Bước 1: Khử hàng 2 bằng phép biến đổi $h_2 \\to h_2 - 2h_1$:\n  $$\\begin{pmatrix} 1 & 2 & 3 \\\\ 2 & 4 & 6 \\\\ 0 & 1 & 1 \\end{pmatrix} \\xrightarrow{h_2 - 2h_1} \\begin{pmatrix} 1 & 2 & 3 \\\\ 0 & 0 & 0 \\\\ 0 & 1 & 1 \\end{pmatrix}$$\n• Bước 2: Đổi chỗ Hàng 2 và Hàng 3 ($h_2 \\leftrightarrow h_3$) để đưa hàng 0 xuống dưới cùng:\n  $$\\begin{pmatrix} 1 & 2 & 3 \\\\ 0 & 1 & 1 \\\\ 0 & 0 & 0 \\end{pmatrix}$$\n• Bước 3: Đếm số hàng khác không trong dạng bậc thang:\n  - Hàng 1 và Hàng 2 khác 0 (có 2 hàng khác 0).\n• Kết luận: $\\operatorname{rank}(A) = 2$.',
    tip: 'Nếu A là ma trận vuông cấp n: rank(A) = n khi và chỉ khi det(A) ≠ 0.',
    mistake: 'Đếm số hàng khác 0 trước khi đưa về dạng bậc thang. Phải hoàn thành phép khử Gauss mới được đếm!',
    question: 'Cho ma trận đơn vị I₄ cấp 4. Hạng của ma trận I₄ bằng bao nhiêu?',
    answer: 4,
    solution: 'Ma trận I₄ đã ở dạng bậc thang với 4 hàng đều khác 0 (độc lập tuyến tính), do đó rank(I₄) = 4.',
  },
  {
    id: 'mat-cramer-system',
    topic: 'matrices',
    name: 'Giải hệ phương trình bằng ma trận & Cramer',
    latex: r`AX = B \implies X = A^{-1}B,\qquad x_j = \frac{\det(A_j)}{\det(A)}`,
    condition: 'Áp dụng cho hệ n phương trình tuyến tính, n ẩn số khi ma trận hệ số A vuông và det(A) ≠ 0. Aⱼ là ma trận nhận được từ A khi thay cột j bằng cột hệ số tự do B.',
    theory: 'Một hệ phương trình tuyến tính có thể viết gọn dưới dạng ma trận AX = B. Nếu det(A) ≠ 0, hệ có nghiệm DUY NHẤT cho bởi X = A⁻¹B hoặc theo quy tắc Cramer: xⱼ = det(Aⱼ) / det(A).',
    proof: 'Từ AX = B, nhân cả hai vế bên trái với A⁻¹: A⁻¹(AX) = A⁻¹B ⇔ IX = A⁻¹B ⇔ X = A⁻¹B.',
    example: 'Giải hệ phương trình bằng ma trận và phương pháp Cramer: $\\begin{cases} 2x + y = 5 \\\\ x + 3y = 10 \\end{cases}$.',
    exampleSolution: '• Bước 1: Viết dưới dạng ma trận $AX = B$:\n  $$A = \\begin{pmatrix} 2 & 1 \\\\ 1 & 3 \\end{pmatrix},\\quad X = \\begin{pmatrix} x \\\\ y \\end{pmatrix},\\quad B = \\begin{pmatrix} 5 \\\\ 10 \\end{pmatrix}$$\n• Bước 2: Tính định thức ma trận hệ số $\\det(A)$:\n  $$\\det(A) = \\begin{vmatrix} 2 & 1 \\\\ 1 & 3 \\end{vmatrix} = 2 \\times 3 - 1 \\times 1 = 5 \\neq 0$$\n• Bước 3: Áp dụng phương pháp Cramer:\n  - Thay cột 1 bằng $B$: $\\det(A_1) = \\begin{vmatrix} 5 & 1 \\\\ 10 & 3 \\end{vmatrix} = 15 - 10 = 5 \\implies x = \\frac{5}{5} = 1$\n  - Thay cột 2 bằng $B$: $\\det(A_2) = \\begin{vmatrix} 2 & 5 \\\\ 1 & 10 \\end{vmatrix} = 20 - 5 = 15 \\implies y = \\frac{15}{5} = 3$\n• Kết luận: Nghiệm duy nhất của hệ là $(x, y) = (1, 3)$.',
    tip: 'Phương pháp ma trận nghịch đảo rất hữu hiệu khi giải nhiều hệ phương trình có cùng hệ số A.',
    mistake: 'Nhân A⁻¹ vào bên phải vế B: viết X = B · A⁻¹ (sai vì phép nhân ma trận không giao hoán).',
    question: 'Giải hệ x + y = 4 và 2x − y = 5. Tìm giá trị của nghiệm x.',
    answer: 3,
    solution: 'Cộng hai phương trình: 3x = 9 ⇒ x = 3 (thay lại y = 1).',
  },
  {
    id: 'mat-eigen',
    topic: 'matrices',
    name: 'Giá trị riêng & Vectơ riêng (Eigenvalues)',
    latex: r`Av = \lambda v \iff \det(A - \lambda I) = 0,\qquad \operatorname{tr}(A) = \sum \lambda_i,\quad \det(A) = \prod \lambda_i`,
    condition: 'A là ma trận vuông cấp n. Vectơ riêng v BẮT BUỘC là vectơ khác 0 (v ≠ 0). Số λ là giá trị riêng (có thể là số thực hoặc phức).',
    theory: 'Vectơ riêng v là vectơ mà khi nhân với ma trận A thì hướng của nó KHÔNG ĐỔI, chỉ bị co giãn theo tỉ lệ λ (gọi là giá trị riêng). Đa thức P(λ) = det(A − λI) được gọi là đa thức đặc trưng của A. Hai tính chất vàng: Tổng các giá trị riêng bằng VẾT ma trận (tr(A)), và Tích các giá trị riêng bằng ĐỊNH THỨC của ma trận (det(A)).',
    proof: 'Phương trình Av = λv tương đương với (A − λI)v = 0. Để hệ thuần nhất có nghiệm không tầm thường v ≠ 0, bắt buộc det(A − λI) = 0.',
    example: 'Tìm các giá trị riêng của ma trận $A = \\begin{pmatrix} 4 & 1 \\\\ 2 & 3 \\end{pmatrix}$.',
    exampleSolution: '• Bước 1: Lập phương trình đặc trưng $\\det(A - \\lambda I) = 0$:\n  $$\\det\\begin{pmatrix} 4 - \\lambda & 1 \\\\ 2 & 3 - \\lambda \\end{pmatrix} = 0$$\n• Bước 2: Khai triển định thức:\n  $$(4 - \\lambda)(3 - \\lambda) - 1 \\times 2 = \\lambda^2 - 7\\lambda + 10 = 0$$\n• Bước 3: Giải phương trình bậc hai $\\lambda^2 - 7\\lambda + 10 = 0$:\n  - Phân tích: $(\\lambda - 5)(\\lambda - 2) = 0 \\implies \\lambda_1 = 5,\\ \\lambda_2 = 2$\n• Kiểm tra tính chất:\n  - Tổng: $\\lambda_1 + \\lambda_2 = 5 + 2 = 7 = \\operatorname{tr}(A) = 4 + 3$\n  - Tích: $\\lambda_1 \\times \\lambda_2 = 5 \\times 2 = 10 = \\det(A) = 4\\times 3 - 1\\times 2$\n• Kết luận: Hai giá trị riêng của ma trận là $\\lambda_1 = 5$ và $\\lambda_2 = 2$.',
    tip: 'Giá trị riêng và vectơ riêng là trái tim của thuật toán PageRank của Google, nén dữ liệu PCA, và phân tích dao động cơ học trong kỹ thuật.',
    mistake: 'Coi vector 0 là vectơ riêng. Theo định nghĩa, vectơ riêng phải khác 0!',
    question: 'Cho ma trận A = [[3, 1], [0, 2]]. Giá trị riêng lớn hơn của A bằng bao nhiêu?',
    answer: 3,
    solution: 'A là ma trận tam giác trên, các giá trị riêng chính là các phần tử trên đường chéo chính: λ₁ = 3, λ₂ = 2. Giá trị lớn hơn là 3.',
  },
];
