import type {Topic,Formula} from './content';

export const modernMathTopics: Topic[] = [
  {
    id: 'probability',
    name: 'Xác suất & Thống kê',
    description: 'Quy tắc đếm, xác suất có điều kiện, định lý Bayes, kỳ vọng và phân phối xác suất',
    symbol: 'P(A|B) · σ',
    color: 'orange',
    level: 'THPT & Đại học',
  },
  {
    id: 'vectors',
    name: 'Vectơ & Tọa độ Oxyz',
    description: 'Tích có hướng, khoảng cách, phương trình mặt phẳng và đường thẳng trong không gian',
    symbol: '[u, v] · d(M,P)',
    color: 'purple',
    level: 'THPT',
  },
];

const r = String.raw;

export const modernMathFormulas: Formula[] = [
  {
    id: 'prob-counting',
    topic: 'probability',
    name: 'Hoán vị, Chỉnh hợp & Tổ hợp',
    latex: r`P_n = n!,\qquad A_n^k = \frac{n!}{(n-k)!},\qquad C_n^k = \binom{n}{k} = \frac{n!}{k!(n-k)!}`,
    condition: 'n, k là các số tự nhiên với 0 ≤ k ≤ n. Quy ước 0! = 1.',
    theory: 'Ba công cụ đếm cơ bản: (1) Hoán vị Pₙ: số cách sắp xếp thứ tự n phần tử khác nhau; (2) Chỉnh hợp Aₙᵏ: số cách chọn k phần tử từ n phần tử CÓ XÉT THỨ TỰ; (3) Tổ hợp Cₙᵏ: số cách chọn k phần tử từ n phần tử KHÔNG XÉT THỨ TỰ (tập hợp con). Tính chất tổ hợp: Cₙᵏ = Cₙⁿ⁻ᵏ, Cₙᵏ + Cₙᵏ⁺¹ = Cₙ₊₁ᵏ⁺¹ (tam giác Pascal).',
    proof: 'Chọn phần tử thứ 1 có n cách, thứ 2 có n-1 cách, ..., thứ k có n-k+1 cách. Tích là n!/(n-k)!. Với tổ hợp, do không xét thứ tự nên chia cho k! cách sắp xếp nội bộ k phần tử đó.',
    example: 'Từ một nhóm gồm 5 người, có bao nhiêu cách chọn ra một ban quản trị gồm 3 người (không phân biệt chức vụ)?',
    exampleSolution: '• Bước 1: Phân tích bài toán:\n  - Tổng số người là n = 5.\n  - Cần chọn ra k = 3 người.\n  - Vì không phân biệt chức vụ giữa 3 người được chọn nên thứ tự chọn không quan trọng.\n• Bước 2: Nhận diện công thức: Áp dụng công thức TỔ HỢP Cₙᵏ với n = 5, k = 3:\n  C₅³ = 5! / [3!(5 − 3)!] = 5! / (3! × 2!).\n• Bước 3: Rút gọn và tính toán:\n  C₅³ = (5 × 4 × 3!) / (3! × 2 × 1) = (5 × 4) / 2 = 20 / 2 = 10.\n• Kết luận: Có 10 cách chọn ban quản trị gồm 3 người.',
    tip: 'Để phân biệt Chỉnh hợp hay Tổ hợp: hãy tự hỏi "Đổi chỗ 2 người được chọn thì kết quả có tạo thành cách mới không?". Nếu CÓ đổi là CHỈNH HỢP (ví dụ Chủ tịch, Phó chủ tịch); nếu KHÔNG đổi là TỔ HỢP.',
    mistake: 'Dùng Chỉnh hợp Aₙᵏ khi bài toán chỉ yêu cầu chọn một tập hợp con không phân biệt vị trí.',
    question: 'Tính giá trị của tổ hợp C₆².',
    answer: 15,
    solution: 'C₆² = 6! / (2! 4!) = (6 × 5) / 2 = 15.',
  },
  {
    id: 'prob-rules',
    topic: 'probability',
    name: 'Quy tắc cộng & nhân xác suất',
    latex: r`P(A \cup B) = P(A) + P(B) - P(A \cap B),\qquad P(A \cap B) = P(A) \cdot P(B) \text{ (khi độc lập)}`,
    condition: 'A và B là hai biến cố trong cùng một không gian mẫu. Nếu A và B xung khắc (A ∩ B = ∅) thì P(A ∩ B) = 0.',
    theory: 'Xác suất của hợp hai biến cố bằng tổng xác suất trừ đi xác suất phần giao (tránh đếm lặp hai lần). Hai biến cố được gọi là độc lập nếu việc xảy ra hay không xảy ra của biến cố này không ảnh hưởng đến xác suất của biến cố kia; khi đó xác suất đồng thời bằng tích hai xác suất. Biến cố đối: P(Ā) = 1 − P(A).',
    proof: 'Dựa trên nguyên lý bù trừ trong lý thuyết tập hợp: |A ∪ B| = |A| + |B| − |A ∩ B|, chia cả hai vế cho kích thước không gian mẫu |Ω|.',
    example: 'Gieo một con xúc xắc cân đối. Tính xác suất để số chấm xuất hiện là số chẵn HOẶC là số chia hết cho 3.',
    exampleSolution: '• Bước 1: Xác định không gian mẫu: Ω = {1, 2, 3, 4, 5, 6} có |Ω| = 6.\n• Bước 2: Gọi A là biến cố "xuất hiện số chẵn": A = {2, 4, 6} ⇒ P(A) = 3/6.\n• Bước 3: Gọi B là biến cố "xuất hiện số chia hết cho 3": B = {3, 6} ⇒ P(B) = 2/6.\n• Bước 4: Phần giao A ∩ B là biến cố "vừa chẵn vừa chia hết cho 3": A ∩ B = {6} ⇒ P(A ∩ B) = 1/6.\n• Bước 5: Áp dụng quy tắc cộng xác suất:\n  P(A ∪ B) = P(A) + P(B) − P(A ∩ B) = 3/6 + 2/6 − 1/6 = 4/6 = 2/3.\n• Kết luận: Xác suất cần tìm là 2/3 (xấp xỉ 0.667).',
    tip: 'Khi bài toán có chữ "ít nhất một lần", hãy nghĩ ngay đến biến cố đối: P(ít nhất 1) = 1 − P(không lần nào).',
    mistake: 'Cộng trực tiếp P(A) + P(B) khi hai biến cố không xung khắc (bị đếm lặp phần giao).',
    question: 'Tung 2 đồng xu độc lập. Xác suất để cả hai đồng xu cùng xuất hiện mặt ngửa bằng bao nhiêu phần trăm?',
    answer: 25,
    solution: 'Hai đồng xu độc lập, P(Ngửa) = 0.5. Xác suất cả hai cùng ngửa = 0.5 × 0.5 = 0.25 (25%).',
  },
  {
    id: 'prob-bayes',
    topic: 'probability',
    name: 'Xác suất có điều kiện & Định lý Bayes',
    latex: r`P(A|B) = \frac{P(A \cap B)}{P(B)} = \frac{P(B|A)P(A)}{P(B)},\qquad P(B) = \sum_{i=1}^n P(B|A_i)P(A_i)`,
    condition: 'P(B) > 0. {A₁, A₂, ..., Aₙ} là một hệ đầy đủ các biến cố rời nhau từng đôi.',
    theory: 'P(A|B) là xác suất để biến cố A xảy ra khi BIẾT RẰNG biến cố B đã xảy ra. Định lý Bayes cho phép ta "lật ngược" điều kiện: từ xác suất tiên nghiệm P(A) và khả năng P(B|A), ta tính được xác suất hậu nghiệm P(A|B) sau khi quan sát thấy bằng chứng B. Đây là nền tảng của trí tuệ nhân tạo (Machine Learning, bộ lọc Spam, chẩn đoán y khoa).',
    proof: 'Theo định nghĩa: P(A ∩ B) = P(A|B)P(B) = P(B|A)P(A). Chia cả hai vế cho P(B) ta được công thức Bayes.',
    example: 'Một căn bệnh hiếm gặp có tỉ lệ mắc 1% dân số (P(Bệnh) = 0.01). Xét nghiệm có độ chính xác 90% (P(Dương tính|Bệnh) = 0.9) nhưng cũng có 5% dương tính giả ở người khỏe (P(Dương tính|Khỏe) = 0.05). Nếu một người có kết quả xét nghiệm dương tính, xác suất thực sự mắc bệnh là bao nhiêu?',
    exampleSolution: '• Bước 1: Liệt kê các giả thiết:\n  - P(B) = 0.01 ⇒ P(K) = 1 − 0.01 = 0.99 (K là người khỏe mạnh).\n  - P(+|B) = 0.90.\n  - P(+|K) = 0.05.\n• Bước 2: Tính xác suất toàn phần để một người có kết quả dương tính P(+):\n  P(+) = P(+|B)P(B) + P(+|K)P(K)\n  = 0.90 × 0.01 + 0.05 × 0.99 = 0.009 + 0.0495 = 0.0585.\n• Bước 3: Áp dụng định lý Bayes để tính P(B|+):\n  P(B|+) = [P(+|B) × P(B)] / P(+) = 0.009 / 0.0585 ≈ 0.1538 (khoảng 15.4%).\n• Kết luận: Dù xét nghiệm dương tính, xác suất thực sự mắc bệnh chỉ khoảng 15.4% do bệnh rất hiếm và có dương tính giả!',
    tip: 'Định lý Bayes nhắc nhở chúng ta: đừng bao giờ bỏ qua "xác suất nền tảng" (Base Rate Fallacy).',
    mistake: 'Nhầm lẫn giữa P(A|B) và P(B|A). Xác suất "Có bệnh thì xét nghiệm dương tính" khác hoàn toàn với "Xét nghiệm dương tính thì có bệnh".',
    question: 'Cho P(A) = 0.4, P(B) = 0.5 và P(A ∩ B) = 0.2. Tính xác suất có điều kiện P(A|B).',
    answer: 0.4,
    solution: 'P(A|B) = P(A ∩ B) / P(B) = 0.2 / 0.5 = 0.4.',
  },
  {
    id: 'prob-stats',
    topic: 'probability',
    name: 'Kỳ vọng, Phương sai & Độ lệch chuẩn',
    latex: r`E[X] = \mu = \sum x_i p_i,\qquad \operatorname{Var}(X) = \sigma^2 = E[X^2] - (E[X])^2,\quad \sigma = \sqrt{\operatorname{Var}(X)}`,
    condition: 'X là biến ngẫu nhiên rời rạc có bảng phân phối xác suất với ∑ pᵢ = 1, pᵢ ≥ 0.',
    theory: 'Kỳ vọng E[X] (giá trị trung bình) thể hiện xu hướng trung tâm của biến ngẫu nhiên. Phương sai Var(X) và Độ lệch chuẩn σ đo lường mức độ phân tán hoặc rủi ro của các giá trị quanh kỳ vọng. Công thức tính nhanh phương sai: Var(X) = E[X²] − (E[X])² (kỳ vọng bình phương trừ bình phương kỳ vọng). Tính chất: E[aX + b] = aE[X] + b, Var(aX + b) = a² Var(X).',
    proof: 'Var(X) = E[(X − μ)²] = E[X² − 2μX + μ²] = E[X²] − 2μE[X] + μ² = E[X²] − 2μ² + μ² = E[X²] − μ².',
    example: 'Cho biến ngẫu nhiên X là số chấm khi gieo một con xúc xắc cân đối. Tính kỳ vọng E[X].',
    exampleSolution: '• Bước 1: Lập bảng phân phối xác suất của X:\n  X nhận các giá trị xᵢ ∈ {1, 2, 3, 4, 5, 6}, mỗi giá trị có xác suất pᵢ = 1/6.\n• Bước 2: Áp dụng công thức tính kỳ vọng E[X] = ∑ xᵢ pᵢ:\n  E[X] = 1×(1/6) + 2×(1/6) + 3×(1/6) + 4×(1/6) + 5×(1/6) + 6×(1/6)\n• Bước 3: Tính toán:\n  E[X] = (1 + 2 + 3 + 4 + 5 + 6) / 6 = 21 / 6 = 3.5.\n• Kết luận: Kỳ vọng số chấm xuất hiện là 3.5.',
    tip: 'Phương sai luôn luôn không âm (Var(X) ≥ 0). Nếu tính ra phương sai âm thì chắc chắn bạn đã tính nhầm ở bước nào đó!',
    mistake: 'Quên bình phương a khi tính phương sai của aX: viết Var(aX) = a Var(X) (sai!). Phải là a² Var(X).',
    question: 'Cho biến ngẫu nhiên X có E[X] = 3 và E[X²] = 13. Tính phương sai Var(X).',
    answer: 4,
    solution: 'Var(X) = E[X²] − (E[X])² = 13 − 3² = 13 − 9 = 4.',
  },
  {
    id: 'prob-normal',
    topic: 'probability',
    name: 'Phân phối nhị thức & Phân phối chuẩn Gauss',
    latex: r`P(X = k) = \binom{n}{k} p^k (1-p)^{n-k},\qquad f(x) = \frac{1}{\sigma\sqrt{2\pi}} e^{-\frac{(x-\mu)^2}{2\sigma^2}}`,
    condition: 'Nhị thức: n phép thử Bernoulli độc lập, xác suất thành công p cố định. Phân phối chuẩn: biến ngẫu nhiên liên tục x ∈ ℝ, σ > 0.',
    theory: 'Phân phối nhị thức B(n, p) có kỳ vọng E[X] = np, phương sai Var(X) = np(1−p). Khi n lớn, theo Định lý giới hạn trung tâm (CLT), phân phối nhị thức xấp xỉ phân phối chuẩn Gauss N(μ, σ²). Đồ thị hàm mật độ Gauss có hình quả chuông đối xứng qua μ. Quy tắc thực nghiệm 3-sigma (68-95-99.7): Khoảng [μ − σ, μ + σ] chứa 68.27% dữ liệu; [μ − 2σ, μ + 2σ] chứa 95.45%; [μ − 3σ, μ + 3σ] chứa 99.73%.',
    proof: 'Tích phân toàn bộ hàm mật độ Gauss trên (−∞, ∞) bằng 1 nhờ đổi sang tọa độ cực trong tích phân Poisson.',
    example: 'Gieo một đồng xu cân đối 4 lần (p = 0.5). Tính xác suất để được đúng 2 lần ngửa.',
    exampleSolution: '• Bước 1: Xác định các tham số phân phối nhị thức:\n  - Số phép thử n = 4.\n  - Số lần thành công cần đạt k = 2.\n  - Xác suất thành công mỗi lần p = 0.5 ⇒ 1 − p = 0.5.\n• Bước 2: Áp dụng công thức phân phối nhị thức:\n  P(X = 2) = C₄² × (0.5)² × (0.5)⁴⁻² = C₄² × (0.5)⁴.\n• Bước 3: Tính toán các giá trị số:\n  C₄² = (4 × 3) / 2 = 6.\n  (0.5)⁴ = 1 / 16 = 0.0625.\n  P(X = 2) = 6 × (1 / 16) = 6 / 16 = 3 / 8 = 0.375 (37.5%).\n• Kết luận: Xác suất xuất hiện đúng 2 mặt ngửa là 37.5%.',
    tip: 'Chuẩn hóa biến ngẫu nhiên: Z = (X − μ) / σ đưa bất kỳ phân phối chuẩn nào về phân phối chuẩn tắc N(0, 1) để tra bảng xác suất.',
    mistake: 'Dùng công thức nhị thức khi các phép thử phụ thuộc nhau (ví dụ rút thăm không hoàn lại). Phải dùng phân phối siêu bội!',
    question: 'Tính kỳ vọng của phân phối nhị thức B(n = 100, p = 0.2).',
    answer: 20,
    solution: 'E[X] = n × p = 100 × 0.2 = 20.',
  },
  {
    id: 'vec-dot-product',
    topic: 'vectors',
    name: 'Tọa độ vectơ & Tích vô hướng trong Oxyz',
    latex: r`\vec{u} \cdot \vec{v} = x_1 x_2 + y_1 y_2 + z_1 z_2 = |\vec{u}| |\vec{v}| \cos\theta,\qquad |\vec{u}| = \sqrt{x^2 + y^2 + z^2}`,
    condition: 'u⃗ = (x₁, y₁, z₁), v⃗ = (x₂, y₂, z₂) là các vectơ trong không gian Oxyz. Góc θ ∈ [0, π].',
    theory: 'Tích vô hướng của hai vectơ là một SỐ THỰC. Hai vectơ vuông góc với nhau khi và chỉ khi tích vô hướng của chúng bằng 0: u⃗ ⊥ v⃗ ⇔ u⃗ · v⃗ = 0 (x₁x₂ + y₁y₂ + z₁z₂ = 0). Độ dài của vectơ là khoảng cách từ gốc O đến điểm (x, y, z). Khoảng cách giữa hai điểm A(x_A, y_A, z_A) và B(x_B, y_B, z_B) là AB = √[(x_B − x_A)² + (y_B − y_A)² + (z_B − z_A)²].',
    proof: 'Dựa trên định lý cosin trong tam giác OAB: AB² = OA² + OB² − 2·OA·OB·cosθ, khai triển theo tọa độ và thu gọn.',
    example: 'Cho hai vectơ u⃗ = (1, 2, 2) và v⃗ = (2, -1, 3). Tính độ dài của u⃗ và tích vô hướng u⃗ · v⃗.',
    exampleSolution: '• Bước 1: Tính độ dài của vectơ u⃗:\n  |u⃗| = √(x² + y² + z²) = √(1² + 2² + 2²) = √(1 + 4 + 4) = √9 = 3.\n• Bước 2: Tính tích vô hướng u⃗ · v⃗ theo tọa độ:\n  u⃗ · v⃗ = x₁x₂ + y₁y₂ + z₁z₂\n  = 1×2 + 2×(-1) + 2×3\n  = 2 − 2 + 6 = 6.\n• Kết luận: Độ dài |u⃗| = 3 và tích vô hướng u⃗ · v⃗ = 6.',
    tip: 'Để tìm góc giữa hai vectơ, dùng công thức cosθ = (u⃗ · v⃗) / (|u⃗| |v⃗|). Nếu tích vô hướng dương: góc nhọn; âm: góc tù; bằng 0: góc vuông.',
    mistake: 'Nhầm kết quả của tích vô hướng là một vectơ. Tích vô hướng luôn là một SỐ thực!',
    question: 'Cho u⃗ = (3, 4, 0). Độ dài của vectơ u⃗ bằng bao nhiêu?',
    answer: 5,
    solution: '|u⃗| = √(3² + 4² + 0²) = √25 = 5.',
  },
  {
    id: 'vec-cross-product',
    topic: 'vectors',
    name: 'Tích có hướng (Cross Product) trong không gian',
    latex: r`[\vec{u}, \vec{v}] = \left( \begin{vmatrix} y_1 & z_1 \\ y_2 & z_2 \end{vmatrix}, \begin{vmatrix} z_1 & x_1 \\ z_2 & x_2 \end{vmatrix}, \begin{vmatrix} x_1 & y_1 \\ x_2 & y_2 \end{vmatrix} \right),\qquad S_{\triangle} = \frac{1}{2}|[\vec{u}, \vec{v}]|`,
    condition: 'Chỉ định nghĩa trong KHÔNG GIAN 3 CHIỀU (ℝ³).',
    theory: 'Tích có hướng của hai vectơ u⃗ và v⃗ là một VECTƠ vuông góc với CẢ HAI vectơ u⃗ và v⃗ (tuân theo quy tắc bàn tay phải). Độ lớn của tích có hướng |[u⃗, v⃗]| = |u⃗||v⃗|sinθ chính là DIỆN TÍCH của hình bình hành dựng bởi u⃗ và v⃗. Ứng dụng: Diện tích tam giác ABC = (1/2)|[AB⃗, AC⃗]|; Thể tích tứ diện ABCD = (1/6)|[AB⃗, AC⃗] · AD⃗|; Ba vectơ đồng phẳng khi và chỉ khi [u⃗, v⃗] · w⃗ = 0.',
    proof: 'Khai triển định thức hình thức i⃗(y₁z₂ − z₁y₂) − j⃗(x₁z₂ − z₁x₂) + k⃗(x₁y₂ − y₁x₂) và kiểm tra trực tiếp tính vuông góc với u⃗ và v⃗ bằng tích vô hướng.',
    example: 'Cho u⃗ = (1, 0, 0) và v⃗ = (0, 1, 0). Tính tích có hướng [u⃗, v⃗].',
    exampleSolution: '• Bước 1: Nhận diện hai vectơ: u⃗ là vectơ đơn vị i⃗ trên trục Ox, v⃗ là vectơ đơn vị j⃗ trên trục Oy.\n• Bước 2: Tính từng tọa độ của vectơ tích có hướng [u⃗, v⃗]:\n  - Tọa độ x: y₁z₂ − z₁y₂ = 0×0 − 0×1 = 0.\n  - Tọa độ y: z₁x₂ − x₁z₂ = 0×0 − 1×0 = 0.\n  - Tọa độ z: x₁y₂ − y₁x₂ = 1×1 − 0×0 = 1.\n• Bước 3: Thu được vectơ: [u⃗, v⃗] = (0, 0, 1) chính là vectơ đơn vị k⃗ trên trục Oz.\n• Kết luận: [u⃗, v⃗] = (0, 0, 1).',
    tip: 'Tích có hướng phản giao hoán: [v⃗, u⃗] = −[u⃗, v⃗]. Đổi thứ tự hai vectơ sẽ làm đổi chiều vectơ tích.',
    mistake: 'Áp dụng tích có hướng cho vectơ 2 chiều trong mặt phẳng Oxy. Tích có hướng chỉ định nghĩa trong không gian 3 chiều!',
    question: 'Cho hai vectơ u⃗, v⃗ vuông góc có độ dài |u⃗| = 3, |v⃗| = 4. Độ dài của vectơ tích có hướng |[u⃗, v⃗]| bằng bao nhiêu?',
    answer: 12,
    solution: 'Vì vuông góc nên sinθ = sin(90°) = 1. Độ dài = |u⃗| |v⃗| sinθ = 3 × 4 × 1 = 12.',
  },
  {
    id: 'vec-plane-distance',
    topic: 'vectors',
    name: 'Phương trình mặt phẳng & khoảng cách',
    latex: r`Ax + By + Cz + D = 0,\qquad d(M_0, (\alpha)) = \frac{|Ax_0 + By_0 + Cz_0 + D|}{\sqrt{A^2 + B^2 + C^2}}`,
    condition: 'A, B, C không đồng thời bằng 0 (A² + B² + C² > 0). n⃗ = (A, B, C) là một vectơ pháp tuyến của mặt phẳng.',
    theory: 'Mặt phẳng đi qua điểm M₁(x₁, y₁, z₁) và nhận n⃗ = (A, B, C) làm vectơ pháp tuyến có phương trình: A(x − x₁) + B(y − y₁) + C(z − z₁) = 0. Khai triển rút gọn thành Ax + By + Cz + D = 0 với D = −(Ax₁ + By₁ + Cz₁). Công thức khoảng cách đo đoạn vuông góc hạ từ điểm M₀(x₀, y₀, z₀) xuống mặt phẳng.',
    proof: 'Hình chiếu vuông góc của đoạn M₁M₀ lên vectơ pháp tuyến n⃗ bằng |M₁M₀⃗ · n⃗| / |n⃗|. Khai triển tọa độ cho ra công thức.',
    example: 'Viết phương trình mặt phẳng (P) đi qua điểm M(1, 2, 3) nhận vectơ pháp tuyến n⃗ = (2, -1, 4), và tính khoảng cách từ gốc tọa độ O(0, 0, 0) đến (P).',
    exampleSolution: '• Bước 1: Viết phương trình mặt phẳng (P):\n  A(x − x₀) + B(y − y₀) + C(z − z₀) = 0\n  ⇔ 2(x − 1) − 1(y − 2) + 4(z − 3) = 0\n  ⇔ 2x − 2 − y + 2 + 4z − 12 = 0\n  ⇔ 2x − y + 4z − 12 = 0.\n• Bước 2: Tính khoảng cách từ O(0, 0, 0) đến (P):\n  d(O, (P)) = |2(0) − (0) + 4(0) − 12| / √(2² + (-1)² + 4²)\n  = |-12| / √(4 + 1 + 16) = 12 / √21.\n• Kết luận: Phương trình là 2x − y + 4z − 12 = 0 và d(O, (P)) = 12 / √21.',
    tip: 'Nếu biết hai vectơ chỉ phương không cùng phương u⃗ và v⃗ nằm trong mặt phẳng, vectơ pháp tuyến n⃗ chính là tích có hướng [u⃗, v⃗].',
    mistake: 'Quên dấu giá trị tuyệt đối trên tử số khi tính khoảng cách (khoảng cách hình học luôn là số không âm!).',
    question: 'Khoảng cách từ điểm M(1, 0, 2) đến mặt phẳng (P): 2x + 2y − z + 3 = 0 bằng bao nhiêu?',
    answer: 1,
    solution: 'd = |2(1) + 2(0) − (2) + 3| / √(2² + 2² + (-1)²) = |3| / √9 = 3 / 3 = 1.',
  },
  {
    id: 'vec-line-space',
    topic: 'vectors',
    name: 'Phương trình đường thẳng trong không gian Oxyz',
    latex: r`\frac{x - x_0}{a} = \frac{y - y_0}{b} = \frac{z - z_0}{c} = t \iff \begin{cases} x = x_0 + at \\ y = y_0 + bt \\ z = z_0 + ct \end{cases}`,
    condition: 'u⃗ = (a, b, c) là vectơ chỉ phương của đường thẳng (a² + b² + c² > 0). Phương trình chính tắc yêu cầu a, b, c đều khác 0.',
    theory: 'Đường thẳng d đi qua điểm M₀(x₀, y₀, z₀) và có vectơ chỉ phương u⃗ = (a, b, c) bao gồm tập hợp các điểm M(x, y, z) sao cho M₀M⃗ cùng phương với u⃗ (tức M₀M⃗ = t · u⃗ với tham số t ∈ ℝ). Vị trí tương đối giữa hai đường thẳng trong không gian: Cắt nhau, Song song, Trùng nhau, hoặc Chéo nhau (không cùng nằm trên một mặt phẳng).',
    proof: 'Từ M₀M⃗ = (x − x₀, y − y₀, z − z₀) = t(a, b, c), cân bằng từng tọa độ ta thu được ngay hệ phương trình tham số.',
    example: 'Viết phương trình tham số của đường thẳng d đi qua điểm M(1, -2, 3) và có vectơ chỉ phương u⃗ = (2, 3, -1).',
    exampleSolution: '• Bước 1: Xác định điểm đi qua M₀(x₀, y₀, z₀) = (1, -2, 3).\n• Bước 2: Xác định vectơ chỉ phương u⃗ = (a, b, c) = (2, 3, -1).\n• Bước 3: Viết hệ phương trình tham số theo công thức:\n  - x = x₀ + at = 1 + 2t\n  - y = y₀ + bt = -2 + 3t\n  - z = z₀ + ct = 3 − t\n  (với t ∈ ℝ).\n• Kết luận: Phương trình tham số của đường thẳng là x = 1 + 2t; y = -2 + 3t; z = 3 − t (t ∈ ℝ).',
    tip: 'Để tìm tọa độ một điểm thuộc đường thẳng, chỉ cần cho một giá trị t bất kỳ (ví dụ t = 0 được M₀, t = 1 được điểm tiếp theo).',
    mistake: 'Nhầm lẫn giữa vectơ pháp tuyến của mặt phẳng và vectơ chỉ phương của đường thẳng khi xét bài toán vuông góc hay song song.',
    question: 'Đường thẳng d: (x-1)/2 = (y+1)/3 = (z-4)/(-1) có vectơ chỉ phương u⃗ = (2, 3, c). Giá trị của c bằng bao nhiêu?',
    answer: -1,
    solution: 'Nhìn trực tiếp ở mẫu số tương ứng với z: c = -1.',
  },
];
