import type {Topic, Formula} from './content';

export const trigonometryTopics: Topic[] = [
  {
    id: 'trigonometry',
    name: 'Lượng giác toàn diện',
    description: 'Hệ thức cơ bản, công thức cộng, nhân đôi, hạ bậc, biến đổi tổng–tích và phương trình lượng giác',
    symbol: 'sin²x + cos²x = 1',
    color: 'blue',
    level: 'THPT & Đại học',
  },
];

const r = String.raw;

export const trigonometryFormulas: Formula[] = [
  {
    id: 'trig-basic',
    topic: 'trigonometry',
    name: 'Hệ thức lượng giác cơ bản & Giá trị góc đặc biệt',
    latex: r`\sin^2 x + \cos^2 x = 1,\quad 1 + \tan^2 x = \frac{1}{\cos^2 x},\quad 1 + \cot^2 x = \frac{1}{\sin^2 x},\quad \tan x \cdot \cot x = 1`,
    condition: 'tan x xác định khi x ≠ π/2 + kπ; cot x xác định khi x ≠ kπ (k ∈ ℤ).',
    theory: 'Trên đường tròn lượng giác đơn vị (bán kính R = 1), tọa độ điểm M ứng với góc x là (cos x, sin x). Do x² + y² = 1 nên sin²x + cos²x = 1 với mọi số thực x. Chia hai vế cho cos²x (≠ 0) ta được 1 + tan²x = 1/cos²x; chia cho sin²x (≠ 0) được 1 + cot²x = 1/sin²x. Giá trị dấu của sin, cos, tan, cot tuân theo quy tắc góc phần tư: "Nhất cả (I: all +), Nhì sin (II: sin +), Tam tang (III: tan & cot +), Tứ cos (IV: cos +)".',
    proof: 'Dựa trên định lý Pythagoras trong tam giác vuông tạo bởi hình chiếu của điểm M lên hai trục tọa độ Ox và Oy trên đường tròn lượng giác đơn vị.',
    example: 'Cho góc x thỏa mãn sin x = 3/5 và x thuộc góc phần tư thứ II (π/2 < x < π). Tính cos x và tan x.',
    exampleSolution: '• Bước 1: Áp dụng hệ thức cơ bản sin²x + cos²x = 1:\n  cos²x = 1 − sin²x = 1 − (3/5)² = 1 − 9/25 = 16/25.\n• Bước 2: Xác định dấu của cos x theo góc phần tư:\n  Vì π/2 < x < π (góc phần tư thứ II), trục hoành âm nên cos x < 0.\n  ⇒ cos x = −√(16/25) = −4/5.\n• Bước 3: Tính tan x:\n  tan x = sin x / cos x = (3/5) / (−4/5) = −3/4.\n• Kết luận: cos x = −4/5 và tan x = −3/4.',
    tip: 'Luôn kiểm tra góc phần tư trước khi khai căn để lấy đúng dấu (+) hoặc (−) của cos và sin.',
    mistake: 'Quên xét góc phần tư và luôn mặc định cos x > 0 khi khai căn cos²x.',
    question: 'Cho cos x = 0.6 và x thuộc góc phần tư thứ IV. Tính sin²x.',
    answer: 0.64,
    solution: 'sin²x = 1 − cos²x = 1 − 0.6² = 1 − 0.36 = 0.64.',
  },
  {
    id: 'trig-addition',
    topic: 'trigonometry',
    name: 'Công thức cộng lượng giác',
    latex: r`\begin{aligned}\sin(a \pm b) &= \sin a \cos b \pm \cos a \sin b\\\cos(a \pm b) &= \cos a \cos b \mp \sin a \sin b\\\tan(a \pm b) &= \frac{\tan a \pm \tan b}{1 \mp \tan a \tan b}\end{aligned}`,
    condition: 'Các góc a, b, a±b thỏa mãn điều kiện tồn tại của hàm tan tương ứng (mẫu số 1 ∓ tan a tan b ≠ 0).',
    theory: 'Công thức cộng cho phép tính giá trị lượng giác của tổng hoặc hiệu hai góc thông qua các góc thành phần. Đây là nguồn gốc để suy ra toàn bộ công thức nhân đôi, nhân ba và biến đổi tích–tổng. Thơ vui nhớ công thức: "Sin thì sin cos cos sin; Cos thì cos cos sin sin coi chừng (ngược dấu); Tang tổng thì lấy tổng tang, chia một trừ tích tang tang rõ ràng".',
    proof: 'Xét hai vectơ đơn vị trên đường tròn lượng giác u⃗ = (cos a, sin a) và v⃗ = (cos b, sin b). Tích vô hướng u⃗ · v⃗ = cos a cos b + sin a sin b = |u⃗||v⃗| cos(a − b) = cos(a − b).',
    example: 'Tính giá trị chính xác của sin 75° bằng cách tách 75° = 45° + 30°.',
    exampleSolution: '• Bước 1: Tách góc 75° thành tổng hai góc đặc biệt: 75° = 45° + 30°.\n• Bước 2: Áp dụng công thức cộng: sin(a + b) = sin a cos b + cos a sin b:\n  sin 75° = sin(45° + 30°) = sin 45° cos 30° + cos 45° sin 30°.\n• Bước 3: Thay các giá trị lượng giác đặc biệt:\n  sin 45° = √2/2, cos 30° = √3/2, cos 45° = √2/2, sin 30° = 1/2.\n  sin 75° = (√2/2)(√3/2) + (√2/2)(1/2) = √6/4 + √2/4 = (√6 + √2)/4 ≈ 0.9659.\n• Kết luận: sin 75° = (√6 + √2)/4.',
    tip: 'Chú ý dấu của cos: cos của tổng thì ở giữa là dấu TRỪ: cos(a + b) = cos a cos b − sin a sin b.',
    mistake: 'Viết nhầm sin(a + b) = sin a + sin b (lượng giác không có tính chất phân phối!).',
    question: 'Tính giá trị của biểu thức sin 40° cos 20° + cos 40° sin 20°.',
    answer: 0.866,
    solution: 'Dùng công thức sin(a + b): sin(40° + 20°) = sin 60° = √3/2 ≈ 0.866.',
  },
  {
    id: 'trig-double-triple',
    topic: 'trigonometry',
    name: 'Công thức nhân đôi & nhân ba',
    latex: r`\begin{aligned}\sin 2x &= 2\sin x \cos x\\\cos 2x &= \cos^2 x - \sin^2 x = 2\cos^2 x - 1 = 1 - 2\sin^2 x\\\tan 2x &= \frac{2\tan x}{1 - \tan^2 x}\\\sin 3x &= 3\sin x - 4\sin^3 x,\quad \cos 3x = 4\cos^3 x - 3\cos x\end{aligned}`,
    condition: 'x thỏa mãn điều kiện xác định của các hàm lượng giác có mặt trong biểu thức.',
    theory: 'Công thức nhân đôi thu được trực tiếp từ công thức cộng khi đặt a = b = x. Đặc biệt, cos 2x có tới 3 dạng tương đương thường xuyên được sử dụng để khử số 1 hoặc chuyển đổi giữa sin và cos. Thơ nhớ nhân ba: "Sin ba thì bốn sin ba trừ (đặt dấu trừ giữa 3 sin x − 4 sin³ x); Cos ba thì bốn cos ba đi đầu (4 cos³ x − 3 cos x)".',
    proof: 'Từ sin(x + x) = sin x cos x + cos x sin x = 2 sin x cos x. Tương tự với cos(x + x) = cos²x − sin²x.',
    example: 'Cho sin x = 0.6 và cos x = 0.8. Tính sin 2x và cos 2x.',
    exampleSolution: '• Bước 1: Áp dụng công thức nhân đôi sin 2x = 2 sin x cos x:\n  sin 2x = 2 × 0.6 × 0.8 = 0.96.\n• Bước 2: Áp dụng công thức nhân đôi cos 2x = cos²x − sin²x:\n  cos 2x = 0.8² − 0.6² = 0.64 − 0.36 = 0.28.\n• Bước 3: Kiểm tra lại bằng hệ thức sin²(2x) + cos²(2x):\n  0.96² + 0.28² = 0.9216 + 0.0784 = 1 (hoàn toàn chính xác!).\n• Kết luận: sin 2x = 0.96 và cos 2x = 0.28.',
    tip: 'Khi gặp biểu thức dạng 1 + cos 2x hãy thay bằng 2cos²x; gặp 1 − cos 2x hãy thay bằng 2sin²x để rút gọn căn hoặc tính tích phân.',
    mistake: 'Quên hệ số 2 trong sin 2x: viết sin 2x = sin x cos x (sai!).',
    question: 'Nếu sin x = 1/√2 và cos x = 1/√2 thì sin 2x bằng bao nhiêu?',
    answer: 1,
    solution: 'sin 2x = 2 × (1/√2) × (1/√2) = 2 × (1/2) = 1 (vì 2x = 90°, sin 90° = 1).',
  },
  {
    id: 'trig-power-reduction',
    topic: 'trigonometry',
    name: 'Công thức hạ bậc',
    latex: r`\cos^2 x = \frac{1 + \cos 2x}{2},\qquad \sin^2 x = \frac{1 - \cos 2x}{2},\qquad \tan^2 x = \frac{1 - \cos 2x}{1 + \cos 2x}`,
    condition: 'x ∈ ℝ. Với tan²x cần cos 2x ≠ −1 (tức x ≠ π/2 + kπ).',
    theory: 'Công thức hạ bậc biến đổi bậc hai (sin²x, cos²x) về hàm số bậc nhất với góc gấp đôi (cos 2x). Đây là công cụ thiết yếu số 1 khi tính nguyên hàm và tích phân các hàm lượng giác bậc chẵn (∫ sin²x dx, ∫ cos⁴x dx) cũng như giải phương trình lượng giác.',
    proof: 'Từ hệ thức cos 2x = 2cos²x − 1 suy ra 2cos²x = 1 + cos 2x ⇒ cos²x = (1 + cos 2x)/2. Tương tự với sin²x.',
    example: 'Tìm nguyên hàm của hàm số f(x) = cos²x.',
    exampleSolution: '• Bước 1: Áp dụng công thức hạ bậc để đưa hàm bậc hai về bậc nhất:\n  cos²x = (1 + cos 2x) / 2 = 1/2 + (1/2) cos 2x.\n• Bước 2: Lấy nguyên hàm từng thành phần:\n  ∫ cos²x dx = ∫ [1/2 + (1/2) cos 2x] dx = 1/2 ∫ dx + 1/2 ∫ cos 2x dx.\n• Bước 3: Tính toán nguyên hàm:\n  = x/2 + 1/2 × (sin 2x / 2) + C = x/2 + (sin 2x)/4 + C.\n• Kết luận: Họ nguyên hàm là F(x) = x/2 + (sin 2x)/4 + C.',
    tip: 'Nhớ mẹo dấu: Cos bậc hai thì CỘNG (1 + cos 2x), Sin bậc hai thì TRỪ (1 − cos 2x). Luôn luôn dùng cos 2x ở vế phải!',
    mistake: 'Nghĩ rằng hạ bậc của sin²x liên quan đến sin 2x. Thực chất CẢ HAI công thức hạ bậc đều đưa về cos 2x!',
    question: 'Tính giá trị của 2 cos²(π/4) − 1.',
    answer: 0,
    solution: '2 cos²(π/4) − 1 = cos(2 × π/4) = cos(π/2) = 0.',
  },
  {
    id: 'trig-product-to-sum',
    topic: 'trigonometry',
    name: 'Biến đổi tích thành tổng',
    latex: r`\begin{aligned}\cos a \cos b &= \frac{1}{2}[\cos(a - b) + \cos(a + b)]\\\sin a \sin b &= \frac{1}{2}[\cos(a - b) - \cos(a + b)]\\\sin a \cos b &= \frac{1}{2}[\sin(a + b) + \sin(a - b)]\end{aligned}`,
    condition: 'a, b là các số thực tùy ý.',
    theory: 'Công thức biến đổi tích thành tổng giúp phân rã tích của hai hàm lượng giác thành tổng các hàm đơn lẻ, cực kỳ quan trọng trong xử lý tín hiệu (Fourier transform), âm học, và giải tích tích phân dạng ∫ sin(ax) cos(bx) dx.',
    proof: 'Cộng hoặc trừ hai công thức cộng cos(a − b) = cos a cos b + sin a sin b và cos(a + b) = cos a cos b − sin a sin b.',
    example: 'Biến đổi tích sin 5x cos 3x thành tổng để tính nguyên hàm ∫ sin 5x cos 3x dx.',
    exampleSolution: '• Bước 1: Áp dụng công thức biến đổi tích thành tổng:\n  sin a cos b = (1/2)[sin(a + b) + sin(a − b)] với a = 5x, b = 3x.\n• Bước 2: Thay số và thu gọn góc:\n  sin 5x cos 3x = (1/2)[sin(5x + 3x) + sin(5x − 3x)] = (1/2)[sin 8x + sin 2x].\n• Bước 3: Tính nguyên hàm:\n  ∫ sin 5x cos 3x dx = (1/2) ∫ (sin 8x + sin 2x) dx\n  = (1/2)[−(cos 8x)/8 − (cos 2x)/2] + C = −(cos 8x)/16 − (cos 2x)/4 + C.\n• Kết luận: Tích đã được biến đổi thành (1/2)(sin 8x + sin 2x).',
    tip: 'Luôn để góc lớn hơn ở phía trước (chọn a > b) để hiệu (a − b) dương, tránh phải xử lý dấu trừ bên trong góc.',
    mistake: 'Quên hệ số 1/2 ở vế phải khi áp dụng công thức biến đổi tích thành tổng.',
    question: 'Tính giá trị của 2 cos 45° cos 15°.',
    answer: 1.366,
    solution: '2 cos 45° cos 15° = cos(45° − 15°) + cos(45° + 15°) = cos 30° + cos 60° = √3/2 + 1/2 ≈ 0.866 + 0.5 = 1.366.',
  },
  {
    id: 'trig-sum-to-product',
    topic: 'trigonometry',
    name: 'Biến đổi tổng thành tích',
    latex: r`\begin{aligned}\cos u + \cos v &= 2\cos\frac{u + v}{2}\cos\frac{u - v}{2}\\\cos u - \cos v &= -2\sin\frac{u + v}{2}\sin\frac{u - v}{2}\\\sin u + \sin v &= 2\sin\frac{u + v}{2}\cos\frac{u - v}{2}\\\sin u - \sin v &= 2\cos\frac{u + v}{2}\sin\frac{u - v}{2}\end{aligned}`,
    condition: 'u, v là các số thực tùy ý.',
    theory: 'Biến đổi tổng lượng giác thành tích là vũ khí chủ lực để đưa phương trình lượng giác về dạng tích f(x) · g(x) = 0 để tìm nghiệm. Bài thơ truyền miệng dễ nhớ: "Cos cộng cos bằng hai cos cos; Cos trừ cos bằng trừ hai sin sin; Sin cộng sin bằng hai sin cos; Sin trừ sin bằng hai cos sin".',
    proof: 'Đặt a = (u + v)/2 và b = (u − v)/2 trong các công thức biến đổi tích thành tổng, khi đó u = a + b và v = a − b.',
    example: 'Giải phương trình lượng giác: sin 3x + sin x = 0.',
    exampleSolution: '• Bước 1: Áp dụng công thức biến đổi sin cộng sin bằng hai sin cos:\n  sin 3x + sin x = 2 sin[(3x + x)/2] cos[(3x − x)/2] = 2 sin 2x cos x.\n• Bước 2: Phương trình trở thành:\n  2 sin 2x cos x = 0 ⇔ sin 2x = 0 hoặc cos x = 0.\n• Bước 3: Tìm nghiệm:\n  - sin 2x = 0 ⇔ 2x = kπ ⇔ x = kπ/2 (k ∈ ℤ).\n  - cos x = 0 ⇔ x = π/2 + kπ (tập nghiệm này đã chứa trong họ x = kπ/2).\n• Kết luận: Nghiệm của phương trình là x = kπ/2 (k ∈ ℤ).',
    tip: 'Chú ý dấu trừ phía trước ở công thức hiệu hai cos: cos u − cos v = −2 sin... sin...',
    mistake: 'Quên chia 2 cho tổng và hiệu góc ở bên trong các hàm lượng giác ở vế phải.',
    question: 'Rút gọn biểu thức (sin 50° + sin 10°) / cos 20°. Kết quả bằng bao nhiêu?',
    answer: 1,
    solution: 'sin 50° + sin 10° = 2 sin 30° cos 20° = 2 × (1/2) × cos 20° = cos 20°. Chia cho cos 20° được 1.',
  },
  {
    id: 'trig-equations',
    topic: 'trigonometry',
    name: 'Phương trình lượng giác cơ bản',
    latex: r`\begin{aligned}\sin x = \sin\alpha &\iff x = \alpha + k2\pi \quad\lor\quad x = \pi - \alpha + k2\pi\\\cos x = \cos\alpha &\iff x = \pm\alpha + k2\pi\\\tan x = \tan\alpha &\iff x = \alpha + k\pi\quad(k \in \mathbb{Z})\end{aligned}`,
    condition: 'Phương trình sin x = m và cos x = m chỉ có nghiệm khi −1 ≤ m ≤ 1. Với tan x = m luôn có nghiệm với mọi m ∈ ℝ.',
    theory: 'Hàm số lượng giác có tính chất tuần hoàn (chu kỳ của sin, cos là 2π, của tan, cot là π), do đó phương trình lượng giác khi có nghiệm sẽ có vô số nghiệm phụ thuộc số nguyên k ∈ ℤ. Để tìm nghiệm trên một đoạn [a, b], ta cho k các giá trị nguyên thỏa mãn bất phương trình a ≤ x_k ≤ b.',
    proof: 'Dựa trên đối xứng của đường tròn lượng giác: hai điểm có cùng tung độ (sin) đối xứng qua trục tung nên góc là α và π − α; hai điểm có cùng hoành độ (cos) đối xứng qua trục hoành nên góc là ±α.',
    example: 'Giải phương trình sin x = 1/2 trên khoảng [0, 2π].',
    exampleSolution: '• Bước 1: Nhận diện góc đặc biệt: sin(π/6) = 1/2 nên phương trình có dạng sin x = sin(π/6).\n• Bước 2: Áp dụng công thức nghiệm tổng quát:\n  - Nhánh 1: x = π/6 + k2π (k ∈ ℤ)\n  - Nhánh 2: x = π − π/6 + k2π = 5π/6 + k2π (k ∈ ℤ).\n• Bước 3: Chọn nghiệm thuộc khoảng [0, 2π]:\n  - Với k = 0: x₁ = π/6, x₂ = 5π/6.\n  - Với k ≠ 0: các nghiệm nằm ngoài khoảng [0, 2π].\n• Kết luận: Trên [0, 2π], phương trình có đúng 2 nghiệm là x = π/6 (30°) và x = 5π/6 (150°).',
    tip: 'Hàm tan và cot chỉ có chu kỳ kπ (không phải k2π như sin và cos).',
    mistake: 'Phương trình sin x = 2 vô nghiệm vì −1 ≤ sin x ≤ 1, không được bấm máy tính giải nghiệm thực.',
    question: 'Số nghiệm của phương trình cos x = 0 trên đoạn [0, 2π] là bao nhiêu?',
    answer: 2,
    solution: 'cos x = 0 khi x = π/2 và x = 3π/2 trên [0, 2π]. Có đúng 2 nghiệm.',
  },
  {
    id: 'trig-derivatives',
    topic: 'trigonometry',
    name: 'Đạo hàm & Nguyên hàm lượng giác',
    latex: r`\begin{aligned}(\sin x)' &= \cos x,\quad (\cos x)' = -\sin x,\quad (\tan x)' = \frac{1}{\cos^2 x} = 1 + \tan^2 x\\\int \cos x\,dx &= \sin x + C,\quad \int \sin x\,dx = -\cos x + C,\quad \int \frac{1}{\cos^2 x}\,dx = \tan x + C\end{aligned}`,
    condition: 'Các góc tính bằng RADIAN (bắt buộc trong giải tích đạo hàm và tích phân).',
    theory: 'Đạo hàm của các hàm lượng giác đo tốc độ biến thiên góc và hình chiếu. Đặc biệt: đạo hàm của sin là +cos, nhưng đạo hàm của cos là −sin (chú ý dấu trừ!). Khi tích phân, quy tắc ngược lại: nguyên hàm của sin x là −cos x + C, nguyên hàm của cos x là +sin x + C.',
    proof: 'Dùng định nghĩa đạo hàm f′(x) = lim_{h→0} [f(x+h) − f(x)]/h và sử dụng giới hạn cơ bản lim_{u→0} (sin u)/u = 1.',
    example: 'Tính đạo hàm của hàm số f(x) = x · sin x tại điểm x = π/2.',
    exampleSolution: '• Bước 1: Nhận dạng quy tắc đạo hàm của tích: (uv)′ = u′v + uv′ với u = x, v = sin x.\n• Bước 2: Tính đạo hàm từng thành phần:\n  u′ = (x)′ = 1.\n  v′ = (sin x)′ = cos x.\n• Bước 3: Áp dụng công thức đạo hàm tích:\n  f′(x) = 1 × sin x + x × cos x = sin x + x cos x.\n• Bước 4: Thay giá trị x = π/2:\n  f′(π/2) = sin(π/2) + (π/2) cos(π/2) = 1 + (π/2)(0) = 1.\n• Kết luận: Đạo hàm tại x = π/2 bằng 1.',
    tip: 'Nhớ vòng tròn lượng giác đạo hàm: Đi theo chiều kim đồng hồ sin → cos → −sin → −cos → sin là ĐẠO HÀM; đi ngược chiều kim đồng hồ là NGUYÊN HÀM.',
    mistake: 'Tính đạo hàm khi góc x đang ở đơn vị độ (°). Công thức vi tích phân chỉ đúng khi x ở đơn vị RADIAN!',
    question: 'Tính giá trị đạo hàm của f(x) = sin(2x) tại x = 0.',
    answer: 2,
    solution: 'f′(x) = 2 cos(2x). Tại x = 0: f′(0) = 2 cos(0) = 2 × 1 = 2.',
  },
];
