// UnicodeMath linear notation: explicit grouping keeps fractions and indices unambiguous.
export const unicodeFormulas: Record<string,string> = {
 f1:'(a+b)² = a²+2ab+b²', f2:'(a−b)² = a²−2ab+b²', f3:'a²−b² = (a−b)(a+b)',
 f4:'(a±b)³ = a³±3a²b+3ab²±b³', f5:'a³±b³ = (a±b)(a²∓ab+b²)',
 f6:'A/B+C/D = (AD+BC)/(BD)', f7:'P(x) = (x−a)Q(x)+P(a)',
 f8:'∑_(k=0)^n▒a_k x^k ≡ ∑_(k=0)^n▒b_k x^k ⇔ a_k=b_k',
 f9:'ax+b=0 ⇒ x=−b/a', f10:'Δ=b²−4ac,  x=(−b±√Δ)/(2a)',
 f11:'D=a₁b₂−a₂b₁,  x=(c₁b₂−c₂b₁)/D', f12:'|x| = {█(x&x≥0@−x&x<0)┤', f13:'f(x)=ax+b',
 f14:'a^m a^n = a^(m+n),  (a^m)^n = a^(mn)', f15:'√(a²)=|a|,  √(ab)=√a √b',
 f16:'∛(a³)=a', f17:'√(n&a)=a^(1/n)', f18:'1/(√a+√b)=(√a−√b)/(a−b)',
 f19:'(a₁+⋯+a_n)/n ≥ √(n&a₁⋯a_n)',
 f20:'(∑_i▒a_i b_i)² ≤ (∑_i▒(a_i)^2)(∑_i▒(b_i)^2)',
 f21:'f(∑_i▒w_i x_i) ≤ ∑_i▒w_i f(x_i)',
 f22:'∑_i▒|a_i b_i| ≤ (∑_i▒|a_i|^p)^(1/p)(∑_i▒|b_i|^q)^(1/q)',
 f23:'(∑_i▒|a_i+b_i|^p)^(1/p) ≤ (∑_i▒|a_i|^p)^(1/p)+(∑_i▒|b_i|^p)^(1/p)',
 f24:'(∑_i▒a_i b_i)/n ≥ ((∑_i▒a_i)/n)((∑_i▒b_i)/n)',
 f25:'a³+b³+c³+3abc ≥ ab(a+b)+bc(b+c)+ca(c+a)', f26:'(1+x)^n ≥ 1+nx',
 f27:'a/(b+c)+b/(c+a)+c/(a+b) ≥ 3/2',
 f28:'u_n=u₁+(n−1)d,  S_n=n(2u₁+(n−1)d)/2',
 f29:'u_n=u₁q^(n−1),  S_n=u₁(1−q^n)/(1−q)', f30:'S_∞=u₁/(1−q)',
 f31:'log_a b=c ⇔ a^c=b', f32:'log_a(xy)=log_a x+log_a y,  log_a b=(ln b)/(ln a)',
 f33:'lg x=log_10 x,  ln x=log_e x', f34:'z=a+bi,  i²=−1',
 f35:'|z|=√(a²+b²),  z̄=a−bi,  zz̄=|z|²', f36:'z=r(cos θ+i sin θ),  r=|z|',
 f37:'[r(cos θ+i sin θ)]^n=r^n(cos(nθ)+i sin(nθ))', f38:'e^(iθ)=cos θ+i sin θ',
 f39:'lim_(x→0)▒(sin x)/x=1', f40:'f′(x)=lim_(h→0)▒(f(x+h)−f(x))/h,  (x^n)′=nx^(n−1)',
 f41:'(uv)′=u′v+uv′,  (f∘g)′=(f′∘g)g′', f42:'∫▒x^n dx=x^(n+1)/(n+1)+C',
 f43:'∫_a^b▒f(x) dx=F(b)−F(a)',
};
